- .gitignore
- CMakeLists.txt
- LICENSE.TXT
- README.md
- cmake/helpers.cmake
- cmake/unified-memory-framework-config.cmake.in
- include/umf.h
- include/umf/base.h
- include/umf/memory_pool.h
- include/umf/memory_pool_ops.h
- include/umf/memory_provider.h
- include/umf/memory_provider_ops.h
- src/CMakeLists.txt
- src/memory_pool.c
- src/memory_pool_default.c
- src/memory_pool_internal.h
- src/memory_provider.c
- src/memory_provider_get_last_failed.c
- src/memory_provider_internal.h
- src/utils/utils.h
- src/utils/utils_posix.c
- src/utils/utils_windows.c
- test/CMakeLists.txt
- test/base.cpp
- test/common/base.hpp
> Copy UMF code from UR repo

- include/umf/memory_pool.h
- include/umf/memory_pool_ops.h
- src/memory_pool_default.c
- src/memory_pool_internal.h
- src/pool/pool_null.c
- src/pool/pool_trace.c
Pool is a combination of memory provider and pool manager. The umfPoolCreate function s is refactored to accept only a single memory provider as we agreed.
> Refactor umfPoolCreate to accept only one provider

- src/pool/disjoint/pool_disjoint_heap_manager.cpp
Do not use C++ designated initializers,
because they are available starting from C++20,
when [-Wpedantic] is set and they treated
as an error on Windows.
Requires:
> Do not use C++ designated initializers

- .clang-format
- .github/workflows/basic.yml
That builds the UMF and runs tests.
Clang-format check is disabled for now since there are some formatting issues and I didn't want to create conflicts for other PRs by fixing them.
> Add simple CI

- test/common/CMakeLists.txt
The `test/common/CMakeLists.txt` file has to contain `target_include_directories()` pointing relatively to `/include`, so that UMF is compatible with `FetchContent`.
> Add missing target_include_directories

- src/pool/disjoint/pool_disjoint.cpp
**Description:**
This change modifies calloc/realloc ops and allows to pull status by tests, especially when some functions are not supported.
Required by: #11
**Note:**
After merging, the mentioned PR should work out of the box. Please rebase and re-run GHA.
> Add missing functions to disjoint pool ops

- CMakeLists.txt
Include `CMakePackageConfigHelpers ` module,
because we use the `write_basic_package_version_file()` function.
**Fix required by oneCCL.**
> Include CMakePackageConfigHelpers module

- src/pool/disjoint/pool_disjoint.cpp
- src/pool/disjoint/pool_disjoint_impl.hpp
This PR removes duplications of members. 
Instead of, the DisjointPoolConfig will extend pool params.
> Remove duplication of DisjointPoolConfig members

- src/provider/provider_coarse.c
Use coarse_memory_provider_free() to free the block instead of changing values of internals.
> Use coarse_memory_provider_free() to free the block

- src/critnib/critnib.c
- src/utils/utils.h
I have no idea how it worked on windows (or did it?) in UR.
Here's a branch rebased on top of Rafal's branch with windows CI where all the tests are passing: https://github.com/igchor/unified-memory-framework/tree/fix_windows_ci
> Fix critnib on windows

- include/pool/pool_disjoint.h
- src/pool/disjoint/pool_disjoint_impl.cpp
- src/pool/disjoint/pool_disjoint_impl.hpp
- test/CMakeLists.txt
- test/c_api/disjoint_pool.c
- test/common/test_helpers.h
C does not allow setting default values as part of struct definition.
> Fix disjoint_pool compilation error in C

- include/pool/pool_disjoint.h
- src/common/umf_helpers.hpp
- src/pool/disjoint/pool_disjoint.cpp
- src/pool/disjoint/pool_disjoint_impl.cpp
- src/pool/disjoint/pool_disjoint_impl.hpp
Relies on: https://github.com/oneapi-src/unified-memory-framework/pull/29
> Remove DisjointPoolConfig and use umf_helpers to expose DisjointPool ops

- test/common/pool.hpp
I have found these minor issues during the work on the tests for IPC API
> Adding default values for local variables in test infrastructure

- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- src/provider/provider_os_memory_linux.c
Unify translation functions in `os_copy_and_translate_params()`.
> Unify translation functions in os_copy_and_translate_params()

- src/provider/provider_os_memory.c
Add error messages to `os_copy_and_translate_params()`.
Requires:
> Add error messages to os_copy_and_translate_params()

- include/umf/providers/provider_coarse.h
Fix error: unknown type name ‘bool’:
```
include/umf/providers/provider_coarse.h:17:5:
error: unknown type name ‘bool’
17 |     bool immediate_init; // pre-allocate soft limit
|     ^~~~
include/umf/providers/provider_coarse.h:18:5:
error: unknown type name ‘bool’
18 |     bool trace;
|     ^~~~
```
> [COARSE] Fix error unknown type name 'bool'

- test/CMakeLists.txt
Add arguments NAME, SRCS and LIBS to add_umf_test():
- NAME - a name of the test
- SRCS - source files
- LIBS - libraries to be linked with.
> Add arguments NAME, SRCS and LIBS to add_umf_test()

- src/common/umf_helpers.hpp
- test/common/pool.hpp
- test/common/provider.hpp
- test/disjoint_pool.cpp
- test/memoryPool.hpp
- test/memoryPoolAPI.cpp
- test/memoryProviderAPI.cpp
Expose ops for all pools/providers implemented in tests and change fixtures to accepts ops and params, instead of factory functions.
Also, remove no longer needed pool/providerMakeUnique functions from umf_helpers.hpp.
> Simplify test fixtures

- CMakeLists.txt
- benchmark/CMakeLists.txt
- benchmark/ubench.c
- benchmark/ubench.h
An example of output:
```
[==========] Running 3 benchmarks.
[ RUN      ] simple.glibc_malloc
[       OK ] simple.glibc_malloc (mean 1.924ms, confidence interval +- 1.019370%)
[ RUN      ] simple.os_memory_provider
[       OK ] simple.os_memory_provider (mean 1.151ms, confidence interval +- 0.866927%)
[ RUN      ] simple.disjoint_pool_with_os_memory_provider
[       OK ] simple.disjoint_pool_with_os_memory_provider (mean 1.189ms, confidence interval +- 1.175367%)
[==========] 3 benchmarks ran.
[  PASSED  ] 3 benchmarks.
```
> Add micro benchmark

- test/CMakeLists.txt
- test/common/test_helpers.c
- test/common/test_helpers.h
- test/disjoint_pool.cpp
- test/malloc_compliance_tests.cpp
- test/malloc_compliance_tests.hpp
- test/memoryPool.hpp
- test/memoryPoolAPI.cpp
They will be useful to test pool managers.
See https://github.com/oneapi-src/unified-memory-framework/pull/65 for an example.
> Add malloc compliance tests

- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- src/provider/provider_os_memory_linux.c
- test/provider_os_memory.cpp
Fix `os_alloc()` of OS memory provider. Make it return aligned address. Replace `os_mmap()` with `os_mmap_aligned()` that returns aligned address.
> Fix os_alloc() of OS memory provider to return aligned address

- test/common/test_helpers.c
- test/common/test_helpers.h
- test/malloc_compliance_tests.cpp
Make all names of functions in test_helpers.c camelCase. Replace:
`is_filled_with_char()` -> `bufferIsFilledWithChar()`
`is_same_content()` -> `buffersHaveSameContent()`
`is_aligned()` -> `addressIsAligned()`
> Make all names of functions in test_helpers.c camelCase

- src/memory_pool.c
- src/memory_pool_default.c
- src/memory_pool_internal.h
- src/memory_pool_tracking.c
- test/CMakeLists.txt
- test/memory_pool_internal.cpp
... that creates a pool owning the provided memory provider.
> Add the umfPoolCreateEx internal function

- CMakeLists.txt
- benchmark/CMakeLists.txt
- cmake/helpers.cmake
- src/CMakeLists.txt
- src/critnib/critnib.c
- src/pool/pool_disjoint.cpp
- test/CMakeLists.txt
- test/common/CMakeLists.txt
- test/memory_pool_internal.cpp
Fixes required to use UMF as an external project (with `FetchContent`):
- add `UMF_CMAKE_SOURCE_DIR`
- add include directories
> Fixes required to use UMF as an external project

- benchmark/CMakeLists.txt
- cmake/helpers.cmake
- src/CMakeLists.txt
- test/CMakeLists.txt
- test/common/CMakeLists.txt
Some libraries that were dependencies of UMF were not link to UMF but rather directly to tests and benchmark. Fix this by extending add_umf_library and passing required libs there.
> Fix linking

- include/umf/memory_provider.h
- include/umf/memory_provider_ops.h
The alignment of `umfMemoryProviderAlloc()` has to be a multiple or a divider of the minimum page size.
> Make alignment of umfMemoryProviderAlloc() more specific

- CMakeLists.txt
- benchmark/CMakeLists.txt
- src/CMakeLists.txt
- src/pool/CMakeLists.txt
- test/CMakeLists.txt
Please, review only the last commit. This PR is based on #73 .
Refactor UMF installation
- remove tests from the installation
- rename libunified-memory-framework.a
- install license file
- change hardcoded installation paths to prefixed with CMake vars
- remove installation paths that are equal to default ones
- remove alias targets usages where not needed
> Cleanup install dir

- include/umf/providers/provider_os_memory.h
- src/provider/provider_os_memory.c
- test/provider_os_memory.cpp
The alignment has to be a multiple or a divider of the minimum page size.
Remove the `UMF_OS_RESULT_ERROR_WRONG_ALIGNMENT` error.
Ref: #90
> Fix checking alignment in os_alloc()

- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- src/provider/provider_os_memory_linux.c
- test/provider_os_memory.cpp
Ref: https://github.com/oneapi-src/unified-memory-framework/pull/74#discussion_r1432442666
> Make sure pointers are correctly aligned in os_mmap_aligned()

- CMakeLists.txt
- README.md
- benchmark/CMakeLists.txt
- benchmark/ubench.c
Turning off disjoint pool (using `UMF_BUILD_LIBUMF_POOL_DISJOINT`) should not turn off benchmark (as it is now).
> Fix running benchmark without disjoint pool

- .github/workflows/benchmarks.yml
- benchmark/CMakeLists.txt
- benchmark/ubench.c
> Add TBB pool manager to benchmark

- test/provider_os_memory.cpp
Add tests for alignment in OS memory provider and refactor tests to use gtest's `TEST_P()`.
> Add tests for alignment in OS memory provider

- test/malloc_compliance_tests.cpp
> Malloc should return address aligned to 8 bytes

- src/provider/provider_os_memory.c
- test/provider_os_memory.cpp
> Ignore error of os_munmap() when size equals 0

- test/c_api/disjoint_pool.c
- test/common/test_helpers.h
This PR adds asserts for C tests (using the implementation from pmemstream: https://github.com/pmem/pmemstream/blob/master/tests/common/unittest.h) and uses them in a c test for disjoint pool.
> Add asserts for C tests

- CMakeLists.txt
Fix "cmake_uninstall.cmake.in does not exist".
Needed for integration with UR.
> Fix building UMF via FetchContent

- src/pool/pool_jemalloc.c
For OS provider, merge, split and commits are nops. This means we should return false, not true from
those hooks.
Ref: https://github.com/memkind/memkind/blob/c425635feb0367c43da8fa0deadb50a4bc127988/src/memkind_arena.c
@kswiecicki this should fix the ASAN issue.
> Fix return values from jemalloc hooks

- src/pool/pool_jemalloc.c
Fix a regression introduced by commit 459a492de41a647d6dab2364d2f15c9603bf7a71
With this commit the jemalloc_pool test fails very often, see:
https://github.com/ldorau/unified-memory-framework/actions/workflows/basic.yml?query=branch%3ATest_real_make_install
This patch fixes this issue.
Ref: 459a492de41a647d6dab2364d2f15c9603bf7a71
> Fix arena_extent_split() and arena_extent_merge()

- .github/workflows/basic.yml
- .github/workflows/benchmarks.yml
- .github/workflows/codeql.yml
- .github/workflows/pr_push.yml
- .github/workflows/spellcheck.yml
This commit converts workflows to reusable workflows.
Also, it reduces the number of Actions entries started by a single PR/push.
Depends on: #113
> [CI] Add reusable workflows

- test/CMakeLists.txt
The test calls `numa_available` and `numa_max_node` from libnuma
> Add missing lib dependency to the test

- test/memoryPoolAPI.cpp
The pool has not been destroyed.
> Fix small memory leak in the memoryPoolWithCustomProvider test

- .github/workflows/basic.yml
- .github/workflows/pr_push.yml
This PR introduces a coding style check.
> [CI] Add coding style check as prerequisite

- test/malloc_compliance_tests.cpp
it only checked part of the allocated memory.
> Extend check in calloc_compliance_test

- test/memspace_numa.cpp
Fix skipping memspace_numa tests.
`GTEST_SKIP()` called in `numa_nodes_test` does not skip `numa_memspace_test` and `numa_memspace_provider_test` tests.
It fixes the following test failure:
```
[----------] 1 test from numa_memspace_test
[ RUN      ] numa_memspace_test.provider_from_numa_memspace
/home/ldorau/work/unified-memory-framework/test/memspace_numa.cpp:21: Skipped
Failed to initialize libnuma
/home/ldorau/work/unified-memory-framework/test/memspace_numa.cpp:43: Failure
Expected equality of these values:
ret
Which is: 3
UMF_RESULT_SUCCESS
Which is: 0
umf_test-memspace_numa: /home/ldorau/work/unified-memory-framework/src/memspace.c:101: umfMemspaceDestroy: Assertion `memspace' failed.
90% tests passed, 1 tests failed out of 10
Label Time Summary:
umf    =   2.71 sec*proc (10 tests) …
```
> Fix skipping memspace_numa tests

- src/pool/pool_scalable.c
- src/utils/utils_sanitizers.h
To fix false positives from TSAN.
Found by @kswiecicki. Can you verify that this fixes the issue?
> Add TSAN annotations to pool_scalable

- .github/workflows/basic.yml
- CMakeLists.txt
- README.md
- cmake/helpers.cmake
- src/critnib/critnib.c
- test/common/provider.hpp
- test/common/test_helpers.h
Currently, there's a problem with leak reported in jemalloc pool implementation. For this reason sanitizers are temporarily disabled on CI for cases when pool tracking is enabled.
Leak points to some `tracker_value_t` not being freed after being allocated by `arena_extent_alloc` jemalloc extent hook as a part of `umfMemoryProviderAlloc` call.
Log reported by leak sanitizer: [leak.log](https://github.com/oneapi-src/unified-memory-framework/files/13887164/LastTest.log)
> Add sanitizers

- src/provider/provider_tracking.c
Tracking provider cannot change behavior of the upstream provider. Tracking provider should be transparent for the upstream provider.
> Tracking provider cannot change behavior of upstream provider

- .github/workflows/pr_push.yml
If not specified, workflows from the same commit will be used.
Ref:
https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
This PR is prepared due to an issue encountered around sanitizers... (ref. #154).
// Tested when it should not work: https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/7571300540/job/20618545502
> [CI] Use local reusable workflows

- .github/workflows/basic.yml
- cmake/helpers.cmake
Enabling ASan for MSVC is more complicated than other compilers and wasn't working correctly. The changes made in https://github.com/oneapi-src/unified-memory-framework/pull/121 were not properly tested by the GHA jobs. To test the changes in `basic.yml` workflow file on this PR, I've temporarily changed the `.github/workflows/pr_push.yml` to retrieve workflow file from my fork.
For the time being, enabling ASan workflows on MSVC requires further investigation. Currently, even though CMake positively tests MSVC for ASan support and compiles the UMF project without errors, the UMF tests return `0xc0000135` error code which is `STATUS_DLL_NOT_FOUND`. Appending the `PATH` env var with the directory containing ASan lib (eg. `C:\Program Files\Microsoft Visual …
> ASan workflow fix

- src/pool/pool_jemalloc.c
@pbalcer why this function wasn't implemented in memkind?  My understanding is that without this function extent deallocation is deferred to when the arena is destroyed. Is that true? Is there any reason we should implement it?
> Implement arena_extent_dalloc in pool_jemalloc

- src/pool/CMakeLists.txt
- test/CMakeLists.txt
This forces the linker to link with libc before linking with jemalloc. Because of that, jemalloc will not override symbols for malloc/free.
Without this patch, we would call `malloc` from within the `arena_extent_alloc`  (jemalloc hook) that would be intercepted by jemalloc.
This fixes the issue with debug jemalloc when running tests with tracking enabled:
```
<jemalloc>: Should own 0 locks of rank >= 14: extent_grow(17)
Aborted (core dumped)
```
> Link jemalloc pool and test with libc explicitly to avoid recursive calls to jemalloc (tmp fix)

- include/umf/memory_provider.h
- include/umf/memory_provider_ops.h
- src/memory_provider.c
- src/pool/pool_jemalloc.c
- src/pool/pool_scalable.c
- src/provider/provider_os_memory.c
- src/provider/provider_tracking.c
- src/provider/provider_tracking.h
- src/provider/provider_tracking_linux.c
- src/provider/provider_tracking_windows.c
- src/utils/utils_concurrency.h
That is needed to support jemalloc (avoid leaking memory).
@kswiecicki could you verify if this solves all the memory leaks? On my machine, it seems to work fine after those changes.
> Implement umfMemoryProviderAllocation[Split/Merge]

- test/malloc_compliance_tests.cpp
It should only be called once, to initialize the seed.
Otherwise, all values returned by rand() will be the same.
> Do not call srand before each rand

- .github/workflows/basic.yml
It's a solution for the problems mentioned in https://github.com/oneapi-src/unified-memory-framework/pull/154. The solution is to include `TheMrMilchmann/setup-msvc-dev@v3` action with a specific toolset version `14.38.33130` when compiling UMF with ASan enabled on Windows.
Solution source: https://github.com/actions/runner-images/issues/8891.
> Add ASan workflow for Windows

- src/critnib/critnib.c
- src/memory_pool.c
- src/memory_provider.c
- src/utils/utils_common.h
- src/utils/utils_concurrency.h
- test/common/base.hpp
- test/memoryPoolAPI.cpp
- test/memoryProviderAPI.cpp
closes https://github.com/oneapi-src/unified-memory-framework/issues/162
> Add checks for pool and provider handles

- include/umf/providers/provider_os_memory.h
- src/memory_targets/memory_target_numa.c
- test/pools/jemalloc_pool.cpp
- test/pools/scalable_pool.cpp
- test/provider_os_memory.cpp
- test/provider_os_memory_config.cpp
Depends on: https://github.com/oneapi-src/unified-memory-framework/pull/171
> Add jemalloc test for metadata allocation

- src/CMakeLists.txt
- src/base_alloc/base_alloc.c
- src/base_alloc/base_alloc_linear.c
- src/base_alloc/base_alloc_linear.h
- src/utils/utils_common.h
- src/utils/utils_concurrency.h
- src/utils/utils_windows_concurrency.c
- test/CMakeLists.txt
- test/test_base_alloc_linear.c
Add a MT-safe linear base allocator. It is useful for a few, small and different size allocations for a most/whole life-time of an application (free() is not available).
It is needed by https://github.com/oneapi-src/unified-memory-framework/pull/178 and https://github.com/oneapi-src/unified-memory-framework/pull/170.
> Add linear base allocator

- .github/workflows/basic.yml
- test/test_base_alloc.c
This PR introduces Intel C/C++ Compiler provided as a Docker image.
Used VM: Ubuntu 22.04
Used container: intel/oneapi:latest (icx/icpx 2024.02)
Other jobs are VM-based (Ubuntu 20.04/22.04, Windows 2019 or MacOSX) and those runners have other paths (github.workspace etc.) than steps executed under Docker in those VM's.
To avoid ambiguity there is a mounting between host and container.
The privileged option is related to NUMA requirements. Maybe it is possible to limit permission just by "--sys-cap SYS_CAP_NICE", but I don't test this option.
As we talked, it will be refactored and please keep it in mind during review.
> Add job with Intel C/C++ Compiler

- .github/workflows/basic.yml
Enable OS provider in builds in the include section. All variables have to be set explicitly in the include section. The values set in the matrix section are NOT copied to the include section.
> Enable OS provider in builds in the include section

- test/poolFixtures.hpp
This solves some of the issues under drd and valgrind:
https://github.com/oneapi-src/unified-memory-framework/issues/156
https://github.com/oneapi-src/unified-memory-framework/issues/157
> Remove unnecessary print from tests

- .github/workflows/pr_push.yml
head_ref is only available on PRs. Without this change all pushes ended up being in one group. On upstream it cancels all consecutive main pushes (which is a little undesired), but on forks it canceled all consecutive pushes (which is undesired if you want to test multiple different branches).
This solution is copy-pasted from the UR repo and it works there just fine.
On pushes the group name was like: `-workflow_name`.
> [CI] Fix concurrency group name for PR/push workflow

- .github/workflows/codeql.yml
The version v2 of the CodeQL GitHub Action uses deprecated Node 16 Node.js resulting in CI warnings.
```
CodeQL / Analyze (ubuntu-latest)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: github/codeql-action/init@v2, github/codeql-action/analyze@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
CodeQL / Analyze (ubuntu-latest)
CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
```
> Upgrade version of CodeQL CI action

- cmake/helpers.cmake
- src/critnib/critnib.c
- src/utils/utils_common.h
> Use base allocator in critnib

- .github/workflows/docs.yml
[Preview](https://github.com/PatKamin/unified-memory-framework/actions/runs/7727031302) of a successful Pages build.
The old version of the upload-artifact action uses old Node.js 16 version resulting in CI warnings below. The other action had to be bumped to be compliant.
[build with warning](https://github.com/PatKamin/unified-memory-framework/actions/runs/7726381566)
```Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.```
> Upgrade versions of actions in GitHub Pages CI

- .github/workflows/.spellcheck-conf.toml
- .github/workflows/nightly.yml
- test/supp/umf_test-provider_os_memory_config.supp
- test/test_valgrind.sh
The current script just checks if there is the
"ERROR SUMMARY: 0 errors from 0 contexts"
line in the output of a test.
It turned out that there can be many lines starting with
"ERROR SUMMARY:" in the output of one test - some with
errors and some without, so the current approach is wrong.
We have to check if there are no other lines starting with
"ERROR SUMMARY:" than this:
"ERROR SUMMARY: 0 errors from 0 contexts" instead.
> Fix the test_valgrind.sh script running tests under valgrind

- benchmark/ubench.c
- include/umf/pools/pool_disjoint.h
- include/umf/pools/pool_jemalloc.h
- include/umf/pools/pool_scalable.h
- include/umf/providers/provider_os_memory.h
- src/memory_targets/memory_target_numa.c
- src/pool/pool_disjoint.cpp
- src/pool/pool_jemalloc.c
- src/pool/pool_scalable.c
- src/provider/provider_os_memory.c
- test/c_api/disjoint_pool.c
- test/pools/disjoint_pool.cpp
- test/pools/jemalloc_pool.cpp
- test/pools/scalable_pool.cpp
- test/provider_os_memory.cpp
- test/provider_os_memory_config.cpp
- test/provider_os_memory_multiple_numa_nodes.cpp
instead of exposing a global variable. Variables are problematic on windows where __declspec(dllimport) must be used in user code on each imported variable declaration.
> Expose provider/pool ops through a getter function

- .github/workflows/pr_push.yml
- CMakeLists.txt
- README.md
- cmake/helpers.cmake
- test/test_base_alloc_linear.c
C++17 is required to build UMF only when two flags are enabled:
- UMF_BUILD_LIBUMF_POOL_DISJOINT,
- UMF_BUILD_TESTS.
In other cases, all is needed is a C compiler.
> Update C++17 requirement cases

- src/CMakeLists.txt
- test/CMakeLists.txt
base_alloc is an internal compontent of umf and it's symbols should not be visible outside.
This avoids linking error after introducing .def/.map files and limiting symbol visibility.
> Build base_alloc test with base_alloc sources

- src/base_alloc/base_alloc.c
that verifies that ptr belongs to a specific pool. This will be especially useful after https://github.com/oneapi-src/unified-memory-framework/pull/203 is merged.
> Add extra debug check for base_alloc

- README.md
- include/umf/pools/pool_proxy.h
- src/CMakeLists.txt
- src/pool/pool_proxy.c
- test/common/pool.hpp
- test/memoryPoolAPI.cpp
- test/test_make_install.txt
a pool that forwards all (supported) requests to the memory provider.
> Add proxy_pool

- test/CMakeLists.txt
- test/c_api/multi_pool.c
To verify that:
- tracking works across different type of pools
- we can succesfully link multiple pool libs to a single app
> Add tests with multiple pools

- src/base_alloc/base_alloc_global.c
- src/base_alloc/base_alloc_global.h
- src/libumf_linux.c
- src/libumf_windows.c
- src/pool/pool_jemalloc.c
- src/pool/pool_scalable.c
- src/utils/utils_windows_concurrency.c
Initializing the global pool in libumf and in each pool separately led to problems with double initialization when multiple pools were used in a single application (and static libumf).
To avoid this problem, use util_init_once inside umf_ba_get_pool instead of having explicit constructor/destructor.
This fixes an issue exposed by:  0c55d8f55d583e87af4f08157c0ad1c828a02ac6
> Unify global umf_ba_pool_t initialization

- benchmark/ubench.c
- include/umf/providers/provider_os_memory.h
- src/memory_targets/memory_target_numa.c
- src/provider/provider_os_memory.c
- test/provider_os_memory.cpp
- test/provider_os_memory_config.cpp
@vinser52 @pbalcer please review. Each commit is an independent change.
> Cleanup OS provider config API

- src/base_alloc/base_alloc_linear.c
- test/test_base_alloc_linear.cpp
Make it possible to allocate more than the initial pool size of the linear allocator.
It fixes a serious bug leading to a segfault in the linear base allocator.
> Fix: make it possible to allocate more than initial pool size

- src/base_alloc/base_alloc.c
- src/base_alloc/base_alloc_linear.c
- src/utils/utils_common.h
Add `ALIGN_UP` and `ALIGN_DOWN` macros and remove `align_size()`. Replace `align_size()` with `ALIGN_UP()`.
> Add ALIGN_UP and ALIGN_DOWN macros and remove align_size()

- .github/workflows/benchmarks.yml
- CMakeLists.txt
- README.md
- benchmark/CMakeLists.txt
- benchmark/multithread.cpp
- benchmark/multithread.hpp
It's not possible to use ubench for MT benchmarks because we want only to measure the workload and not thread creation time, etc. This means that we have to write out our own measurement code and use it within each worker thread. We also have to make sure that all threads start running at the same time (hence use of syncthreads()).
> Add MT benchmarks

- src/base_alloc/base_alloc_global.c
- src/base_alloc/base_alloc_global.h
- src/base_alloc/base_alloc_linux.c
- src/libumf_windows.c
The global base allocator should be destroyed in the library destructor in order to avoid use-after-free.
> Destroy global base allocator in the library destructor

- .github/workflows/basic.yml
- .github/workflows/pr_push.yml
- CMakeLists.txt
- README.md
- examples/CMakeLists.txt
- examples/README.md
- examples/basic/basic.c
- scripts/docs_config/conf.py
- scripts/docs_config/example-usage.rst
- scripts/docs_config/glossary.rst
- scripts/docs_config/index.rst
- test/test_make_install.txt
- test/test_make_uninstall.txt
- third_party/requirements.txt
Add an example with allocating memory with the usage of OS Memory Provider
and Scalable Pool.
[preview of docs](https://patkamin.github.io/unified-memory-framework/example-usage.html)
TODO:
> Basic example with documentation

- include/umf/providers/provider_os_memory.h
- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- test/provider_os_memory.cpp
> Add documentation to OS provider

- src/libumf_linux.c
- src/provider/provider_tracking.c
Make sure TRACKER is not used after being destroyed.
Also add checks to umfMemoryTrackerGetPool()
to detect if TRACKER or its map is not initialized.
> Make sure TRACKER is not used after being destroyed

- src/base_alloc/base_alloc_global.c
- src/base_alloc/base_alloc_global.h
- src/memory_pool_default.c
- src/memory_pool_internal.h
- src/memory_pool_tracking.c
- src/memory_provider.c
- src/memory_target.c
- src/memory_target.h
- src/memory_targets/memory_target_numa.c
- src/memspace.c
- src/memspace_internal.h
- src/memspaces/memspace_numa.c
- src/pool/pool_jemalloc.c
- src/pool/pool_scalable.c
- src/provider/provider_os_memory.c
- test/CMakeLists.txt
- test/common/pool.hpp
- test/common/provider.hpp
- test/poolFixtures.hpp
- test/pools/pool_base_alloc.cpp
The `umf_ba_global_free` requires size but this should not be a problem - I believe we know size of each allocation in our codebase currently.
> Add abstraction on top of ba_alloc  which supports arbitrary size allocations

- src/provider/provider_tracking.c
Replace linear base allocator with the fixed-size in trackingInitialize() and trackingFinalize().
> Replace linear base allocator with the global one in tracking provider

- .github/workflows/pr_push.yml
- .github/workflows/proxy_lib.yml
- src/CMakeLists.txt
- src/base_alloc/base_alloc.c
- src/base_alloc/base_alloc_linear.c
- src/base_alloc/base_alloc_linear.h
- src/provider/provider_tracking.c
- src/proxy_lib/CMakeLists.txt
- src/proxy_lib/proxy_lib.c
- src/proxy_lib/proxy_lib.def
- src/proxy_lib/proxy_lib.h
- src/proxy_lib/proxy_lib.map
- src/proxy_lib/proxy_lib_linux.c
- src/proxy_lib/proxy_lib_windows.c
- src/utils/utils_common.h
- test/test_base_alloc_linear.cpp
- test/test_make_install.txt
Ref: https://github.com/oneapi-src/unified-memory-framework/issues/240
> Add proxy library (for Linux only now)

- src/base_alloc/base_alloc_linear.c
- src/base_alloc/base_alloc_linear.h
- src/proxy_lib/proxy_lib.c
- src/utils/utils_common.h
- test/test_base_alloc_linear.cpp
Implement and use `umf_ba_linear_free()` in the proxy library.
`umf_ba_linear_free()` really frees memory only if all allocations from an inactive pool were freed.
> Implement and use umf_ba_linear_free() in the proxy library

- src/base_alloc/base_alloc_linear.c
This assert fails sporadically on Windows only.
It is safe to comment it out temporarily,
because the linear base allocator is used
in the proxy library only but `umf_ba_linear_destroy()`
is skipped, so this code is never run in real life.
Ref: #260
> Skip temporarily the assert in umf_ba_linear_destroy()

- .github/workflows/proxy_lib.yml
Enable pool tracking in the tests of the proxy library: UMF_ENABLE_POOL_TRACKING=ON
> Enable pool tracking in the tests of the proxy library

- .github/docker/README.md
- .github/docker/ubuntu-20.04.Dockerfile
- .github/docker/ubuntu-22.04.Dockerfile
- .github/workflows/trivy.yml
- .trivyignore
// tested on my fork: https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/7886306110/job/21519277801
> [CI] Add first dockers and trivy workflow

- src/pool/pool_scalable.c
The handle received from dlopen() was never closed - this PR fixes that. This is also one of the problems reported by the Coverity (#437908)
> close tbb handle on scalable pool finalize

- src/base_alloc/base_alloc_global.c
- src/base_alloc/base_alloc_global.h
- src/critnib/critnib.c
- src/memory_pool_default.c
- src/memory_pool_tracking.c
- src/memory_provider.c
- src/memory_target.c
- src/memory_targets/memory_target_numa.c
- src/memspace.c
- src/memspaces/memspace_host_all.c
- src/memspaces/memspace_numa.c
- src/pool/pool_jemalloc.c
- src/pool/pool_scalable.c
- src/provider/provider_os_memory.c
- src/provider/provider_tracking.c
- test/pools/pool_base_alloc.cpp
Also, implement malloc_usable_size and aligned_alloc for global
base alloc.
> Global base alloc free function now does not require size param

- src/base_alloc/base_alloc_global.c
This PR slightly simplifies umf_ba_global_alloc/free and fixes coverity errors #436585 and #436586
> refactor ba_global_alloc and fix coverity issues

- .github/workflows/basic.yml
- .github/workflows/benchmarks.yml
- .github/workflows/codeql.yml
- .github/workflows/gpu.yml
- .github/workflows/nightly.yml
- .github/workflows/pr_push.yml
- .github/workflows/proxy_lib.yml
- .github/workflows/sanitizers.yml
- CMakeLists.txt
- README.md
- benchmark/CMakeLists.txt
- include/umf/providers/provider_level_zero.h
- src/CMakeLists.txt
- src/libumf.map
- src/pool/pool_scalable.c
- src/provider/provider_level_zero.c
- test/CMakeLists.txt
- test/providers/provider_level_zero.cpp
- test/test_make_install.txt
This PR adds a Level Zero memory provider that supports #225 enhancement. TODO:
Please note that shared memory would be supported in separate PR
> add Level Zero memory provider

- .github/workflows/pr_push.yml
- include/umf/providers/provider_level_zero.h
Build docs (without pushing them to GH pages) on PR to avoid CI failures on the main.
Requires #287 (already merged @ldorau)
> build-only docs w/o deploy on pr push

- README.md
The current badge reflects the status of the Coverity report and it is green even if the Coverity build fails.
The Coverity build fails and nobody knows about it, becase there is no badge that reflects it.
So let's add a badge for the Coverity build.
> Add badge for the Coverity build

- src/cpp_helpers.hpp
436582 [Uninitialized scalar variable](https://scan3.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_UNINIT)
436581 [Uninitialized scalar variable](https://scan3.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_UNINIT)
> Fix: uninitialized scalar variable 'ops'

- test/memspaces/memspace_host_all.cpp
I removed the check that caused a sporadic test failure. 
I think we cannot guarantee in the test that all nodes will be touched because some other processes on the system might consume all memory from a particular NUMA node and as a result test is not getting memory allocated from that NUMA node.
> Fix sporadic issue in memspaceHostAllProviderTest.memoryPolicyOOM test

- benchmark/CMakeLists.txt
Fixes: https://github.com/oneapi-src/unified-memory-framework/issues/301
> Fix multithreaded bench compilation on windows

- .github/workflows/nightly.yml
- CMakeLists.txt
- README.md
- src/base_alloc/base_alloc.c
- src/pool/pool_disjoint.cpp
- src/pool/pool_jemalloc.c
- src/utils/CMakeLists.txt
- src/utils/utils_sanitizers.h
- test/common/pool.hpp
- test/poolFixtures.hpp
- test/supp/umf_test-jemalloc_pool.supp
Closes https://github.com/oneapi-src/unified-memory-framework/issues/217
TBB pool is not annotated because tbb keeps metadata inline and hence we cannot mark the memory as undefined/unaccessible on free.
Ref: https://valgrind.org/docs/manual/valgrind_manual.pdf
> Add memcheck and asan annotations

- test/CMakeLists.txt
- test/memspaces/memspace_host_all.cpp
- test/supp/umf_test-memspace_host_all.supp
Adjust alloc size to 4MB. Add an access to each allocation so that pages are actually allocated on the selected NUMA nodes.
~~Fixes: https://github.com/oneapi-src/unified-memory-framework/issues/285~~
This also fixes the nightly workflow fails here:  https://github.com/oneapi-src/unified-memory-framework/actions/runs/8148821384.
Nightly workflow run with these changes on my fork: https://github.com/kswiecicki/unified-memory-framework/actions/runs/8188227540.
> Fix OOM test for HOST ALL memspace

- test/common/base.hpp
CID: 436576 
https://scan3.scan.coverity.com/#/project-view/65391/15141?selectedIssue=436576
> Fix: Use move instead of copy for args

- .github/workflows/pr_push.yml
- .github/workflows/qemu.yml
- scripts/qemu/run-build.sh
Qemu config specifies 3 NUMA nodes and is based on: https://github.com/open-mpi/hwloc/wiki/Simulating-complex-memory-with-Qemu
> Add simple qemu run to CI

- .github/workflows/basic.yml
- .github/workflows/benchmarks.yml
- benchmark/CMakeLists.txt
- benchmark/multithread.cpp
- benchmark/ubench.c
Unify benchmarks' CI workflows for Linux and Windows.
Use ctest to run benchmarks.
A benchmark passes if it prints "PASSED" in the output,
because ubench of scalable pool fails if the confidence interval
exceeds maximum permitted 2.5%.
Fixes: #301
> Unify benchmarks' CI workflows for Linux and Windows

- src/pool/CMakeLists.txt
- test/CMakeLists.txt
Do not link directly with libc.
It was used to force using malloc from glibc.
We do not need it any more, because we use our own base allocator now.
> Do not link directly with libc

- src/provider/provider_os_memory.c
Replace hwloc_bitmap_list_asprintf() with hwloc_bitmap_list_snprintf()
`hwloc_bitmap_list_asprintf()` requires calling `free()` from stdlib what we cannot do.
> Replace hwloc_bitmap_list_asprintf() with hwloc_bitmap_list_snprintf()

- include/umf/memory_provider_ops.h
- src/cpp_helpers.hpp
- src/memory_provider.c
- src/provider/provider_level_zero.c
- src/provider/provider_os_memory.c
- src/provider/provider_tracking.c
- test/common/provider.hpp
- test/common/provider_null.c
- test/common/provider_trace.c
- test/memoryProviderAPI.cpp
As we agreed on our sync, the memory provider ops structure is split into mandatory and optional fields. Mandatory fields should be always initialized with a pointer to the appropriate function. Optional fields can be NULL. If an optional field is NULL the UMF initializes it with a default implementation that returns `UMF_RESULT_ERROR_NOT_SUPPORTED` error code.
> Split memory provider ops to mandatory and optional fields

- src/base_alloc/base_alloc_global.c
Whenever allocation larger than the largest allocation class was requested base_alloc_global was calling ba_os_alloc and wasn't marking the memory in any way. This was problematic as address returned from ba_os_alloc could have been the same as an address used for other instance of umf_ba_pool_t. If that other instance had been destroyed the memory address would still be marked as inaccessible.
This fixes build on: https://github.com/oneapi-src/unified-memory-framework/pull/88
> Add missing annotations to base_alloc_global

- .github/workflows/gpu.yml
Using new runners require updated labels
// previe of the execution: https://github.com/oneapi-src/unified-memory-framework/actions/runs/8251864728/job/22597511622#step:1:2
> [CI] Update runner's label for GPU workflow

- src/proxy_lib/proxy_lib.c
Add missing initialization of the linear base allocator.
> Fix ba_leak_free and ba_leak_pool_contains_pointer in proxy library

- src/base_alloc/base_alloc.c
- src/base_alloc/base_alloc_linear.c
- src/critnib/critnib.c
- src/memory_pool.c
- src/memory_provider.c
- src/provider/provider_tracking.c
- src/utils/CMakeLists.txt
- src/utils/utils_assert.h
- src/utils/utils_common.c
- src/utils/utils_common.h
Move functions from `utils_common.h` to `utils_common.c` and assert-related stuff to `utils_assert.h`.
This change is required to enable the proxy library on Windows - it needs some macros from `utils_common.h`,
but the `stdlib.h` cannot be included on Windows due to "_inconsistent DLL linkage_".
> Move functions from utils_common.h to utils_common.c

- src/critnib/critnib.c
To avoid wasting memory. This will improve memory utilization especially for IPC-related changes where each memory provider can have it's own critnib instance for caching handles.
> Use global base alloc in critnib

- CMakeLists.txt
- examples/basic/basic.c
- src/utils/utils_common.h
- src/utils/utils_posix_common.c
- src/utils/utils_windows_common.c
This commit introduces the _CRT_SECURE_NO_WARNINGS definition and removes the usage of strncpy_s from UMF to demonstrate that change works correctly.
The rationale for this change can be found in this issue:
Closes: oneapi-src/unified-memory-framework#317
> add _CRT_SECURE_NO_WARNINGS definition

- .github/workflows/pr_push.yml
- .github/workflows/valgrind.yml
- test/test_valgrind.sh
1. Make valgrind CI job a per-PR build.
2. Temporarily skip disjointPool tests failing under valgrind:
- pow2AlignedAlloc
- multiThreadedpow2AlignedAlloc
3. Skip tests incompatible with valgrind
The https://github.com/oneapi-src/unified-memory-framework/pull/343 PR is included in this PR.
Ref: #338
> Make valgrind CI job a per-PR build

- src/provider/provider_os_memory.c
> Remove disabling the C4996 warning on Windows

- src/base_alloc/base_alloc_global.c
Print size of the exceeding allocation in the debug message
> Print size of the exceeding allocation in the debug message

- CMakeLists.txt
Check if CMAKE_BUILD_TYPE is correctly set
> Check if CMAKE_BUILD_TYPE is correctly set

- src/utils/utils_common.c
- src/utils/utils_common.h
- src/utils/utils_log.c
- src/utils/utils_posix_common.c
- src/utils/utils_windows_common.c
- test/utils/utils_log.cpp
Commit 683a26e (add _CRT_SECURE_NO_WARNINGS definition, 2024-03-13) removed need to use not standard, secure implementations of some CRT functions on windows. This allows use getenv on all supported OSes what simplifies getting and parsing environment variables.
ref: oneapi-src/unified-memory-framework#317
> Simplify getenv implementation

- src/utils/utils_log.c
- test/utils/utils_log.cpp
remove usage of fopen_s and fix error message in the logger.
check commit descriptions for details.
> remove fopen_s and fix error in logger

- include/umf/memory_pool.h
- include/umf/pools/pool_disjoint.h
- include/umf/providers/provider_level_zero.h
- include/umf/providers/provider_os_memory.h
- scripts/docs_config/api.rst
- scripts/docs_config/conf.py
Add pools, providers, and memspaces to the web docs + small fixes.
preview: https://bratpiorka.github.io/unified-memory-framework/api.html
> Add pools, providers and memspaces to the web docs

- .github/workflows/coverity.yml
Missing 'schedule' event caused lack of pushing to Coverity server when runned as a planned job.
> Fix condition to make scheduled Coverity work as planned

- src/base_alloc/base_alloc.c
The annotate size should equal to metadata size
(size of umf_ba_chunk_t), not pointer size.
> Fix CID 438800:  Code maintainability issues

- test/utils/utils_log.cpp
helper_log_init sets global "const char *" variable. if we exit scope when this global variable is set to ptr from std::string::c_str method, this ptr is invalid (std::string object is freed), and coverity do not like this.
> fix coverity issue in logger tests.

- CMakeLists.txt
FORCE make it always come back to the default value. In our use case it's only needed to set the value if empty or missing.
> Don't force UMF_PROXY_LIB_BASED_ON_POOL

- .github/docker/README.md
- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
3 minor updates around docs.
// Preview for the first commit:
// https://github.com/lukaszstolarczuk/unified-memory-framework/tree/minor-docs-updates?tab=readme-ov-file#requirements-2
> Minor docs updates

- src/base_alloc/base_alloc_global.c
Make `umf_ba_global_alloc(0)` always return NULL, because it makes no sense to allocate a chunk of memory for size == 0.
Ref: #371
> Make umf_ba_global_alloc(0) always return NULL

- CMakeLists.txt
Add `PROPERTY STRINGS` for `UMF_PROXY_LIB_BASED_ON_POOL` variable
> Add PROPERTY STRINGS for UMF_PROXY_LIB_BASED_ON_POOL variable

- src/base_alloc/base_alloc_linear.c
- test/test_base_alloc_linear.cpp
**Fix: make `umf_ba_linear_alloc(0)` always return `NULL`**
`umf_ba_linear_alloc(0)` didn't return NULL and
`umf_ba_linear_free(umf_ba_linear_alloc(0))` always failed,
because `pool_contains_ptr(umf_ba_linear_alloc(0))` always
returned false, since `umf_ba_linear_alloc(0)` pointed
at the very end of the pool (`ptr == (char *)pool + pool_size`).
Fixes: #260
**Revert "Skip temporarily the assert in umf_ba_linear_destroy()"**
This reverts commit 66ac900d7d08832a57353a7cb650d6bfaa0b9068.
> Fix: make umf_ba_linear_alloc(0) always return NULL

- src/base_alloc/base_alloc_global.c
Memory Tracker allocates a lot of critnib nodes of size 152 bytes.
Make a separate allocation class for them, because each such allocation
causes an allocation of 4kB page now and a lot of the following messages:
```
base_alloc: allocation size (152) larger than the biggest allocation class. Falling back to OS memory allocation.
```
> Add allocation class for a critnib node of size 152 bytes

- .github/workflows/scorecard.yml
It looks like they changed something in the key generation/signing/whatever.
Bumping the version of the scorecard's action fixed the issue, we observed on some of the recent builds.
// Before:
https://github.com/oneapi-src/unified-memory-framework/actions/runs/8378598819/job/22944503805#step:4:1124
// After:
Verified on my fork's main: https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/8379660048/job/22947119974#step:4:1295
> [CI] Bump actions' versions in scorecard workflow

- .github/workflows/basic.yml
- CMakeLists.txt
- examples/CMakeLists.txt
- test/test_installation.py
Examples are installed in system as a documentation, hence only the source files are installed, not binaries... so we can install examples all the time, not under an `if`.
A minor cleanup in the installation area of CMake is done as well (in a sep. commit).
> Always install examples

- CMakeLists.txt
Custom commands for clang/cmake were added, even if the tools were not found. Similarly convienence command (to run both tools at once) were printing issue if one of the tools were not available.
> [CMake] Add clang/cmake formatting commands only if tools are available

- .github/workflows/sanitizers.yml
This reverts commit ca322eb1ddb6d18f83e51719cdf300503ab9f974.
Issue in GHA images was resolved, we can revert the temporary WA.
> Revert "Fix ubuntu-22.04 runner issue"

- .github/docker/ubuntu-20.04.Dockerfile
- .github/docker/ubuntu-22.04.Dockerfile
- .github/workflows/trivy.yml
- .trivyignore
'Least Privilege User' rule is really important and we should not skip it by default.
> Use non-root user in dockers by default

- src/CMakeLists.txt
- src/pool/CMakeLists.txt
- src/utils/CMakeLists.txt
- test/CMakeLists.txt
- test/memspaces/memspace_highest_capacity.cpp
- test/test_installation.py
So that users of umf pools (which are static libraries) do not have to link with umf_utils themselves.
It's not possible to link static libraries to other static libraries.
> Make umf_utils an interface library

- src/base_alloc/base_alloc_global.c
this messes up match files in UR. This should only be printed if requested (using logger).
> Do not print anything if allocation size results in os allocation

- .github/workflows/qemu.yml
- scripts/qemu/run-build.sh
- src/memory_targets/memory_target_numa.c
- src/memory_targets/memory_target_numa.h
- test/common/numa_helpers.h
- test/memspaces/memspace_highest_capacity.cpp
- test/memspaces/memspace_host_all.cpp
- test/provider_os_memory_multiple_numa_nodes.cpp
The integration was not correct - umfMemoryProviderCreateFromMemspace was passing nodemask with all bits set to OS provider (with MODE_BIND) which resulted in memory being allocated from the arbitrary node. This wasn't caught by the test due to wrong way of checking allocation location.
Fix this, by changing the implementation of numa_memory_target to only pass a single node to OS provider for now. This should be changed once we have implemented memspace policies and/or extend OS provider to possibly support setting priority for nodes from which we want to allocate.
> Fix highest capacity memspace with OS provider integration.

- .github/workflows/basic.yml
- .github/workflows/benchmarks.yml
- CMakeLists.txt
- benchmark/CMakeLists.txt
- test/test_installation.py
Do not rely on the `CMAKE_BUILD_TYPE` configuration variable in Windows builds. This variable is ignored by `MSVC`, the build type is determined during the build time based on the `--config` parameter.
There seems to be no way for disabling the proxy library build based on the used config, so this change provides just notification messages on all Windows builds and builds proxy library always.
Fixes: #362
> Disable CMake build type checks on Windows

- cmake/cmake_uninstall.cmake.in
On Windows, the 'uninstall' target failed randomly. The CMake command used for deleting files, 'cmake -E remove' seems to be not reliable. Changing the tool used for files deletion to 'rm'.
> Fix uninstallation random failures on Windows

- .github/scripts/get_system_info.sh
- .github/workflows/gpu.yml
Import get_system_info.sh from [UR repo](https://github.com/oneapi-src/unified-runtime/blob/main/.github/scripts/get_system_info.sh), adapt it for UMF, and use it in the only HW-related workflow we have - GPU.
> Add get_system_info script

- src/CMakeLists.txt
- src/pool/CMakeLists.txt
They are only intended to be used by umf itself. Making them public makes them visible to the users of umf which is not desired.
> Make compile definitions for libumf and pool private

- third_party/requirements.txt
Current version of pygments is affected by some vulnerabilities - bump it to the least unaffected version.
// preview of built docs: https://lukaszstolarczuk.github.io/unified-memory-framework/
> Bump pygments version

- .cmake-format
- test/CMakeLists.txt
Fixes: #399
This PR disables the two tests which use proxy lib when ctest is run for a Debug config on Windows:
```
ctest -C Debug
```
> Disable proxy lib tests on Windows Debug

- test/supp/helgrind-umf_test-disjointPool.supp
- test/test_valgrind.sh
Helgrind is complaining:
"pthread_mutex_lock with a pthread_rwlock_t* argument"
The call to pthread_mutex_lock is coming from c++ standard lib so the only thing we can do is to suppress it.
> Add suppresion file for helgrind for disjointPool test

- src/pool/pool_disjoint.cpp
Catch any possible errors from logger in Disjoint Pool.
This is the fix for the Coverity issue https://scan3.scan.coverity.com/#/project-view/65229/15141?selectedIssue=449677
Coverity says the logger may use a mocked-up version of fputs from the Google test (/test/utils/utils_log.cpp), which can throw errors.
> catch any possible errors from logger in Disjoint Pool

- test/supp/helgrind-umf_test-disjointPool.supp
- test/test_valgrind.sh
1) Add more suppressions for helgrind for disjointPool test
This is a continuation of #405.
This patch adds missing suppressions.
Ref: #405
Fixes: #338
2) Revert "Temporarily skip disjointPool tests failing under valgrind"
This reverts commit 2648539890172e26648d573d615acc7d800741f6.
> Add more suppresions for helgrind for disjoint pool test

- src/base_alloc/base_alloc.c
- src/base_alloc/base_alloc_linear.c
This assert would be triggered every time a memory pool or memory provider is leaked. Assert should not be used to verify the correctness of a user code but only to make sure the state of UMF is correct.  Also, in certain cases, leaking a pool/provider might be done on purpose.
> Remove assert from umf_ba_destroy

- src/utils/utils_concurrency.h
- src/utils/utils_sanitizers.h
This PR fixes helgrind and drd issues in critnib data structure found in PR #88.
> Add helgrind and drd annotations to critnib data strcture

- test/poolFixtures.hpp
Fix poolFixtures - `malloc(0)` can be `NULL`.
> Fix poolFixtures - malloc(0) can be NULL

- .github/workflows/pr_push.yml
- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- scripts/generate_docs.py
- test/test_installation.py
- third_party/requirements.txt
- Add `black` formatter support (via CMake custom commands)
- New CI check enabled
- Apply formatting on python source files
- Add a minor fixes in clang/cmake formatting commands
> Add black formatter for Python

- .cmake-format
- README.md
- include/umf/proxy_lib_new_delete.h
- src/proxy_lib/proxy_lib.c
- src/proxy_lib/proxy_lib.def
- test/CMakeLists.txt
- test/memoryPoolAPI.cpp
- test/test_proxy_lib.cpp
1) Add `_aligned_malloc()` and `_aligned_free()` to Windows proxy library.
`_aligned_malloc()` is a Windows variant of Linux `aligned_alloc()`
2) Add proxy_lib_new_delete.h
This header provides convenient overrides for the new and delete
operations in C++. It should be included in only one source file.
See: https://github.com/microsoft/mimalloc/tree/8f7d1e9a41bb0182166aac6a8d4d8b00f60ed032?tab=readme-ov-file#override_on_windows
Fixes: #350
3) Revert "Disable proxy lib tests on Windows Debug"
This reverts commit 92fa419d007a29c308739ffc7d8f3a2b608058ea.
> Enable tests of proxy library on Windows Debug

- third_party/requirements.txt
Bump `black` formatter version in our python's `requirements.txt` to omit the vulnerability PYSEC-2024-48.
> Bump black version

- test/utils/utils_log.cpp
Do not use c_str() beyond its scope.
It fixes the Coverity issue [#449676](https://scan3.scan.coverity.com/#/project-view/66197/15141?selectedIssue=449676)
> Do not use c_str() beyond its scope

- src/provider/provider_os_memory.c
This structure was duplicate of the umf_os_memory_provider_params_t structure, which was defined in public header file.
> remove umf_os_memory_provider_config_t struct from os provider

- scripts/docs_config/api.rst
- scripts/docs_config/introduction.rst
Create documentation for IPC API.
Fixes referencing between documents.
Ref. #404
> Add documentation for IPC API

- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- src/provider/provider_os_memory_linux.c
- src/provider/provider_os_memory_windows.c
Make `os_translate_mem_protection_flags`, `os_translate_flags` and `os_translate_mem_protection_one_flag` return umf_result_t.
> Make os_translate_mem_protection_flags return umf_result_t

- src/provider/provider_os_memory.c
Make `translate_numa_mode ()` return `umf_result_t`.
> Make translate_numa_mode return umf_result_t

- include/umf/memory_provider.h
- include/umf/memory_provider_ops.h
- src/ipc.c
- src/memory_provider.c
- src/provider/provider_level_zero.c
- src/provider/provider_tracking.c
- test/common/provider.hpp
- test/common/provider_null.c
- test/common/provider_trace.c
- test/ipcAPI.cpp
Add size param to the close_ipc_handle API
It is needed by https://github.com/oneapi-src/unified-memory-framework/pull/429
Ref: #429
> Add size param to the close_ipc_handle API

- .github/workflows/trivy.yml
Add printing trivy ignore and report in CI. Right now there's no easy way to look for the report's content.
// Preview: https://github.com/oneapi-src/unified-memory-framework/actions/runs/8721774953/job/23926226642
> [CI] Print trivy report in CI

- .github/workflows/pr_push.yml
Running tests in the Fast builds makes them at maximum 5 seconds longer, but it can prevent from starting the huge matrix of basic builds if any of tests fails.
> Run tests in the Fast builds

- src/provider/provider_tracking.c
Fix error message in `umfMemoryTrackerRemove()`
> Fix error message in umfMemoryTrackerRemove

- .github/scripts/get_system_info.sh
- .github/workflows/multi_numa.yml
- .github/workflows/pr_push.yml
- .github/workflows/qemu.yml
- scripts/qemu/run-build.sh
- src/provider/provider_os_memory.c
- test/common/numa_helpers.h
- test/provider_os_memory_multiple_numa_nodes.cpp
Continuation of https://github.com/oneapi-src/unified-memory-framework/pull/241.
- Rebased on the latest main
- Added multi_numa workflow
Ref: https://github.com/oneapi-src/unified-memory-framework/issues/242
> Add bind modes tests and run on multi-numa machine

- src/ipc.c
- src/ipc_internal.h
- src/provider/provider_tracking.c
- src/provider/provider_tracking.h
- test/memoryPoolAPI.cpp
The `umfMemoryTrackerGetPool` function has an issue in the implementation. It incorrectly returns a pool when `ptr + range_size` is passed as an argument. The test is added to validate it.
this PR refactored code and implemented the `umfMemoryTrackerGetPool` function on top of the `umfMemoryTrackerGetAllocInfo` function.
> Fix umfMemoryTrackerGetPool function and minor refactoring

- test/provider_os_memory_multiple_numa_nodes.cpp
- test/test_valgrind.sh
Clean up multi numa tests up a little, move "free" function up in the code, where possible, and use `EXPECT_` rather than `ASSERT_` to allow proper freeing.
While these tests seem clean from any valgrind issues now, they still are incompatibile with valgrind, hence I've left the gtest filters (but I've set the more specific ones).
Closes: #461
> Fix valgrind multi numa tests

- README.md
- benchmark/ubench.c
- include/umf/memory_provider_ops.h
- include/umf/providers/provider_os_memory.h
- src/CMakeLists.txt
- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- src/provider/provider_os_memory_linux.c
- src/provider/provider_os_memory_macosx.c
- src/provider/provider_os_memory_posix.c
- src/provider/provider_os_memory_windows.c
- src/proxy_lib/proxy_lib.c
- test/CMakeLists.txt
- test/ipc_os_prov.sh
- test/ipc_os_prov_consumer.c
- test/ipc_os_prov_producer.c
- test/test_valgrind.sh
1) Add support for `MAP_SHARED` to OS memory provider
2) Add support for `MAP_SHARED` to the proxy library
3) Implement the IPC hooks in OS memory provider
4) Add a basic shared memory (SHM) IPC test (`ipc_os_prov`) using only the OS memory provider API (not using the API from `ipc.h`).
> Add support for MAP_SHARED for Linux only

- src/pool/pool_proxy.c
Use base global allocator in the proxy pool.
> Use base global allocator in the proxy pool

- .github/workflows/basic.yml
- CMakeLists.txt
- cmake/helpers.cmake
- src/CMakeLists.txt
- src/proxy_lib/CMakeLists.txt
- test/test_installation.py
- third_party/requirements.txt
Use (and print) version set via `project` command, and additionally set "SRCVERSION" which will be more precise (based on git tags, if we have any).
Version change is actually a minor update, the more important part is the SOVERSION, which is now set for `libumf` and `libumf_proxy` shared libraries.
// After installation it looks like this, now:
> Set versions in CMake

- CMakeLists.txt
- examples/CMakeLists.txt
- examples/README.md
- examples/basic/ipc_shm_ipcapi.sh
- examples/basic/ipc_shm_ipcapi_consumer.c
- examples/basic/ipc_shm_ipcapi_producer.c
- src/ipc.c
Add IPC shared memory example using the ipc.h API.
> Add IPC shared memory example using the ipc.h API

- README.md
A small update in Disclaimer to assure our users we aim to make UMF stable sooner than later :)
// preview: https://github.com/lukaszstolarczuk/unified-memory-framework/tree/update-disclaimer?tab=readme-ov-file#introduction
> Update Disclaimer in README

- CMakeLists.txt
the name of helpers file is not very unique, it's safer to incldue this module via its full path.
Fixes https://github.com/oneapi-src/unified-memory-framework/issues/480
> [CMake] include helpers module via full path

- src/provider/provider_tracking.c
This assert would be triggered every time a memory is leaked by the application. Currently this happens in certain SYCL tests.
Ref: https://github.com/intel/llvm/actions/runs/9024914892/job/24800360426?pr=13343
> Remove assert from tracking provider

- src/pool/pool_proxy.c
Get size from tracking provider in `proxy_free()`.
Fixes: #475
> Get size from tracking provider in proxy_free()

- examples/basic/ipc_shm_ipcapi_producer.c
- test/ipc_os_prov_producer.c
Make sure the received string is NULL-terminated.
It fixes the Coverity issue no. 460614.
> Make sure the received string is NULL-terminated

- src/provider/provider_os_memory.c
- test/provider_os_memory.cpp
Do not ignore error in os free when size == 0.
This is a continuation of #482.
Ref: #482
Requires to be merged:
> Do not ignore error in os free when size == 0

- .github/workflows/codeql.yml
- .github/workflows/gpu.yml
- CMakeLists.txt
- README.md
- benchmark/CMakeLists.txt
- examples/CMakeLists.txt
- examples/basic/utils_level_zero.h
- src/CMakeLists.txt
- src/libumf.def.in
- src/pool/pool_scalable.c
- src/provider/provider_level_zero.c
- src/utils/CMakeLists.txt
- src/utils/utils_load_library.c
- src/utils/utils_load_library.h
- test/CMakeLists.txt
- test/providers/provider_level_zero.cpp
> Adapt project to work on windows with L0 and GPU

- benchmark/ubench.c
- src/memspace.c
- src/memspace_internal.h
- src/memspaces/memspace_numa.c
- src/provider/provider_level_zero.c
- src/proxy_lib/proxy_lib.c
- test/ipcAPI.cpp
- test/memspaces/memspace_helpers.hpp
- test/memspaces/memspace_host_all.cpp
- test/memspaces/memspace_numa.cpp
Replace `enum umf_result_t` with the `umf_result_t` type.
> Replace enum umf_result_t with the umf_result_t type

- cmake/FindLIBHWLOC.cmake
The FindLIBHWLOC.cmake module previously used the config.h header to retrieve the HWLOC library version. This header was not always present depending on how the library was distributed. To address this issue, we now rely on the HWLOC API version retrieved from hwloc.h, the main HWLOC library header.
> Retrieve HWLOC API version from hwloc.h header

- .github/workflows/sanitizers.yml
Use the latest version available in the GHA Win image.
> [CI] bump toolset version in sanitizer job on Win

- ChangeLog
- RELEASE_STEPS.md
... and an empty ChangeLog file.
This patch partially is based on #453 (it includes one extra place that should be updated for release)
Preview: https://github.com/lukaszstolarczuk/unified-memory-framework/blob/release-guide/RELEASE_STEPS.md
> [Doc] Add a release guide

- src/ipc.c
- src/ipc_internal.h
- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- src/provider/provider_os_memory_posix.c
- src/provider/provider_os_memory_windows.c
- src/utils/utils_common.h
- src/utils/utils_posix_common.c
- src/utils/utils_windows_common.c
Add pid to the umf_ipc_data_t structure
Add pid to the umf_ipc_data_t structure. It is required to implement IPC cache for the `umfOpenIPCHandle` function on the consumer side.
Also moved `getpid` implementation from the `provider_os_memory` to the `utils_common`.
> Add pid to the umf_ipc_data_t structure

- .github/workflows/qemu.yml
- scripts/qemu/configs/default.xml
- scripts/qemu/configs/sock_2_var1.xml
- scripts/qemu/configs/sock_2_var1_hmat.xml
- scripts/qemu/configs/sock_2_var2.xml
- scripts/qemu/configs/sock_2_var2_hmat.xml
- scripts/qemu/configs/sock_2_var3.xml
- scripts/qemu/configs/sock_2_var3_hmat.xml
- scripts/qemu/configs/sock_4_var1.xml
- scripts/qemu/configs/sock_4_var1_hmat.xml
- scripts/qemu/configs/sock_4_var2.xml
- scripts/qemu/configs/sock_4_var2_hmat.xml
> [CI] Add no-HMAT qemu configuration files

- .github/workflows/basic.yml
- .github/workflows/codeql.yml
- .github/workflows/gpu.yml
- .github/workflows/multi_numa.yml
- .github/workflows/nightly.yml
- .github/workflows/pr_push.yml
- .github/workflows/proxy_lib.yml
- .github/workflows/sanitizers.yml
- .github/workflows/valgrind.yml
- CMakeLists.txt
- README.md
- examples/CMakeLists.txt
- examples/basic/ipc_shm_ipcapi.sh
- scripts/qemu/run-build.sh
- test/CMakeLists.txt
- test/ipc_os_prov.sh
Add skipping of IPC test, which require a specific value of ptrace (set in the system). Enable it in the CI in all workflows.
Fixes: #488
> [Tests] skip test with improper ptrace value

- .github/workflows/basic.yml
- .github/workflows/sanitizers.yml
We currently have separate tasks for testing Intel icx/icpx compilers, which require Intel-supplied containers. This PR changes this and adds the icx/icpx tasks to the regular task set for Ubuntu.
fixes https://github.com/oneapi-src/unified-memory-framework/issues/259
> use oneAPI basekit instead dockers for icx/icpx tests

- .github/workflows/pr_push.yml
- include/umf/proxy_lib_new_delete.h
- src/utils/CMakeLists.txt
This PR is fixes https://github.com/oneapi-src/unified-memory-framework/pull/510 and https://github.com/oneapi-src/unified-memory-framework/issues/517
It is made of 3 commits:
* extend CI to catch issues
* fix #517 problem with linking 
* fix #510 compilation error related to semicolons
> test and fix UMF simplest build

- README.md
- include/umf/memspace.h
- scripts/qemu/run-build.sh
- src/CMakeLists.txt
- src/libumf.map
- src/libumf_linux.c
- src/memory_target.c
- src/memory_target.h
- src/memory_target_ops.h
- src/memory_targets/memory_target_numa.c
- src/memspace.c
- src/memspace_internal.h
- src/memspaces/memspace_highest_bandwidth.c
- test/CMakeLists.txt
- test/memspaces/memspace_helpers.hpp
- test/memspaces/memspace_highest_bandwidth.cpp
- test/memspaces/memspace_host_all.cpp
- test/memspaces/memspace_numa.cpp
- test/test_valgrind.sh
This memspace contains memory targets ordered by the highest bandwidth value (targets higher in the ordering are prioritised).
There is also an alternative way to assign nodes to this memspace by setting `UMF_MEMSPACE_HIGHEST_BANDWIDTH` environment variable.
> Add memspace "highest bandwidth"

- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- cmake/helpers.cmake
This pull request introduces support for gcov, a test coverage program that developers can use to assess the effectiveness of their test suites. The changes include:
- An additional CMake option USE_GCOV to enable gcov support, which is turned off by default.
- Modifications to CMakeLists.txt and cmake/helpers.cmake to ensure that the correct compile and link options are set when USE_GCOV is enabled. It also includes a check to ensure that gcov is only used with Debug builds.
- Updates to CONTRIBUTING.md to guide contributors on how to use gcov to check code coverage for new functionality, including a sample workflow for generating a coverage report.
- Documentation in README.md has been updated to include the new USE_GCOV option in the list of CMake options.
With these changes, …
> Enable gcov

- src/utils/utils_common.h
- src/utils/utils_log.c
- src/utils/utils_posix_common.c
- src/utils/utils_windows_common.c
- test/CMakeLists.txt
Use `syscall(SYS_gettid)` instead of `gettid()`,
because `gettid()` can be undefined in older OSes.
`gettid()` is undefined in CI OSes of OpenMP.
> Use utils_getpid() and utils_gettid() in util_log_internal()

- examples/CMakeLists.txt
- examples/basic/utils_level_zero.h
- src/provider/provider_level_zero.c
- test/CMakeLists.txt
- test/providers/provider_level_zero.cpp
ze_api.h should be always:
* included from the deps (build/_deps/level-zero-loader-***) for all internal code including tests
* included from the system paths in the examples
> cleanup include ze_api.h

- src/base_alloc/base_alloc.c
- src/base_alloc/base_alloc_linear.c
- src/ipc.c
- src/memory_pool.c
- src/provider/provider_tracking.c
- src/utils/utils_log.c
- src/utils/utils_log.h
- test/utils/utils_log.cpp
Added additional logs to the tracking provider.
> Added additional logs to the tracking provider.

- .github/workflows/sanitizers.yml
Apparently, the more generic version works properly (even though it uses precisely the same version, as before).
> [CI] Bump MSVC version to more generic one

- include/umf.h
- src/CMakeLists.txt
- src/base_alloc/base_alloc_global.c
- src/base_alloc/base_alloc_linux.c
- src/libumf.c
- src/libumf.def.in
- src/libumf.map
- src/libumf_linux.c
- src/libumf_windows.c
- src/memspaces/memspace_highest_bandwidth.c
- src/memspaces/memspace_highest_capacity.c
- src/memspaces/memspace_host_all.c
- src/provider/provider_level_zero.c
- src/topology.c
- test/CMakeLists.txt
- test/test_init_teardown.c
Add init/teardown functions: `umfInit()` and `umfTearDown()`:
- `umfInit()` increments the usage reference counter and initializes the global state of libumf if the usage reference counter was equal 0. Returns 0 on success or -1 on failure.
- `umfTearDown()` decrements the usage reference counter and destroys the global state of libumf if the usage reference counter is equal 0.
Fixes: #514
> Add init/teardown functions: umfInit() and umfTearDown()

- .github/dependabot.yml
"If you only require security updates and want to exclude version updates, you can set open-pull-requests-limit to 0 in order to prevent version updates for a given package-ecosystem"
Source:
https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
> Add dependabot .yml - dependencies version update

- README.md
- include/umf/memspace.h
- src/CMakeLists.txt
- src/libumf.c
- src/libumf.map
- src/memory_target.c
- src/memory_target.h
- src/memory_target_ops.h
- src/memory_targets/memory_target_numa.c
- src/memspace_internal.h
- src/memspaces/memspace_lowest_latency.c
- test/CMakeLists.txt
- test/memspaces/memspace_fixtures.hpp
- test/memspaces/memspace_helpers.hpp
- test/memspaces/memspace_highest_capacity.cpp
- test/memspaces/memspace_host_all.cpp
- test/memspaces/memspace_lowest_latency.cpp
- test/memspaces/memspace_numa.cpp
- test/test_valgrind.sh
This memspace is analogous to the 'highest bandwidth' memspace in its composition, but it focuses on the NUMA nodes with best latency.
Contains changes from https://github.com/oneapi-src/unified-memory-framework/pull/408.
> Add memspace "lowest latency"

- src/memory_targets/memory_target_numa.c
- src/provider/provider_os_memory.c
- test/memspaces/memspace_host_all.cpp
For the default CPU memspace (MemspaceHostAll) with all NUMA nodes, we should follow the default kernel behavior, and we shouldn't call any kind of mbind() that could negatively impact the performance
> Handle default kernel behavior for CPU access to all NUMA nodes

- .github/workflows/basic.yml
- .github/workflows/benchmarks.yml
- .github/workflows/pr_push.yml
Revert: Temporarily disable Windows 2022 Release CI builds
This PR reverts https://github.com/oneapi-src/unified-memory-framework/pull/535
Ref: #535
> Revert: Temporarily disable Windows 2022 Release CI builds

- test/CMakeLists.txt
Link the init_teardown test with libdl explicitly
for systems with glibc < 2.34.
The init_teardown test uses dlopen(), dlsym() and dlclose().
Fixes: #543
> Link the init_teardown test with libdl

- .github/workflows/pr_push.yml
Run the simplest CMake CI build also on Ubuntu 20.04
in order to test glibc < 2.34.
Ref: #543
> Run the simplest CMake CI build also on Ubuntu 20.04

- README.md
- src/proxy_lib/proxy_lib.c
Add support for the named shared memory to the proxy library. It adds the `UMF_PROXY="page.disposition=shared-shm"` environment variable for the `MAP_SHARED` visibility mode with the named shared memory using a generated SHM name.
> Add support for the named shared memory to the proxy library

- include/umf.h
- src/libumf.c
- src/libumf.def.in
- src/libumf.map
Add `umfGetCurrentVersion()` to UMF API that gets the current version of the UMF headers defined by `UMF_VERSION_CURRENT`.
> Add umfGetCurrentVersion() to UMF API

- src/utils/utils_log.c
- test/utils/utils_log.cpp
Print out the UMV version in `util_log_init()`.
> Print out the UMV version in util_log_init()

- src/utils/utils_log.c
- test/utils/utils_log.cpp
Add initial expected_message to the logger test.
Ref: #552
> Add initial expected_message to the logger test

- src/memory_targets/memory_target_numa.c
- src/memspaces/memspace_highest_bandwidth.c
- src/memspaces/memspace_lowest_latency.c
Add logs to `query_attribute_value()`.
> Add logs to query_attribute_value()

- include/umf/providers/provider_os_memory.h
- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- test/provider_os_memory.cpp
- test/provider_os_memory_multiple_numa_nodes.cpp
split mode splits each allocation based on user provided partitions,
across multiple numa nodes. If no partition defined then each
allocation is split evenly, across all numa available.
Signed-off-by: Łukasz Plewa <lukasz.plewa@intel.com>
> add umf split mode to os_memory_provider

- src/CMakeLists.txt
- src/utils/utils_log.c
Add `UMF_SRC_VERSION` to `UMF_PRIVATE_COMPILE_DEFINITIONS`.
Print UMF source version (`UMF_SRC_VERSION`) in `util_log_init()` if it is defined.
It looks like:
```
[PID:21521  TID:21521  INFO  UMF] util_log_init: Logger enabled (umf version: 0.9, src version: 0.1.0.git.d1e2930, level: DEBUG, flush: DEBUG, pid: yes, timestamp: no)
```
> Print UMF source version in util_log_init() if it is defined

- examples/CMakeLists.txt
When scalacble pool is disabled, set_test_properties will be called on non-existent test which causes an error.
Move set_property under appropriate if.
> Fix cmake for examples

- test/CMakeLists.txt
- test/common/ipc_common.c
- test/common/ipc_common.h
- test/ipc_os_prov_consumer.c
- test/ipc_os_prov_producer.c
Refactor ipc_os_prov_consumer.c and ipc_os_prov_producer.c.
Split the code into functions, move them to the common directory
and prepare them to be reused in a future similar tests.
> Refactor ipc_os_prov_consumer.c and ipc_os_prov_producer.c

- test/provider_os_memory_multiple_numa_nodes.cpp
Coverity fixes:
* avoid unnecessary copy of the numa_nodes vector
* use of const auto& in the for loop, as the argument is never modified
> Coverity fixes

- test/CMakeLists.txt
- test/common/ipc_common.c
- test/common/ipc_common.h
- test/common/ipc_os_prov_common.c
- test/common/ipc_os_prov_common.h
- test/ipc_os_prov_consumer.c
- test/ipc_os_prov_producer.c
Move `memcopy()` to a separate source file.
> Move memcopy() to a separate source file

- .github/workflows/basic.yml
- CMakeLists.txt
- README.md
- examples/CMakeLists.txt
- src/CMakeLists.txt
> Add static linking option

- .github/scripts/check_dll_flags.ps1
- .github/workflows/basic.yml
- .github/workflows/pr_push.yml
- cmake/helpers.cmake
Set /DEPENDENTLOADFLAG to 2000 (LOAD_LIBRARY_SAFE_CURRENT_DIRS) in Windows umf.dll builds (MSVC only). 
With this flag, loading a DLL for execution from the current directory is only allowed if it is under a directory in the Safe load list.
In addition, there is a new test written in Power Shell that uses dumpbin.exe to check that this flag is set correctly.
Detailed information about the flag can be found at: https://learn.microsoft.com/en-us/cpp/build/reference/dependentloadflag?view=msvc-170
and: https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexa
> load DLLs only from safe load list

- test/fuzz/CMakeLists.txt
- test/fuzz/umfFuzz.cpp
Fixes in fuzz test - details on commits messages.
> Fuzz test fixes

- src/umf_hwloc.h
UMF source code imports HWLOC headers that trigger unused parameter warnings, which are treated as errors. The UMF CI might not have caught this issue, but the UR CI did, possibly due to different HWLOC versions.
Logs: https://github.com/oneapi-src/unified-runtime/actions/runs/9701110619/job/26798893141?pr=1430
> Suppress unused param warning from hwloc.h

- .github/workflows/pr_push.yml
Example:
Source:
https://github.com/KFilipek/unified-memory-framework/actions/runs/9681607789/job/26712591718
> [CI] Add diff print to CMake style check

- cmake/helpers.cmake
- src/provider/provider_os_memory_posix.c
- src/provider/provider_tracking.c
- src/utils/utils_log.c
- test/CMakeLists.txt
Those flags provide extra warnings in case of discarding qualifiers or return values. This allows for the discovery of warnings/errors before they appear on UR CI (https://github.com/oneapi-src/unified-runtime/actions/runs/9712855198/job/26811966767?pr=1430).
> Add extra compilation flags

- .github/workflows/sanitizers.yml
Disable umf-provider_os_memory in sanitizers tests for now due to https://github.com/oneapi-src/unified-memory-framework/issues/581
> Disable umf-provider_os_memory in sanitizers tests

- src/utils/utils_windows_math.c
UR CI reports `C28251` warning in Windows header `intrin.h`.
Logs: https://github.com/intel/llvm/actions/runs/9781171173/job/27004776301?pr=13343.
> Suppress warning 28251 for intrin.h

- ChangeLog
- scripts/docs_config/conf.py
Drop the `-rc1` part and move to a final 0.1.0 release.
Once this PR is merged, the `v0.1.0` tag will be created.
> 0.1.0 release

- .github/workflows/pr_push.yml
- .github/workflows/qemu.yml
- scripts/qemu/run-build.sh
- scripts/qemu/run-tests.sh
- scripts/qemu/start_qemu.sh
In short this PR merges all qemu workflow in one. We can reuse the same image and build project only one time. 
We reduce Runner utilization from ~55min to 25 min (+ we gain time wasted for runner to pickup work and start, which is not counted)
As a downside we reduce parallelize - we had 11 -  5 min jobs  now we have a single 25 min long job. 
It should not be a problem, as we are blocked by runner availability, so qemu workflow should finish anyway before all other jobs. But to limit negative influence of this change, i changed qemu workflow dependency, to start it sooner, and do not block other workflows.
> optimize qemu workflow

- include/umf/ipc.h
- src/ipc.c
- src/libumf.def.in
- src/libumf.map
- test/ipcFixtures.hpp
The MPI team requested this API. It allows to get the size of the IPC handle created by a particular pool.
> Add umfPoolGetIPCHandleSize API

- .github/workflows/fast.yml
- .github/workflows/pr_push.yml
Run fast builds when Spellcheck and CodeStyle succeed.
> Run fast builds when Spellcheck and CodeStyle succeed

- include/umf/memory_pool.h
- include/umf/memory_pool_ops.h
- include/umf/mempolicy.h
- scripts/docs_config/examples.rst
- scripts/docs_config/introduction.rst
- src/ipc.c
- src/libumf.h
- src/provider/provider_os_memory.c
most of them found by `codespell` and `sphinxcontrib-spelling`; other by hand
> Fix misspells in the repo

- examples/basic/CMakeLists.txt
- examples/cmake/FindLIBHWLOC.cmake
- examples/cmake/FindLIBUMF.cmake
- examples/cmake/FindTBB.cmake
- examples/gpu_shared_memory/CMakeLists.txt
- examples/ipc_ipcapi/CMakeLists.txt
- examples/ipc_level_zero/CMakeLists.txt
- src/CMakeLists.txt
- test/CMakeLists.txt
- test/test_examples.sh
Add standalone tests of examples.
Fixes: #427
> Add standalone tests of examples

- scripts/docs_config/examples.rst
After recent changes in examples (https://github.com/oneapi-src/unified-memory-framework/pull/589) the links were broken.
// Preview: https://lukaszstolarczuk.github.io/unified-memory-framework/examples.html
> [docs] Update links to examples

- src/CMakeLists.txt
- src/proxy_lib/CMakeLists.txt
Define `UMF_SRC_VERSION` in the proxy library.
It enables printing out the source version in `util_log_init()`.
> Define UMF_SRC_VERSION in the proxy library

- src/utils/utils_concurrency.h
- src/utils/utils_windows_intrin.h
- src/utils/utils_windows_math.c
Disable warning 28251: Inconsistent annotation for `_BitScanForward` in `utils_concurrency.h`.
> Disable warning 28251: Inconsistent annotation for _BitScanForward

- .github/workflows/basic.yml
- .github/workflows/benchmarks.yml
- .github/workflows/codeql.yml
- .github/workflows/fast.yml
- .github/workflows/gpu.yml
- .github/workflows/proxy_lib.yml
- .github/workflows/sanitizers.yml
- test/CMakeLists.txt
- test/test_examples.sh
1) Set `CMAKE_INSTALL_PREFIX` in all CI builds.
2) Clean up setting and using of `env.BUILD_DIR`.
3) Do not run cmake inside ctest tests.
Ref: https://github.com/oneapi-src/unified-memory-framework/pull/599/files#r1670260245
> Do not run cmake inside ctest tests

- include/umf/pools/pool_jemalloc.h
- src/pool/pool_jemalloc.c
Add the `disable_provider_free ` parameter to pool jemalloc. It should be set to true if `umfMemoryProviderFree()` should never be called.
This option will be needed by the future memory providers that will not provide the free() op.
> Add disable_provider_free parameter to pool jemalloc

- src/libumf.rc.in
- src/proxy_lib/proxy_lib.rc.in
Fix the warnings:
```
umf\build\src\libumf.rc(12): warning RC4005: 'UMF_VERSION' : redefinition
umf\build\src\proxy_lib\proxy_lib.rc(12): warning RC4005: 'UMF_VERSION' : redefinition
```
> Fix warnings RC4005: 'UMF_VERSION' : redefinition

- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
Add lock for updating file size in OS memory provider, because `umfMemoryProviderAlloc()` has to be MT-safe.
> Add lock for updating file size in OS memory provider

- .github/workflows/sanitizers.yml
- src/base_alloc/base_alloc_global.c
- src/base_alloc/base_alloc_linux.c
- src/provider/provider_os_memory_posix.c
Fixes: https://github.com/oneapi-src/unified-memory-framework/issues/581
> Fix asan bug

- src/pool/pool_disjoint.cpp
ASan throws an error whenever the memory poison is called for the memory allocated on GPU:
```"AddressSanitizer: CHECK failed: asan_mapping.h:359 "((AddrIsInMem(p))) != (0)" (0x0, 0x0)".```
This commit disables poisoning by default and adds a new parameter to Disjoint Pool params struct that allows to enable the poisoning.
> Disable memory poisoning in DisjointPool by default

- src/pool/pool_disjoint.cpp
The poison memory macro definition is always defined, so an #ifdef check is insufficient.
> Fix disjoint pool memory poison macro

- include/umf/memspace.h
- include/umf/memtarget.h
- scripts/docs_config/api.rst
- src/libumf.def.in
- src/libumf.map
- src/memspace.c
- src/memtarget.c
- src/memtarget_ops.h
- src/memtargets/memtarget_numa.c
- test/CMakeLists.txt
- test/memspaces/memspace_numa.cpp
- test/memspaces/memtarget.cpp
> add Memtargetgettype

- cmake/helpers.cmake
> Remove werror compile option from UMF targets

- .github/workflows/basic.yml
- CMakeLists.txt
- examples/CMakeLists.txt
- src/CMakeLists.txt
- src/libumf.c
- test/CMakeLists.txt
> Add option to disable hwloc

- .github/workflows/basic.yml
- CMakeLists.txt
- test/CMakeLists.txt
> Add option to link statically with hwloc on linux

- CMakeLists.txt
- cmake/helpers.cmake
- src/CMakeLists.txt
- src/libumf.def.in
- src/libumf.map.in
to fix:
"ld.lld: error: version script assignment of 'UMF_1.0' to symbol
'umfLevelZeroMemoryProviderOps' failed: symbol not defined"
when using lld linker
> Avoid using non-existing symbols in .map

- CMakeLists.txt
> Allow completely disabling hwloc on windows

- src/provider/provider_os_memory.c
`size_fd` has to be read under a lock.
> Fix: size_fd has to be read under a lock

- CMakeLists.txt
- README.md
- add missing `UMF_DISABLE_HWLOC` in readme
- clean badges up
- fix misspell
> Minor updates in README

- CMakeLists.txt
Referring to an installed file using `CMAKE_SOURCE_DIR` only works when UMF is built and installed standalone, but not when it's included by other projects.
Only `LICENSE.TXT` and `licensing/third-party-programs.txt` still had these issue, while other files already used `PROJECT_SOURCE_DIR`.
> [CMake] Don't use CMAKE_SOURCE_DIR during install

- CMakeLists.txt
#656 commit: [CMake] Don't use CMAKE_SOURCE_DIR during install
> commits for 0.9x rc3

- CMakeLists.txt
Without explicitly disabling them and if a system where hwloc is being build has opencl/cuda/nvml installed those libraries will become hwloc dependencies which would force umf to link with them.
The problem manifested on a system where opencl was installed and umf compilation failed due to missing clGetDevices symbol.
> Disable opencl, cuda and nvml when configuring hwloc

- .github/workflows/bandit.yml
- .github/workflows/docs.yml
- .github/workflows/fast.yml
- .github/workflows/pr_push.yml
- .github/workflows/proxy_lib.yml
- .github/workflows/spellcheck.yml
- .github/workflows/trivy.yml
in some of the jobs, we enable intel-maintained, ephemeral runners.
> [CI] enable new runners for some of jobs

- .github/workflows/coverity.yml
Run Coverity only on upstream.
Forks do not know Username/Password.
> [CI] Run Coverity only on upstream

- examples/CMakeLists.txt
- examples/common/utils_examples.h
- examples/memspace/memspace_hmat.c
- examples/memspace/memspace_numa.c
- test/common/test_helpers.h
- test/memspaces/memspace_fixtures.hpp
- test/memspaces/memspace_numa.cpp
- test/provider_os_memory_multiple_numa_nodes.cpp
Checks with numa_available() whether NUMA is supported on the system, then runs tests requiring NUMA according to the result. 
- Adds GTEST_SKIP() or substitutes GTEST_FAIL() with GTEST_SKIP() if failure has been determined by the lack of NUMA support;
- removes UT_ASSERTs checking for NUMA if NUMA support has been checked in the test fixture;
- allows uninstantiated tests in /test/provider_os_memory_multiple_numa_nodes.cpp, which suppresses failures caused by GoogleTestVerification test suite - the potentially uninstantiated tests are never run but skipped by the fixture if NUMA is not supported
- a helper function get_available_numa_nodes() in /test/provider_os_memory_multiple_numa_nodes.cpp returns an empty vector in case of lacking NUMA support (which causes tests to be …
> Skip tests requiring NUMA if NUMA is not supported

- .github/workflows/basic.yml
- CMakeLists.txt
- src/CMakeLists.txt
A small fixes in CMake and CI around hwloc options.
> Minor fixes around hwloc in CMake and CI

- .github/workflows/qemu.yml
- scripts/qemu/parse_config.py
- scripts/qemu/qemu_config.py
- scripts/qemu/run-build.sh
- scripts/qemu/run-tests.sh
- scripts/qemu/start_qemu.sh
A little cleanup around QEMU job in CI. It contains a few commits, each can be reviewed separately. It's a small introduction to next changes in QEMU CI, I have in mind.
> Minor cleanup in QEMU CI

- include/umf/memtarget.h
- src/libumf.def.in
- src/libumf.map.in
- src/memspace.c
- src/memspace_internal.h
- src/memtarget.c
- src/memtarget_internal.h
- test/CMakeLists.txt
- test/memspaces/memtarget.cpp
~~depends on https://github.com/oneapi-src/unified-memory-framework/pull/631~~
> Memtarget capacity

- CONTRIBUTING.md
Add black installation details in CONTRIBUTING.md
as in README.md
Added information about `black` installation in CONTRIBUTING.md, as it is in README.md. A possible contributor (who could focus on CONTRIBUTING.md) might have problems with formatting, since targets `format-apply` and `format-check` are not built if `black` is not installed (issue based on a true story).
> docs: add details in CONTRIBUTING.md

- CMakeLists.txt
> Disable pciaccess library in hwloc

- CMakeLists.txt
- src/provider/provider_level_zero.c
Contains:
- https://github.com/oneapi-src/unified-memory-framework/pull/685
- https://github.com/oneapi-src/unified-memory-framework/pull/678
> Another fixes for rc4

- CMakeLists.txt
Around changes in #667, perhaps in merge conflict resolution, extra hwloc configure params were accidentally removed (ref. #660).
> [CMake] Fix hwloc configure params

- test/test_base_alloc.cpp
- test/test_base_alloc_linear.cpp
- test/test_proxy_lib.cpp
The PR is a part of a major fix: to substitute UT_ASSERTs with asserts provided by GTEST, in multiple files.
Ref. #569
> fix: substitute UT_ASSERTs with asserts from GTEST part 1

- CMakeLists.txt
- cmake/fix_coverity_issues.patch
fix coverity issues in hwloc - possible dereference of NULL pointers assigned to get_cpubind() and set_cpubind()
> fix coverity issues in hwloc

- CMakeLists.txt
- cmake/fix_coverity_issues.patch
> fixes for rc4

- .github/workflows/basic.yml
- CMakeLists.txt
- cmake/FindJEMALLOC.cmake
- cmake/FindLIBHWLOC.cmake
- cmake/FindTBB.cmake
- examples/cmake/FindLIBHWLOC.cmake
- examples/cmake/FindTBB.cmake
- src/CMakeLists.txt
If hwloc is got from vcpkg it is named "hwloc" while mingw version names it "libhwloc".
> set custom name for hwloc lib

- src/CMakeLists.txt
Turning UMF_BUILD_LEVEL_ZERO_PROVIDER on in UR
results in configuration errors as both projects try to fetch and build L0 loader.
> Add option to control fetching L0

- include/umf/providers/provider_level_zero.h
- src/provider/provider_level_zero.c
Extend L0 provider with:
- ability to make memory resident on devices
- ability to allocate memory exceeding maxMemAllocSize
to match L0 provider capabilities from UR.
> Extend L0 provider to match UR capabilities

- src/provider/provider_os_memory_linux.c
on SLES there is not SYS_memfd_secret defined, therefore it is safer to use direct number
> Fix compilation of syscall_memfd_secret for SLES

- src/provider/provider_level_zero.c
- test/providers/level_zero_helpers.cpp
- test/providers/provider_level_zero.cpp
and do not call zeDeviceGetProperties for HOST provider.
Also, add extra checks for parameters.
> L0 provider: do not accept device handle for HOST memory type

- test/memspaces/memspace_highest_capacity.cpp
- test/provider_os_memory_multiple_numa_nodes.cpp
Found on Ubuntu 23.10 on gcc 13.2.0:
warning: ‘nodeId’ may be used uninitialized [-Wmaybe-uninitialized]
Fix other places for unity, setting them to -1.
> tests: fix warning 'maybe-uninitialized'

- .github/workflows/proxy_lib.yml
Do not run benchmarks in the proxy_lib CI,
since it takes about 4 minutes to run
the umf-bench-ubench benchmark.
Benchmarks are run in a separate workflow.
See https://github.com/oneapi-src/unified-memory-framework/actions/runs/10696438586/job/29652522203 for an example.
Times of builds:
1) ProxyLib / Ubuntu (Release, gcc, g++, SCALABLE
2) ProxyLib / Ubuntu (Release, gcc, g++, JEMALLOC
3) ProxyLib / Ubuntu (Debug, gcc, g++, SCALABLE
4) ProxyLib / Ubuntu (Debug, gcc, g++, JEMALLOC
Before:
1) 11m 33s
2) 11m 5s
3) 6m 22s
4) 6m 47s
With this patch:
1) 2m 21s
2) 2m 22s
3) 1m 57s
4) 1m 57s
> Do not run benchmarks in the proxy_lib CI

- .github/workflows/basic.yml
- .github/workflows/sanitizers.yml
Run setvars.sh also before building for icpx compiler. It fixes the following warnings:
```
/usr/bin/ld: warning: libsvml.so, needed by ../lib/libumf.so.0.9.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libirng.so, needed by ../lib/libumf.so.0.9.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libimf.so, needed by ../lib/libumf.so.0.9.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libintlc.so.5, needed by ../lib/libumf.so.0.9.0, not found (try using -rpath or -rpath-link)
```
See the build: https://github.com/oneapi-src/unified-memory-framework/actions/runs/10700901541/job/29666095891#logs
> Run setvars.sh also before building for icpx compiler

- test/memspaces/memspace_fixtures.hpp
This file uses `std::find` and `std::any_of` which are part of the `<algorithm>` header, but it wasn't including it.
When building with gcc 14 this caused build issues such as:
```
memspace_fixtures.hpp:204:26: error: ‘any_of’ is not a member of ‘std’
```
With this patch adding the include building UMF with gcc 14 works fine.
> Fix includes in memspace test fixtures

- src/critnib/critnib.c
> Fix a typo in critnib.c

- CMakeLists.txt
Windows `cmd.exe` doesn't have a `true` command which causes the DPC++ build to fail, `(exit 0)` will do the same thing but it will work on both linux and windows.
This issue only shows up on Windows and not on a first build, since when building the first time the patch applies cleanly so the `||` branch is not taken, but then when rebuilding the patch doens't apply and the command errors out in the `||` branch.
> Fix hwloc patch application on windows

- src/provider/provider_os_memory_internal.h
- src/proxy_lib/proxy_lib.c
Remove definitions of `NAME_MAX` since it is defined in `<limits.h>`.
> Remove definitions of NAME_MAX

- src/ravl/ravl.c
Fix Coverity issues in RAVL tree:
- 468502 Dereference after null check
- 462949 Overflowed return value
> Fix Coverity issues in RAVL tree

- src/base_alloc/base_alloc_global.c
Remove the warning message of the base allocator.
This situation can happen often and it is nothing wrong, so this message just spams the debug output.
> Remove the warning message of the base allocator

- test/provider_os_memory.cpp
Refactor `providerCreateExt()`.
Ref: #664
> Refactor providerCreateExt()

- examples/gpu_shared_memory/CMakeLists.txt
- examples/ipc_level_zero/CMakeLists.txt
- src/CMakeLists.txt
Bump L0 loader version, to align with UR - it's the latest version. Also, update comments and cache variable type.
> Bump L0 loader

- src/ravl/ravl.c
Fix assert in `ravl_node_rank_difference_parent()`.
`ravl_node_rank()` do not have to be positive - it can return (-1), so the assert has to be corrected.
For example:
if `ravl_node_rank(p) = 0` and `ravl_node_rank(n) = -1`, then `rv = 1`.
Ref: #717
This patch is tested in #715
> Fix assert in ravl_node_rank_difference_parent()

- src/ipc.c
- test/CMakeLists.txt
- test/ipcFixtures.hpp
- test/provider_os_memory.cpp
- test/test_valgrind.sh
Minor refactoring of IPC. Enabled IPC tests for the OS provider.
> Refactor IPC tests and enable them for OS provider

- cmake/FindLIBHWLOC.cmake
When libhwloc is not found users are warned with this message `libhwloc NOT found (set CMAKE_PREFIX_PATH to point the location)`. This can be disabled with the flag `UMF_DISABLE_HWLOC` which they would need to look up in the project documentation, so just adding it to the warning message to skip that. The updated message is `libhwloc NOT found (set CMAKE_PREFIX_PATH to point the location) or disable with -DUMF_DISABLE_HWLOC=ON`
> Update CMake warning when libhwloc is not found to inform user about UMF_DISABLE_HWLOC flag

- ChangeLog
- scripts/docs_config/conf.py
Merge v0.9.0 tag (via v0.9.x branch) into main.
> Merge v0.9.0 to main

- CONTRIBUTING.md
As a first time contributor it took a bit of hunting to find out why the `format-check` and `format-apply` targets mentioned in the build docs were not working, a comment is hidden away in `CMakeLists.txt` saying that all 3 of the formatters (`clang-format`, `cmake-format` and `black` need to be installed before they are available. Updated build docs to try to make this a little more obvious.
> Update docs for using formatting targets to make it more obvious about helper format-check and format-apply targets

- .github/workflows/devdax.yml
- .github/workflows/pr_push.yml
- CMakeLists.txt
- README.md
- include/umf/providers/provider_devdax_memory.h
- scripts/docs_config/api.rst
- src/CMakeLists.txt
- src/provider/provider_devdax_memory.c
- src/provider/provider_devdax_memory_internal.h
- src/provider/provider_os_memory_internal.h
- src/provider/provider_os_memory_linux.c
- src/provider/provider_os_memory_macosx.c
- src/provider/provider_os_memory_posix.c
- src/provider/provider_os_memory_windows.c
- src/utils/utils_common.c
- src/utils/utils_common.h
- test/CMakeLists.txt
- test/common/ipc_common.c
- test/ipc_devdax_prov.sh
- test/ipc_devdax_prov_consumer.c
- test/ipc_devdax_prov_producer.c
- test/provider_devdax_memory.cpp
- test/test_valgrind.sh
> Add devdax memory provider

- src/utils/utils_common.h
Remove excessive definition of `NAME_MAX`.
> Remove excessive definition of NAME_MAX

- test/provider_os_memory_multiple_numa_nodes.cpp
Fix two testNuma tests:
- `checkModeInterleave` and
- `checkModeInterleaveCustomPartSize`
It fixes the Coverity issue no. 468463.
> Fix two testNuma tests

- benchmark/ubench.c
- src/provider/provider_level_zero.c
minor L0 provider improvements
- fix "unused symbol" warning in ubench
- define L0 prov functions as static
- improve error handling
> minor L0 provider improvements

- CMakeLists.txt
- README.md
- include/umf/providers/provider_file_memory.h
- scripts/docs_config/api.rst
- src/CMakeLists.txt
- src/provider/provider_file_memory.c
- src/provider/provider_file_memory_internal.h
- src/provider/provider_os_memory_internal.h
- src/provider/provider_os_memory_linux.c
- src/provider/provider_os_memory_macosx.c
- src/provider/provider_os_memory_posix.c
- src/provider/provider_os_memory_windows.c
- src/utils/utils_common.h
- test/CMakeLists.txt
- test/ipc_file_prov.sh
- test/ipc_file_prov_consumer.c
- test/ipc_file_prov_producer.c
- test/provider_devdax_memory.cpp
- test/provider_file_memory.cpp
- test/provider_os_memory.cpp
- test/test_valgrind.sh
> Add file memory provider

- .github/workflows/basic.yml
- include/umf/base.h
- scripts/docs_config/conf.py
Update UMF version to 0.10.0 in CI and docs config file.
None CI build on the main branch will pass until this patch is merged.
> Update UMF version to 0.10.0 in headers, CI and docs config file

- src/provider/provider_file_memory.c
Fix error handling in `file_open_ipc_handle()`.
It fixes the Coverity issue no. 469239.
> Fix error handling in file_open_ipc_handle()

- src/utils/utils_macosx_common.c
Remove unneeded functions.
All those functions have `utils_*` counterparts in the same file. They were left here by mistake.
> Remove unneeded functions

- README.md
- include/umf/memory_provider.h
- src/provider/provider_devdax_memory.c
- src/provider/provider_file_memory.c
- src/utils/utils_common.h
- src/utils/utils_linux_common.c
- src/utils/utils_macosx_common.c
- src/utils/utils_windows_common.c
Rename `utils_devdax_mmap()` to `utils_mmap_file()` and improve it:
- add support for `MAP_PRIVATE`
- add `flags` and `fd_offset` arguments
Add support for mapping with `MAP_SYNC` to file provider:
use `utils_mmap_file()` instead of `utils_mmap()`.
> Add support for mapping with MAP_SYNC to file provider

- .github/workflows/basic.yml
Change based on the warning in macos 12 job (as `brew` printed: `We (and Apple) do not provide support for this old version.`)
// https://github.com/oneapi-src/unified-memory-framework/actions/runs/10994309175/job/30527923269#step:4:10
> [CI] Switch MacOS job from old 12 to new 14

- test/CMakeLists.txt
Replace `umf_standalone_examples` with `umf-standalone_examples`.
> Fix name of the umf-standalone_examples test

- examples/cmake/FindCUDA.cmake
- examples/cuda_shared_memory/CMakeLists.txt
Fix `cuda_shared_memory` standalone example.
> Fix cuda_shared_memory standalone example

- .github/workflows/dax.yml
- .github/workflows/pr_push.yml
- test/common/CMakeLists.txt
- test/common/test_helpers_linux.c
- test/common/test_helpers_linux.h
- test/provider_devdax_memory.cpp
- test/provider_file_memory.cpp
Add test if FSDAX is mapped with the `MAP_SYNC` flag
> Add test if FSDAX is mapped with the MAP_SYNC flag

- test/test_valgrind.sh
Fix `test_valgrind.sh`:
If a test fails, but there is no "ERROR SUMMARY" string in the LOG, the LOG is removed and the whole test fails with the following error message:
```
ls: cannot access 'umf_test-*.log': No such file or directory
```
This patch fixes that.
> Fix test_valgrind.sh

- test/common/test_helpers_linux.c
Close file descriptor in `is_mapped_with_MAP_SYNC()`.
> Close file descriptor in is_mapped_with_MAP_SYNC()

- .github/workflows/dax.yml
- CMakeLists.txt
- examples/CMakeLists.txt
- examples/cmake/FindJEMALLOC.cmake
- examples/dram_and_fsdax/CMakeLists.txt
- examples/dram_and_fsdax/dram_and_fsdax.c
- test/CMakeLists.txt
- test/test_examples.sh
Add the `dram_and_fsdax` example.
Ref: #742
> Add dram_and_fsdax example

- .github/workflows/dax.yml
- test/CMakeLists.txt
- test/ipc_file_prov_fsdax.sh
- test/test_valgrind.sh
> Add IPC test for FSDAX

- src/utils/utils_macosx_common.c
Ref. #745
One more function seems unused and redundant.
> Remove redundant, doubled function

- examples/memspace_numa/memspace_numa.c
> add example how to use filterById

- src/ravl/ravl.c
Use the UMF base allocator in RAVL instead of the glibc's one.
> Use the UMF base allocator in RAVL instead of the glibc's one

- README.md
- src/provider/provider_file_memory.c
- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- test/provider_file_memory.cpp
- test/provider_os_memory.cpp
IPC API of OS memory provider requires the `UMF_MEM_MAP_SHARED` memory `visibility` mode (`UMF_RESULT_ERROR_INVALID_ARGUMENT` is returned otherwise).
IPC API of file memory provider requires the `UMF_MEM_MAP_SHARED`
or `UMF_MEM_MAP_SYNC` memory `visibility` mode
(`UMF_RESULT_ERROR_INVALID_ARGUMENT` is returned otherwise).
> Fix arguments checking in IPC API of OS and file memory providers

- test/ipc_file_prov_consumer.c
- test/ipc_file_prov_fsdax.sh
- test/ipc_file_prov_producer.c
Use `UMF_MEM_MAP_SYNC` for FSDAX in the FSDAX IPC example.
> Use UMF_MEM_MAP_SYNC for FSDAX in the FSDAX IPC example

- .github/workflows/performance.yml
Add initial workflow for performance measurements.
// Preview run for `main` branch: https://github.com/oneapi-src/unified-memory-framework/actions/runs/10996891676/job/30531119551
// manual workflow can be tested only if this workflow is merged.
> Add perf workflow

- benchmark/ubench.c
- examples/ipc_level_zero/ipc_level_zero.c
- examples/level_zero_shared_memory/level_zero_shared_memory.c
- src/provider/provider_level_zero.c
handles were being ignored in the initialize function.
Unfortunetaly there is no easy way to test the residency here. I'm working on a test in UR repo for that.
> Fix handling resident_device_handles in L0 provider

- src/memory_pool.c
- src/provider/provider_tracking.c
- src/provider/provider_tracking.h
- test/memoryPoolAPI.cpp
- test/pools/disjoint_pool.cpp
Clear tracker for the current pool when destroying the pool
and clear the whole tracker when destroying the UMF library.
Print error messages about unfreed allocations left in the tracker
only if provider supports the `free()` operation.
> Clear tracker for the current pool on destroy

- src/provider/provider_tracking.c
> Fix one typo in a comment

- cmake/helpers.cmake
Disable setting the `/analyze` flag on Windows if the compiler ID does not equal MSVC, this fixes builds using the `clang-cl.exe` frontend which does not support this flag.
> clang-cl.exe does not support /analyze flag

- test/common/base.hpp
- test/memspaces/memspace_fixtures.hpp
- test/memspaces/memspace_highest_bandwidth.cpp
- test/memspaces/memspace_lowest_latency.cpp
The PR is a part of a major fix, which will be provided in multiple files.
Ref. #569 
canQuery*(...) are changed to void. The success, failure or the need to skip the tests are determined in the function body using GTEST asserts, which set the appropriate flags for the current test. The flags are checked then in the fixture. The solution is inspired by [GTEST docs.](https://google.github.io/googletest/advanced.html#checking-for-failures-in-the-current-test).
The condition using ::memspaceGetTest::IsSkipped() in memspaceProviderTest is replaced due to its ineffectiveness: it has used the method from superclass for itself, before skipping any tests.
EXPECT_* and ADD_FAILURE() interefere with GTEST_SKIP() when used in a non-void helper function - tests are run in spite of labelling as …
> fix: substitute UT_ASSERTs with asserts from GTEST part 4

- README.md
- include/umf/providers/provider_coarse.h
- scripts/docs_config/api.rst
- src/CMakeLists.txt
- src/libumf.def.in
- src/libumf.map.in
- src/provider/provider_coarse.c
- src/utils/utils_common.h
- test/CMakeLists.txt
- test/common/base.hpp
- test/disjointCoarseMallocPool.cpp
- test/supp/helgrind-umf_test-disjointCoarseMallocPool.supp
A memory provider that can provide memory from:
1) a given pre-allocated buffer (the fixed-size memory provider option) or
2) from an additional upstream provider (e.g. provider that does not support the free() operation
like the File memory provider or the DevDax memory provider - see below).
This is a continuation of #378
> Add Coarse provider

- cmake/helpers.cmake
The Intel C++ compiler requires linker flags to be wrapped, because CMake passes them through the compiler driver.
Prefix Linker options with `LINKER:`.
CMake will transform it to the appropriate flag for the compiler driver: (Nothing for MSVC, clang-cl and /Qoption,link for ICX), so this will work for the other compilers too, and for earlier versions of CMake.
Fixes: #757
> Wrap linker flags on Windows for IntelLLVM

- src/libumf.map.in
`umfMemspaceCreateFromNumaArray` is defined in
`memspaces/memspace_numa.c` which is only added to the build if hwloc is enabled.
When hwloc is enabled this is added as an optional symbol to the linker script through `UMF_OPTIONAL_SYMBOLS_LINUX`.
When hwloc is disabled this symbol isn't available so this linker script would fail, I believe the correct fix is just to remove the symbol from the linker script.
I ran into this issue while building DPC++ with hwloc disabled.
> Fix build with hwloc support disabled

- src/provider/provider_coarse.c
Remove unused function `get_block_node()`.
> Remove unused function get_block_node()

- .github/workflows/nightly.yml
In our CI we only test icx on Ubuntu. This introduces a few job with icx run on Windows, but only in nightly build.
Ref. #772 
// Preview run: https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/11235904478
> [CI] Add Windows icx build in nightly workflow

- examples/ipc_ipcapi/ipc_ipcapi_shm.sh
- src/provider/provider_os_memory.c
- test/common/ipc_common.c
- test/ipc_os_prov_shm.sh
open_ipc_handle should use shm from handle
see https://github.com/oneapi-src/unified-memory-framework/issues/777 for details
> open_ipc_handle should use shm from handle

- src/provider/provider_coarse.c
- test/disjointCoarseMallocPool.cpp
Implement more API of the Coarse provider.
> Implement split()/merge() API of the Coarse provider

- src/provider/provider_coarse.c
ifndef NDEBUG get_block_prev() and get_block_next() since
get_block_prev() and get_block_next() are used only in Debug build.
> ifndef NDEBUG get_block_prev() and get_block_next()

- .github/workflows/codeql.yml
- third_party/requirements.txt
Bump pip dependencies to the newest versions. One small downside is that on Windows `sphinx==8.x` requires `python>=3.10`, which is not installed by default on Windows runners (meaning, it's probably not a standard there yet?).
Generated website did not change much:
new, on my fork: https://lukaszstolarczuk.github.io/unified-memory-framework/index.html
current on upstream: https://oneapi-src.github.io/unified-memory-framework/
> Bump pip dependencies

- benchmark/multithread.hpp
Fix: add missing header `<stdexcept>` in benchmark/multithread.hpp
It fixes the following build error:
```
In file included from /home/runner/work/unified-memory-framework/unified-memory-framework/benchmark/multithread.cpp:10:
/home/runner/work/unified-memory-framework/unified-memory-framework/benchmark/multithread.hpp: In function ‘auto umf_bench::measure(size_t, size_t, F&&)’:
/home/runner/work/unified-memory-framework/unified-memory-framework/benchmark/multithread.hpp:42:20: error: ‘runtime_error’ is not a member of ‘std’
42 |         throw std::runtime_error("iterations must be > 1");
|                    ^~~~~~~~~~~~~
/home/runner/work/unified-memory-framework/unified-memory-framework/benchmark/multithread.hpp:24:1: note: ‘std::runtime_error’ is defined in header ‘<stdexcept>’; did …
```
> Fix: add missing header stdexcept in benchmark/multithread.hpp

- src/memory_pool.c
Our current implementation of the `umfPoolDestroy` destroys tracking and the upstream memory providers in the wrong order. The tracking memory provider is a wrapper on top of the upstream memory provider and as a result the `trackingFinalize` function might use upstream memory provider. I found this issue while working on the #736.
> Fix umfPoolDestroy to destroy providers in the right order

- .github/workflows/proxy_lib.yml
- test/test_proxy_lib.cpp
Add missing tests for the proxy library.
> Add missing tests for the proxy library

- src/provider/provider_tracking.c
Fix `trackingFree()` - do not add a not removed entry.
Do not add memory back to the tracker,
if it had not been removed.
> Fix `trackingFree()` - do not add a not removed entry

- src/memory_provider.c
- test/memspaces/memspace_highest_capacity.cpp
- test/provider_os_memory_multiple_numa_nodes.cpp
The PR is a part of a major fix, which will be provided in multiple files.
Ref. #569
> fix: substitute UT_ASSERTs with asserts from GTEST part 5

- src/provider/provider_file_memory.c
- test/provider_file_memory.cpp
Fix `file_alloc()` of the file memory provider.
Fixes: #796
> Fix `file_alloc()` of the file memory provider

- test/ipcFixtures.hpp
Minor fix: Remove an unnecessary parameter in openHandlesFn lambda
> Remove an unnecessary parameter in openHandlesFn lambda

- src/provider/provider_tracking.c
Fix similar error messages:
Replace "provider is failed to" with "provider failed to".
> Fix one error message

- scripts/docs_config/api.rst
Currently, the Coarse Provider section is badly formatted:
fixed version:
https://bratpiorka.github.io/unified-memory-framework/api.html#coarse-provider
> small fix for Coarse Provider html documentation

- test/memoryPoolAPI.cpp
- test/poolFixtures.hpp
- test/pools/disjoint_pool.cpp
- test/pools/jemalloc_pool.cpp
- test/pools/pool_base_alloc.cpp
- test/pools/scalable_pool.cpp
Add optional coarse provider to `umfPoolTest` fixture.
Add 5th argument (`coarse_memory_provider_params_t *`)
to the `poolCreateExtParams` tuple (can be `nullptr`).
If it is `non-nullptr`, coarse provider is created
with the given provider as the upstream provider.
It will be used to test the following providers:
- file provider
- devdax provider
as the upstream providers with the coarse provider
and different pool managers.
Requires:
> Add optional coarse provider to `umfPoolTest` fixture

- src/utils/utils_linux_common.c
Make debug messages in `utils_mmap_file()` more verbose.
It is very useful during debugging.
> Make debug messages in utils_mmap_file() more verbose

- CMakeLists.txt
- examples/cuda_shared_memory/CMakeLists.txt
- examples/ipc_level_zero/CMakeLists.txt
- examples/level_zero_shared_memory/CMakeLists.txt
- src/CMakeLists.txt
- test/CMakeLists.txt
2 changes to avoid CMake warnings:
- ref. https://github.com/oneapi-src/unified-memory-framework/issues/734
- bump GTEST version - it was pretty old and had some warnings
> Fix CMake warnings

- src/provider/provider_cuda.c
- test/providers/cuda_helpers.cpp
- test/providers/cuda_helpers.h
- test/providers/provider_cuda.cpp
During the PR #807 work, I found issues in the CUDA provider implementation. This PR fixes the problems and modifies CUDA tests.
> Fix CUDA provider

- test/CMakeLists.txt
- test/malloc_compliance_tests.cpp
- test/poolFixtures.hpp
- test/pools/jemalloc_coarse_devdax.cpp
- test/pools/pool_coarse.hpp
- test/pools/pool_coarse_file.hpp
- test/pools/scalable_coarse_devdax.cpp
- test/supp/drd-umf_test-jemalloc_coarse_devdax.supp
- test/supp/drd-umf_test-scalable_coarse_devdax.supp
- test/supp/helgrind-umf_test-jemalloc_coarse_devdax.supp
- test/supp/helgrind-umf_test-scalable_coarse_devdax.supp
Add the jemalloc_coarse_devdax and scalable_coarse_devdax tests
that test the coarse provider with upstream devdax provider
and two pool managers: jemalloc and scalable pool.
> Add the jemalloc_coarse_devdax and scalable_coarse_devdax tests

- src/provider/provider_coarse.c
- test/disjointCoarseMallocPool.cpp
Implement `purge_lazy/_force()` API of the Coarse provider.
Tests for the new API are included in https://github.com/oneapi-src/unified-memory-framework/pull/815.
Requires:
> Implement purge_lazy/_force() API of the Coarse provider

- test/disjointCoarseMallocPool.cpp
- test/provider_coarse.cpp
Use `std::vector<char>` instead of `std::unique_ptr<char[]>`
because we do not need to use memset(0) in this case.
> Use `std::vector<char>` instead of `std::unique_ptr<char[]>`

- test/ipcFixtures.hpp
- test/providers/provider_cuda.cpp
- test/providers/provider_level_zero.cpp
To improve code coverage the new tests for CUDA and L0 providers are added. In next PR this tests can be refactored to avoid code duplications.
> Add additional tests for CUDA and L0 providers

- test/memspaces/memspace_host_all.cpp
- test/memspaces/memspace_numa.cpp
> fix: substitute UT_ASSERTs with asserts from GTEST part last

- .github/workflows/pr_push.yml
- .github/workflows/reusable_coverage.yml
- README.md
Verified on pushed branch: https://github.com/oneapi-src/unified-memory-framework/actions/runs/11479430214/job/31950598109
Preview of badges on my fork: https://github.com/lukaszstolarczuk/unified-memory-framework/tree/clean-badges?tab=readme-ov-file#unified-memory-framework
> Badges in readme

- test/common/ipc_common.c
fix error handling in IPC common - this fixes coverity issues:
https://scan3.scan.coverity.com/#/project-view/65229/15141?selectedIssue=469541
https://scan3.scan.coverity.com/#/project-view/65229/15141?selectedIssue=469540
https://scan3.scan.coverity.com/#/project-view/65229/15141?selectedIssue=469539
> fix error handling in IPC common

- .github/workflows/reusable_basic.yml
Disable temporarily failing CI job with ICX compiler.
> Temporarily disable failing CI job with ICX compiler

- src/CMakeLists.txt
Fix fetching L0 and CUDA headers and add `UMF_CUDA_INCLUDE_DIR`.
Fetch L0 loader only if needed i.e.:
if building L0 provider is ON and L0 headers are not provided by the user (via setting `UMF_LEVEL_ZERO_INCLUDE_DIR`).
Fetch CUDA only if needed i.e.:
if building CUDA provider is ON and CUDA headers are not provided by the user (via setting `UMF_CUDA_INCLUDE_DIR`).
Ref: #825
Fixes:: #827
> Fix fetching L0 and CUDA headers and add UMF_CUDA_INCLUDE_DIR

- src/provider/provider_cuda.c
- test/CMakeLists.txt
- test/providers/cuda_helpers.cpp
- test/providers/ipc_cuda_prov.sh
- test/providers/ipc_cuda_prov_common.c
- test/providers/ipc_cuda_prov_common.h
- test/providers/ipc_cuda_prov_consumer.c
- test/providers/ipc_cuda_prov_producer.c
- test/providers/ipc_level_zero_prov_consumer.c
- test/providers/ipc_level_zero_prov_producer.c
Implement IPC API in CUDA provider.
> IPC API in CUDA provider

- test/ipcFixtures.hpp
Add IPC tests for using an allocation after `umfCloseIPCHandle()`.
Test if `umfPoolMalloc()` returns a usable pointer after `umfCloseIPCHandle()`.
> Add IPC tests for using an allocation after `umfCloseIPCHandle()`

- CMakeLists.txt
fix for the apply of the HWLOC security patch
This is a fix for a scenario where the user runs the cmake configuration with the UMF_LINK_HWLOC_STATICALLY setting multiple times for the same build directory. On the first run, cmake downloads the HWLOC sources and successfully applies the required security patch, but the patching fails the second time (the patch has already been applied). This PR fixes this error.
> fix for the apply of the HWLOC security patch

- .github/workflows/basic.yml
Disable temporarily failing CI job with ICX compiler
ref https://github.com/oneapi-src/unified-memory-framework/pull/842
> Disable temporarily failing CI job with ICX compiler

- src/base_alloc/base_alloc.c
- src/base_alloc/base_alloc_linear.c
- src/provider/provider_devdax_memory.c
- src/utils/utils_common.c
- src/utils/utils_common.h
- test/provider_devdax_memory.cpp
Fix devdax_open_ipc_handle() and devdax_close_ipc_handle()
devdax_open_ipc_handle() has to use the path of the remote
/dev/dax got from the IPC handle, not the local one.
devdax_open_ipc_handle() has to use also the memory protection
got from the IPC handle, so let's add the memory protection
to the IPC handle.
devdax_open_ipc_handle() should mmap only the required range of memory,
not the whole /dev/dax device, so let's add the length of the allocation
to the IPC handle.
devdax_close_ipc_handle() should unmap only the required range of memory,
not the whole /dev/dax device.
Fixes: #846
> Fix devdax_open_ipc_handle() and devdax_close_ipc_handle()

- test/c_api/disjoint_pool.c
- test/c_api/multi_pool.c
- test/c_api/test_ut_asserts.h
- test/common/test_helpers.h
> UT_ASSERTs moved to test/c_api

- src/utils/utils_linux_common.c
- test/CMakeLists.txt
- test/ipcAPI.cpp
- test/ipcFixtures.hpp
- test/provider_devdax_memory.cpp
- test/provider_os_memory.cpp
- test/providers/provider_level_zero.cpp
Add IPC tests (`umfIpcTest`) to the devdax provider.
> Add IPC tests (`umfIpcTest`) to the devdax provider

- src/provider/provider_file_memory.c
Alignment passed to `file_alloc()` must be a power of two and a multiple or a divider of the page size.
Align up the alignment in `file_alloc()` to the page size.
`file_open_ipc_handle()` has to use the memory protection and visibility got from the IPC handle, so let's add the memory protection and visibility to the IPC handle.
Ref: #838
Fixes: #848
> Fix `file_alloc()` and `file_open/close_ipc_handle()`

- .github/workflows/reusable_dax.yml
- test/CMakeLists.txt
- test/provider_devdax_memory.cpp
- test/provider_devdax_memory_ipc.cpp
Add DEVDAX and FSDAX tests with the proxy library.
The `umf-provider_devdax_memory_ipc` IPC test is commented out,
because it does not work with the proxy library.
Ref: #864
> Add DEVDAX and FSDAX tests with the proxy library

- test/CMakeLists.txt
- test/ipcFixtures.hpp
- test/ipc_negative.cpp
> Add tests for IPC not supported case

- CMakeLists.txt
The flag that hwloc recognize is --disable-pci, not --disable-pciaccess.
> [main] Fix disabling of pci support in hwloc

- CMakeLists.txt
The flag that hwloc recognize is --disable-pci, not --disable-pciaccess.
> [v0.9.x] Fix disabling of pci support in hwloc

- README.md
Less steps in a build example in README:
- do not mix usage of make and cmake, cmake handles all that is needed
- cmake handles build dir creation
Preview: https://github.com/PatKamin/unified-memory-framework/tree/simplify-build-steps?tab=readme-ov-file#linux
> Simplify build steps example

- src/provider/provider_os_memory.c
Add protection and visibility to the IPC handle.
Fix `os_get_ipc_handle()` - get protection and visibility from the IPC handle instead of provider.
> Fix os_get_ipc_handle() - add protection and visibility

- CMakeLists.txt
- src/CMakeLists.txt
- test/providers/provider_level_zero.cpp
There are two L0-related fixes in this PR:
1. When `UMF_LEVEL_ZERO_INCLUDE_DIR` is set the test cannot be built because of `ze_api.h` not found. It happens because we set `LEVEL_ZERO_INCLUDE_DIRS` in the `src/CMakeLists.txt`. The fix moves corresponding CMake code to the `./CmakeLists.txt`. @lukaszstolarczuk, @bratpiorka, looks like we never checked such flow in CI, can we do that?
2. Some versions of the L0 driver do not return an error when a user tries to allocate 0 bytes. So I removed the corresponding test.
> Fix Level Zero related CMake configs

- test/CMakeLists.txt
- test/common/provider.hpp
- test/disjointCoarseMallocPool.cpp
- test/ipcAPI.cpp
- test/memoryPoolAPI.cpp
- test/pools/disjoint_pool.cpp
- test/provider_coarse.cpp
- test/providers/ipc_cuda_prov_common.c
- test/test_valgrind.sh
Replace `MALLOC_PROVIDER_OPS` with `BA_GLOBAL_PROVIDER_OPS`:
1) Use `umf_ba_global_*()` API in `MALLOC_PROVIDER_OPS`,
2) Rename `provider_malloc` to `provider_ba_global`,
3) Rename `MALLOC_PROVIDER_OPS` to `BA_GLOBAL_PROVIDER_OPS`.
> Replace `MALLOC_PROVIDER_OPS` with `BA_GLOBAL_PROVIDER_OPS`

- test/CMakeLists.txt
Fix building the `provider_file_memory_ipc` test.
> Fix building the `provider_file_memory_ipc` test

- .github/workflows/reusable_basic.yml
- CMakeLists.txt
- src/CMakeLists.txt
- src/provider/provider_devdax_memory.c
- src/provider/provider_tracking.c
- src/proxy_lib/proxy_lib.c
- test/CMakeLists.txt
- test/ipc_os_prov_proxy.c
- test/ipc_os_prov_proxy.sh
Enable Tracking Provider in the Proxy Lib by default.
> enable tracker in ProxyLib by default

- src/provider/provider_coarse.c
- test/provider_coarse.cpp
Increase code coverage of Coarse provider:
- add missing tests,
- remove unreachable checks.
> Increase code coverage of Coarse provider

- .github/workflows/reusable_dax.yml
Do not run tests under the proxy library if libumf is not a shared library,
because the proxy library is built only if libumf is a shared library.
ref. #761
> Do not run tests under proxy lib if libumf is not a shared lib

- .github/workflows/reusable_sanitizers.yml
- src/base_alloc/base_alloc.c
- src/base_alloc/base_alloc_global.c
- src/base_alloc/base_alloc_linear.c
- src/provider/provider_os_memory.c
- src/proxy_lib/proxy_lib.c
- src/utils/utils_common.h
- test/common/provider.hpp
- test/common/test_helpers.h
- test/poolFixtures.hpp
- test/provider_os_memory.cpp
- test/provider_os_memory_multiple_numa_nodes.cpp
- test/supp/helgrind-umf_test-disjointPool.supp
- test/test_valgrind.sh
> Add overflow tests

- .github/workflows/reusable_gpu.yml
- cmake/FindCUDA.cmake
- examples/cmake/FindCUDA.cmake
- examples/cuda_shared_memory/cuda_shared_memory.c
- src/provider/provider_cuda.c
- src/utils/utils_load_library.c
- test/providers/cuda_helpers.cpp
- test/providers/cuda_helpers.h
- test/providers/provider_cuda.cpp
enable CUDA provider on windows
> enable CUDA provider on windows

- src/CMakeLists.txt
- src/ipc.c
- src/ipc_cache.c
- src/ipc_cache.h
- src/ipc_internal.h
- src/libumf.c
- src/provider/provider_tracking.c
- src/uthash/uthash.h
- src/uthash/utlist.h
- src/utils/utils_concurrency.h
- test/CMakeLists.txt
- test/ipcFixtures.hpp
- test/provider_os_memory.cpp
- test/supp/drd-umf_test-provider_devdax_memory_ipc.supp
- test/supp/drd-umf_test-provider_os_memory.supp
- test/supp/helgrind-umf_test-provider_devdax_memory_ipc.supp
- test/supp/helgrind-umf_test-provider_file_memory_ipc.supp
- test/supp/helgrind-umf_test-provider_os_memory.supp
This PR adds initial set of changes to implement cache for opened IPC handles.
The new third-party data structure (uthash - has map implementation) is added. The same data structure is used by MPI to implement IPC cache. Here is the [uthash documentation](https://troydhanson.github.io/uthash/). Here is the [original source repo](https://github.com/troydhanson/uthash)
Fixes: https://github.com/oneapi-src/unified-memory-framework/issues/403
> Implement IPC cache for umfOpenIPCHandle function

- include/umf/pools/pool_scalable.h
- src/cpp_helpers.hpp
- src/libumf.def
- src/libumf.map
- src/pool/pool_scalable.c
- test/pools/scalable_pool.cpp
- test/supp/memcheck-umf_test-scalable_pool.supp
Introduce config params for scalable pool
> Introduce config params for scalable pool

- .github/workflows/nightly.yml
- .github/workflows/pr_push.yml
- .github/workflows/reusable_gpu.yml
- .github/workflows/reusable_multi_numa.yml
- .github/workflows/reusable_qemu.yml
- scripts/qemu/run-tests.sh
- scripts/qemu/start_qemu.sh
Each commit should be checked separately.
QEMU build is split, to only run selected jobs per PR and the whole suite (with extra OS) on nightly. QEMU in short run executes only 3 configs and valgrind is executed only on `default`.
// nightly qemu (long) run was executed on my fork: https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/11722236706/job/32651339247
CUDA and L0 - similarly - only a few jobs on PR, the rest during the nigth.
Multi Numa workflow is extended, because it's executed very quickly.
> Workflows clean up (part 2)

- src/pool/pool_scalable.c
- test/pools/scalable_pool.cpp
- Fix Coverity issues in `scalable_pool.cpp`.
- Cosmetic changes in scalable pool params implementation.
> Minor fixes in scalable pool params implementation

- src/utils/utils_linux_common.c
Fix location of printing out error message in `utils_mmap_file()`.
It was printed out in a wrong place.
> Fix location of printing out error message in utils_mmap_file()

- src/provider/provider_devdax_memory.c
- src/provider/provider_file_memory.c
- test/provider_file_memory_ipc.cpp
- test/supp/helgrind-umf_test-ipc.supp
Enable IPC API for FSDAX.
FSDAX requires 2 MB page size.
> Enable IPC API for FSDAX

- examples/custom_file_provider/custom_file_provider.c
- src/memory_provider.c
- src/provider/provider_coarse.c
- src/provider/provider_cuda.c
- src/provider/provider_devdax_memory.c
- src/provider/provider_file_memory.c
- src/provider/provider_level_zero.c
- src/provider/provider_os_memory.c
- test/memoryProviderAPI.cpp
Remove dead code - remove checks run always earlier in `src/memory_provider.c`.
> Remove dead code

- .github/workflows/reusable_basic.yml
Temporarily disable failing windows-2022 clang CI job, because of the error:
```
Error: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\lib\clang\18\include\__stddef_ptrdiff_t.h(15): fatal error RC1012: mismatched parenthesis : missing ' [D:\a\unified-memory-framework\unified-memory-framework\build\src\umf.vcxproj]
```
See: 
https://github.com/oneapi-src/unified-memory-framework/actions/runs/11892350813/job/33136923719
https://github.com/oneapi-src/unified-memory-framework/actions/runs/11893427436/job/33141053575
Ref: https://github.com/oneapi-src/unified-memory-framework/issues/910
> Temporarily disable failing windows-2022 clang CI job

- src/ipc_cache.c
Fix: `getGlobalLruListSize()` is needed only in debug mode.
Fix the warning:
```
warning : unused function 'getGlobalLruListSize' [-Wunused-function]
```
> Fix: `getGlobalLruListSize()` is needed only in debug mode

- benchmark/multithread.cpp
- benchmark/ubench.c
- examples/cuda_shared_memory/cuda_shared_memory.c
- examples/dram_and_fsdax/dram_and_fsdax.c
- examples/ipc_level_zero/ipc_level_zero.c
- examples/level_zero_shared_memory/level_zero_shared_memory.c
- include/umf/pools/pool_disjoint.h
- include/umf/pools/pool_jemalloc.h
- src/pool/pool_disjoint.cpp
- src/pool/pool_jemalloc.c
- test/c_api/disjoint_pool.c
- test/c_api/multi_pool.c
- test/disjointCoarseMallocPool.cpp
- test/pools/disjoint_pool.cpp
- test/pools/jemalloc_pool.cpp
- test/provider_os_memory.cpp
- test/providers/ipc_cuda_prov_consumer.c
- test/providers/ipc_cuda_prov_producer.c
- test/providers/ipc_level_zero_prov_consumer.c
- test/providers/ipc_level_zero_prov_producer.c
> Update params implementation

- src/utils/utils_load_library.c
Print `dlerror()` in `utils_open_library()` and `utils_get_symbol_addr()`.
> Print dlerror in utils_open_library() and utils_get_symbol_addr()

- cmake/helpers.cmake
- src/ipc_cache.c
- src/memtargets/memtarget_numa.c
- src/provider/provider_cuda.c
- src/provider/provider_level_zero.c
- src/provider/provider_os_memory.c
- test/CMakeLists.txt
- test/memspaces/memspace_fixtures.hpp
- test/poolFixtures.hpp
- test/providers/provider_level_zero.cpp
> Enable -Werror flag in developer build

- examples/cuda_shared_memory/cuda_shared_memory.c
- include/umf/providers/provider_cuda.h
- src/libumf.def
- src/libumf.map
- src/provider/provider_cuda.c
- test/providers/cuda_helpers.cpp
- test/providers/cuda_helpers.h
- test/providers/ipc_cuda_prov_common.c
- test/providers/ipc_cuda_prov_common.h
- test/providers/ipc_cuda_prov_consumer.c
- test/providers/ipc_cuda_prov_producer.c
- test/providers/provider_cuda.cpp
Change the Cuda provider config as we agreed in #844
> Update Cuda provider config API

- test/poolFixtures.hpp
> Add test for `umfPoolMallocUsableSize` to improve coverage of `base_alloc_global.c`

- test/poolFixtures.hpp
CI for the following PRs (#927 #920) failed because of an unreachable code error.
> Fix unreachable code error when Sanitazer is enabled

- .github/workflows/nightly.yml
- .github/workflows/reusable_qemu.yml
End of Life of Ubuntu 24.04 LTS (Noble Numbat) is April 2036.
End of Life of Ubuntu 22.04 LTS (Jammy Jellyfish) is April 2034.
End of Life of Ubuntu 23.04 (Lunar Lobster) was January 25, 2024.
> Update Ubuntu versions in CI

- .github/workflows/nightly.yml
disable ICX tests in nightly builds
issue: https://github.com/oneapi-src/unified-memory-framework/issues/843
> disable ICX tests in nightly builds

- examples/dram_and_fsdax/dram_and_fsdax.c
- include/umf/providers/provider_file_memory.h
- src/libumf.def
- src/libumf.map
- src/provider/provider_file_memory.c
- test/CMakeLists.txt
- test/ipc_file_prov_consumer.c
- test/ipc_file_prov_producer.c
- test/pools/jemalloc_coarse_file.cpp
- test/pools/scalable_coarse_file.cpp
- test/provider_file_memory.cpp
- test/provider_file_memory_ipc.cpp
- test/provider_file_memory_not_impl.cpp
Change the File Provider config as we agreed in #844.
> Update File provider config API

- test/CMakeLists.txt
- test/providers/provider_cuda_not_impl.cpp
- test/providers/provider_level_zero_not_impl.cpp
Two additional tests when CUDA and Level zero providers are disabled
> Additional tests when CUDA or Level Zero providers are disabled

- benchmark/multithread.cpp
- benchmark/ubench.c
- examples/basic/basic.c
- examples/dram_and_fsdax/dram_and_fsdax.c
- examples/ipc_ipcapi/ipc_ipcapi_consumer.c
- examples/ipc_ipcapi/ipc_ipcapi_producer.c
- include/umf/providers/provider_os_memory.h
- scripts/docs_config/examples.rst
- src/libumf.def
- src/libumf.map
- src/memtargets/memtarget_numa.c
- src/provider/provider_os_memory.c
- src/proxy_lib/proxy_lib.c
- test/c_api/multi_pool.c
- test/fuzz/umfFuzz.cpp
- test/ipc_os_prov_consumer.c
- test/ipc_os_prov_producer.c
- test/pools/jemalloc_pool.cpp
- test/pools/scalable_pool.cpp
- test/provider_os_memory.cpp
- test/provider_os_memory_config.cpp
- test/provider_os_memory_multiple_numa_nodes.cpp
Change the L0 provider config as we agreed in #844
> Update OS provider config API

- src/pool/pool_scalable.c
- src/provider/provider_cuda.c
This should fix the following failure: https://github.com/oneapi-src/unified-memory-framework/actions/runs/12041220655/job/33590212027
> Fix failure with destructor order in CUDA params

- src/proxy_lib/proxy_lib.c
Use unused `ba_leak_aligned_alloc()` in `ba_leak_malloc()` and `ba_leak_calloc()`.
Remove not needed code.
> Use unused `ba_leak_aligned_alloc()`

- test/CMakeLists.txt
- test/provider_os_memory_not_impl.cpp
Add test for not implemented OS provider
> Add test for not implemented OS provider

- include/umf/providers/provider_devdax_memory.h
- src/libumf.def
- src/libumf.map
- src/provider/provider_devdax_memory.c
- test/CMakeLists.txt
- test/ipc_devdax_prov_consumer.c
- test/ipc_devdax_prov_producer.c
- test/poolFixtures.hpp
- test/pools/jemalloc_coarse_devdax.cpp
- test/pools/scalable_coarse_devdax.cpp
- test/provider_devdax_memory.cpp
- test/provider_devdax_memory_ipc.cpp
- test/provider_devdax_memory_not_impl.cpp
Change the L0 provider config as we agreed in #844
> Update DevDax provider config API

- .github/workflows/nightly.yml
- .github/workflows/reusable_qemu.yml
Update and fix QEMU Ubuntu
// preview nightly: https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/12068436829
> QEMU ubuntu fix & update

- cmake/helpers.cmake
This change removes all unnecessary flags that are enabled by other flags like `-Wall`, `-Wextra`, `-Wpedantic`
Resolves #944
> [CMake] Remove redundant compilation flags

- cmake/helpers.cmake
- src/CMakeLists.txt
- src/coarse/CMakeLists.txt
- src/coarse/coarse.c
- src/coarse/coarse.h
- test/CMakeLists.txt
- test/coarse_lib.cpp
Add the coarse library that will replace the coarse provider.
Example of usage: https://github.com/oneapi-src/unified-memory-framework/pull/932
Code coverage of the coarse library is 92.6%.
> Add the coarse library

- test/CMakeLists.txt
Clean up `target_*()` calls in `test/CMakeLists.txt`.
> Clean up target_*() calls in test/CMakeLists.txt

- ChangeLog
Thanks to this merge we assure no missing patches on main, plus all patch releases (along with tags) will be available on the main branch.
> Merge stable branch v0.9.x to main

- .github/workflows/reusable_gpu.yml
- CMakeLists.txt
- benchmark/CMakeLists.txt
- benchmark/benchmark.cpp
- benchmark/benchmark.hpp
- benchmark/benchmark_interfaces.hpp
- benchmark/multithread.cpp
- benchmark/ubench.c
- L0 benchmark will be added in separate PR (unless merge of this one will take too long ;))
- Old benchmark will be removed in separate PRs too
- Please focus more on bechmark framework - particular benchmark will be also changed in separate PRs - current set is more a demo of framework - to select good benchmark scenarios there is litte bit more research to be done.
> Add new benchmarks

- src/provider/provider_devdax_memory.c
- src/provider/provider_file_memory.c
- test/ipcAPI.cpp
- test/ipcFixtures.hpp
- test/provider_devdax_memory.cpp
- test/provider_devdax_memory_ipc.cpp
- test/provider_file_memory.cpp
- test/provider_file_memory_ipc.cpp
- test/provider_os_memory.cpp
- test/providers/provider_level_zero.cpp
Use libcoarse in the file and the devdax providers.
This PR is required by 3 PRs that fix the following issues:
- https://github.com/oneapi-src/unified-memory-framework/issues/864
- https://github.com/oneapi-src/unified-memory-framework/issues/900
- https://github.com/oneapi-src/unified-memory-framework/issues/904
> Use libcoarse in the file and the devdax providers

- src/proxy_lib/proxy_lib.c
Revert WA for the issue with jemalloc in the proxy library.
This reverts commit a4fced635067affb6787da41116ae3ffadfc5597.
Fixes: #894
Depends on:
> Revert WA for the issue with jemalloc in the proxy library

- examples/ipc_ipcapi/ipc_ipcapi_consumer.c
- examples/ipc_level_zero/ipc_level_zero.c
- include/umf/ipc.h
- scripts/docs_config/examples.rst
- src/ipc.c
- src/libumf.def
- src/libumf.map
- test/common/ipc_common.c
- test/ipcFixtures.hpp
- test/ipc_negative.cpp
As we agreed on the UMF technical meeting, this PR introduces `umf_ipc_handler_handle_t` that is used by the `umfOpenIPCHandle` function instead of pool handle to open the IPC handle. In current implementation the `umf_ipc_handler_handle_t` is just a memory provider handle to the tracking provider instance.
> Update umfOpenIPCHandle API to use IPC handler instead of pool

- src/provider/provider_file_memory.c
- src/provider/provider_os_memory.c
Fix two error messages and add some new ones.
> Fix and add error messages

- .github/workflows/reusable_dax.yml
- .github/workflows/reusable_proxy_lib.yml
Enable IPC tests with the proxy library which were disabled, because of the issue: https://github.com/oneapi-src/unified-memory-framework/issues/864
Fixes: #864
Requires:
> Enable IPC tests with the proxy library

- CMakeLists.txt
The `make install` step is executed always
and all UMF tests are re-linked also always now
because of an incorrect dependence.
This patch fixes that.
> Fix building the custom jemalloc

- include/umf/memory_pool.h
- src/libumf.def
- src/libumf.map
- src/memory_pool.c
- src/memory_pool_internal.h
- test/memoryPoolAPI.cpp
Implements https://github.com/oneapi-src/unified-memory-framework/issues/687
> Implement umfPool[Set/Get]Tag

- .github/workflows/reusable_gpu.yml
- .github/workflows/reusable_multi_numa.yml
1) Do not check coverage in the Release multi-numa build
2) Unify the name of the coverage data file in the `upload-artifact`
step and the coverage artifact file in the `Check coverage` step.
A name of the coverage artifact file in the `Check coverage` step
must be unique.
> Do not check coverage in the Release multi-numa build

- CMakeLists.txt
Disable not used hwloc feature "rsmi". Silence errors during hwloc linkage to umf, like:
```
/usr/bin/ld: _deps/hwloc_targ-build/lib/libhwloc.a(topology-rsmi.o): in function `get_device_name': topology-rsmi.c:(.text+0x208): undefined reference to `rsmi_dev_name_get'
```
> Disable rsmi in hwloc build

- src/coarse/coarse.c
- src/coarse/coarse.h
- src/utils/utils_common.c
- test/coarse_lib.cpp
- test/provider_devdax_memory.cpp
Make `coarse_alloc()` always return address aligned to `coarse->page_size` when `alignment==0`.
> Make coarse_alloc() return aligned address when alignment==0

- src/utils/utils_common.c
- test/utils/utils_linux.cpp
Remove incorrect assert in `utils_align_ptr_up_size_down()`.
A pointer is aligned, but a size is only adjusted to the new pointer.
The size does not have to be aligned.
> Fix: remove incorrect assert in utils_align_ptr_up_size_down()

- CMakeLists.txt
- README.md
It is supported on Linux, MacOS, and Windows with the exception that the proxy library is disabled when this flag is used on Windows with Debug config.
> Update description of UMF_LINK_HWLOC_STATICALLY flag

- .github/workflows/reusable_gpu.yml
- .github/workflows/reusable_multi_numa.yml
- CMakeLists.txt
- ChangeLog
- examples/ipc_ipcapi/ipc_ipcapi_consumer.c
- examples/ipc_level_zero/ipc_level_zero.c
- include/umf/ipc.h
- licensing/third-party-programs.txt
- scripts/docs_config/examples.rst
- src/ipc.c
- src/libumf.def
- src/libumf.map
- test/common/ipc_common.c
- test/ipcFixtures.hpp
- test/ipc_negative.cpp
- test/utils/utils_linux.cpp
Merge changes from v0.10.x into main, including latest release.
> Merge v0.10.x into main

- benchmark/benchmark.cpp
- benchmark/benchmark.hpp
- benchmark/benchmark_interfaces.hpp
On Windows static builds, destructors are invoked after the UMF destructor, causing parameter structures to be unable to be destroyed. By switching to std::unique_ptr, we ensure that parameters are properly cleaned up and the destruction order issue is resolved.
> use unique_ptr instead of constructor/destructor in benchmarks

- CMakeLists.txt
- CONTRIBUTING.md
- src/CMakeLists.txt
- src/utils/utils_log.c
- test/utils/utils_log.cpp
Add strings with UMF version and useful CMake variables that can be grepped in the following way:
```sh
$ strings libumf.so | grep "@(#)"
@(#) Intel(R) UMF version: 0.10.0-git4.g55d6db70
@(#) Intel(R) UMF CMake variables: "CMAKE_BUILD_TYPE:Debug,UMF_BUILD_BENCHMARKS:OFF,UMF_BUILD_BENCHMARKS_MT:OFF,UMF_BUILD_CUDA_PROVIDER:ON,UMF_BUILD_EXAMPLES:ON,UMF_BUILD_FUZZTESTS:OFF,UMF_BUILD_GPU_EXAMPLES:OFF,UMF_BUILD_GPU_TESTS:OFF,UMF_BUILD_LEVEL_ZERO_PROVIDER:ON,UMF_BUILD_LIBUMF_POOL_DISJOINT:OFF,UMF_BUILD_LIBUMF_POOL_JEMALLOC:ON,UMF_BUILD_SHARED_LIBRARY:ON,UMF_BUILD_TESTS:ON,UMF_DEVELOPER_MODE:ON,UMF_DISABLE_HWLOC:OFF,UMF_FORMAT_CODE_STYLE:ON,UMF_HWLOC_NAME:hwloc,UMF_LINK_HWLOC_STATICALLY:OFF,UMF_PROXY_LIB_BASED_ON_POOL:SCALABLE,UMF_TESTS_FAIL_ON_SKIP:OFF,UMF_USE_ASAN:OFF,UMF_USE_COVERAGE:OFF,UMF_US …
```
> Add strings with UMF version and useful CMake options

- examples/custom_file_provider/custom_file_provider.c
Print more info when open() fails in the custom_file_provider example.
> Print more info when open() fails in the custom_file_provider example

- test/test_valgrind.sh
Run also examples under valgrind.
> Run also examples under valgrind

- cmake/helpers.cmake
- src/CMakeLists.txt
- src/ctl/ctl.c
- src/ctl/ctl.h
- test/CMakeLists.txt
- test/ctl/config.txt
- test/ctl/ctl_debug.c
- test/ctl/ctl_debug.h
- test/ctl/test.cpp
This commit introduces sources and compilation of the CTL.
TODO:
Other:
> CTL: Add a CTL sources to the UMF

- test/CMakeLists.txt
Fix name of the `proxy_lib_size_threshold` test.
> Fix name of the `proxy_lib_size_threshold` test

- .github/workflows/reusable_dax.yml
- .github/workflows/reusable_multi_numa.yml
- test/test_valgrind.sh
> Run DAX and multi-NUMA tests under valgrind

- src/ctl/ctl.c
- src/ctl/ctl.h
- test/ctl/ctl_debug.c
This commit reverts changes that can make code reading more difficult.
> Remove unnecessary commas due to removing pedantic option

- src/provider/provider_cuda.c
- src/provider/provider_devdax_memory.c
- src/provider/provider_file_memory.c
- src/provider/provider_level_zero.c
Add error messages when memory providers are disabled.
> Add error messages when memory providers are disabled

- src/provider/provider_level_zero.c
Set device_properties.stype during init.
Found by L0 validation layer.
> Fix L0 provider

- RELEASE_STEPS.md
- src/libumf.def
- src/libumf.map
- src/proxy_lib/proxy_lib.def
- src/proxy_lib/proxy_lib.map
and unify names used in these files - "LIBUMF" and "LIBUMF_PROXY"
> Set symbol versions 0.10 in def/map files

- .github/workflows/reusable_basic.yml
- RELEASE_STEPS.md
use the UMF version from git describe in tests, not the harcoded one
fixes https://github.com/oneapi-src/unified-memory-framework/issues/1025
> use the UMF version from git describe in tests, not the harcoded one

- CMakeLists.txt
- RELEASE_STEPS.md
- docs/README.md
- docs/config/conf.py
use the UMF version from git describe in docs, not the harcoded one
logs from the workflow on my fork:
https://github.com/bratpiorka/unified-memory-framework/actions/runs/12667121286/job/35299837634
built docs:
https://bratpiorka.github.io/unified-memory-framework/
fixes: https://github.com/oneapi-src/unified-memory-framework/issues/1024
> use the UMF version from git describe in docs, not the harcoded one

- .github/workflows/reusable_basic.yml
- .github/workflows/reusable_sanitizers.yml
- CMakeLists.txt
- cmake/helpers.cmake
- test/CMakeLists.txt
There is a problem with linkage under icx/icpx due to linking against compiler libs.
When executing tests without sourced paths to compiler (prevents from loading compiler version of UMF) there are errors of missing symbols/libs.
There was 2 options:
- link statically against compiler dependencies using `-static-intel`
- omit linking Intel compiler extensions with `-no-intel-lib` ([more info](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/no-intel-lib-qno-intel-lib.html)) or using another option `-Wl,-as-needed'`
First works like a charm, but the UMF contains icx/icpx needed dependencies compiled in, I don't know it's a problem or not. 
Last option require to force `gtest` to compile the same way - without Intel compiler dependencies (e.g. …
> Make ICX enabled again

- README.md
Add GAI Tooling Notice to readme
> Add GAI Tooling Notice to readme

- benchmark/benchmark.cpp
- benchmark/benchmark.hpp
> reduce code duplication in Benchmark by using Apply() to set arguments

- src/provider/provider_cuda.c
`cu_provider->device` is not set (equals 0) in this place yet, so we have to use `cu_params->cuda_device_handle` instead of `cu_provider->device` here.
> Fix: use cuda_device_handle in cu_memory_provider_initialize

- .github/workflows/reusable_basic.yml
- .github/workflows/reusable_fast.yml
- .github/workflows/reusable_proxy_lib.yml
- .github/workflows/reusable_sanitizers.yml
- README.md
- examples/ipc_ipcapi/ipc_ipcapi_anon_fd.sh
- examples/ipc_ipcapi/ipc_ipcapi_producer.c
- scripts/qemu/run-tests.sh
- src/utils/utils_posix_common.c
- test/common/ipc_common.c
- test/ipc_os_prov_anon_fd.sh
- test/providers/ipc_level_zero_prov.sh
Update our documentation with better info about ptrace - IPC users should be aware of required permissions. Add proposed, two possible solutions into our docs. Also, update our examples and tests to work without global change of ptrace_scope.
Co-authored-by: sergey.vinogradov@intel.com
// Continuation of https://github.com/oneapi-src/unified-memory-framework/pull/1018
Fixes: https://github.com/oneapi-src/unified-memory-framework/issues/979
> Add info about ptrace permissions

- RELEASE_STEPS.md
- cmake/helpers.cmake
- src/libumf.def
Each commit introduces a small update around versioning.
Comment about additional `-devX` tags (from commit msg):
```
-devX tag may be required when e.g. a first -dev tag was "replaced"
with new patch release incoming from stable branch into main.
E.g., at this moment, the main branch is introduced as v0.10.1-...
instead of v0.11.0-dev... and this is not desired.
```
Locally tested:
`UMF version: 0.99.1-dev`
`UMF version: 0.99.1-dev.git1.gc184e8e2`
`UMF version: 0.99.2-dev3.git3.gc184e8e2`
After this change is merged I'll "fix" our main branch with proper versioning with a new dev tag `v0.11.0-dev1`.
> Minor updates around versioning

- .github/workflows/reusable_basic.yml
- src/CMakeLists.txt
Replaces #1050 which targeted v0.10.x
Needed for changes in intel/llvm: https://github.com/intel/llvm/pull/15261
> Test static hwloc build on macOS

- test/pools/disjoint_pool.cpp
The UMF tests should not use the default system allocator to allocate memory, because they may not work correctly under the UMF proxy library when they and the proxy library are dynamically linked with the same libumf.so file.
In such case the same tracker is used in both: the test and the proxy library, so there may be conflicts of memory allocations. An allocation made originally by the the default system allocator in the test is first added to the tracker by the proxy library (which replaced the system allocator) and then the test itself tries to add the same pointer to the same tracker in the tracking provider of the pool that had made this allocation.
Fixes: #240
> Fix disjoint_pool unit tests

- examples/CMakeLists.txt
Add timeout to the `add_umf_ipc_example` function.
> Add timeout to the add_umf_ipc_example function

- .cmake-format
- CMakeLists.txt
- benchmark/ubench.c
- examples/CMakeLists.txt
- examples/ipc_level_zero/ipc_level_zero.c
- examples/level_zero_shared_memory/level_zero_shared_memory.c
- test/CMakeLists.txt
Each commit introduces a small fix/update around CMake. The "most important" part is to add a warning if a version is set to 0.0.0, which should be rather unexpected for users.
> Various CMake updates

- test/ipcAPI.cpp
- test/ipcFixtures.hpp
- test/memoryPoolAPI.cpp
- test/poolFixtures.hpp
- test/pools/disjoint_pool.cpp
- test/pools/jemalloc_coarse_devdax.cpp
- test/pools/jemalloc_coarse_file.cpp
- test/pools/jemalloc_pool.cpp
- test/pools/pool_base_alloc.cpp
- test/pools/scalable_coarse_devdax.cpp
- test/pools/scalable_coarse_file.cpp
- test/pools/scalable_pool.cpp
- test/provider_devdax_memory_ipc.cpp
- test/provider_file_memory_ipc.cpp
- test/provider_os_memory.cpp
- test/providers/provider_cuda.cpp
- test/providers/provider_level_zero.cpp
Do not use global constructor/destructors for test params.
Currently, all provider and pool tests use parameters created during the instantiation phase, with automatic destructors called upon program exit. The problem occurs when the creation of some parameters requires our global base allocator (in the case for the Disjoint Pool in the C version - not merged yet). In this scenario, the global base allocator's free() function could be called after the deletion of the entire global base allocator, because we cannot guarantee the correct order of destructors. Additionally, in the failing scenario, the base allocator's debug checks will report memory leaks.
> do not use global ctor/dtor for test params

- src/provider/provider_cuda.c
Check return value of set_context() in
cu_memory_provider_open_ipc_handle().
It fixes a Coverity issue no. 473892
> Check return value of set_context()

- include/umf/providers/provider_level_zero.h
- src/libumf.def
- src/libumf.map
- src/provider/provider_level_zero.c
- src/utils/utils_level_zero.cpp
- src/utils/utils_level_zero.h
- test/providers/provider_level_zero.cpp
- test/providers/provider_level_zero_not_impl.cpp
and allow passing device ordinal through params
> L0 provider: implement min/recommended page size query

- test/CMakeLists.txt
Add `LIBHWLOC_INCLUDE_DIRS` to `build_umf_test()`
when `UMF_LINK_HWLOC_STATICALLY` is ON.
Ref: #1065
> Add LIBHWLOC_INCLUDE_DIRS to build_umf_test()

- .github/workflows/reusable_benchmarks.yml
- .github/workflows/reusable_docs_build.yml
Fix cache for bench results - dir should most likely match, when cached and restored.
Side note, caches are accessible only on the same branch - PR cannot access caches from, e.g., main branch.
// I tested this only partially: https://github.com/oneapi-src/unified-memory-framework/actions/runs/13075967093/job/36488171640
> Fix bench cache restore

- .gitignore
add clangd files to gitignore:
./.cache/clangd
compile_commands.json
> add clangd files to gitignore

- .github/workflows/reusable_basic.yml
- cmake/helpers.cmake
partially reverts changes from #1030 
`-no-intel-lib` breaks the compiler's build, as these extra intel libs should be normally usable and reachable.
Fix our CI build with sourcing setvars and updating LD_LIBRARY_PATH.
// Verified on my fork, ICX build only: https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/13200540850
> Fix icx build

- .github/scripts/get_system_info.sh
- .github/workflows/docs.yml
- .github/workflows/nightly.yml
- .github/workflows/reusable_benchmarks.yml
Make use of new runner for benchmarks, plus minor changes around the bench workflows.
// example results: https://github.com/oneapi-src/unified-memory-framework/actions/runs/13186606144/job/36810064078?pr=1082
> New bench runner

- CMakeLists.txt
- src/provider/provider_cuda.c
Fix: remove `CUDA_ERROR_INVALID_RESOURCE_TYPE`.
`CUDA_ERROR_INVALID_RESOURCE_TYPE` is not defined in CUDA v10.1 that is used in UR.
PR in UR: https://github.com/oneapi-src/unified-runtime/pull/2680
> Fix: remove `CUDA_ERROR_INVALID_RESOURCE_TYPE`

- .github/workflows/reusable_gpu.yml
- benchmark/CMakeLists.txt
This PR fixes the compilation error during `ubench` compilation when `-DUMF_BUILD_CUDA_PROVIDER=ON -DUMF_BUILD_LEVEL_ZERO_PROVIDER=OFF`.
Here is the compilation error:
```bash
[ 24%] Built target umf-ubench
In file included from /nfs/pdx/home/svinogra/unified-memory-framework/benchmark/multithread.cpp:10:
/nfs/pdx/home/svinogra/unified-memory-framework/benchmark/multithread.hpp:24:10: fatal error: multithread_helpers.hpp: No such file or directory
24 | #include "multithread_helpers.hpp"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [benchmark/CMakeFiles/umf-multithreaded.dir/build.make:76: benchmark/CMakeFiles/umf-multithreaded.dir/multithread.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3034: benchmark/CMakeFiles/umf-multithreaded.dir/all] Error 2 …
```
> Fix ubench for CUDA provider

- .github/workflows/reusable_gpu.yml
disable the UMF MT bench in the GPU workflow as it crashes on GitHub machines. 
see https://github.com/oneapi-src/unified-memory-framework/actions/runs/13255586163/job/37001810256 
it will only be built
> disable umf mt bench in GPU workflow

- .github/workflows/reusable_basic.yml
- src/coarse/CMakeLists.txt
Revert "Temporarily disable failing windows-2022 clang CI job".
This reverts commit 467be1753b0274169666da6dc15c21ede8b1286d.
Fixes: #910
> Revert "Temporarily disable failing windows-2022 clang CI job"

- src/pool/pool_scalable.c
- src/provider/provider_cuda.c
- src/provider/provider_level_zero.c
- src/proxy_lib/proxy_lib.c
Use `LOG_FATAL()` in case of critical errors.
> Use LOG_FATAL() in case of critical errors

- src/proxy_lib/proxy_lib.c
This improves search time if ptr belongs to leak pool, during free
> Increase pool size of the "leak" base allocator in proxy lib

- examples/level_zero_shared_memory/level_zero_shared_memory.c
While working on the #1086 I found that the `umf_example_level_zero_shared_memory` returns success even the actual flow failed. See the output below:
```bash
test 1
Start 1: umf_example_level_zero_shared_memory
1: Test command: /home/test-user/actions-runner/_work/unified-memory-framework/unified-memory-framework/build/examples-standalone/level_zero_shared_memory/umf_example_level_zero_shared_memory
1: Test timeout computed to be: 10000000
1: [FATAL UMF] utils_open_library: dlopen(libze_loader.so) failed with error: (null)
1: [FATAL UMF] ze_memory_provider_initialize: Loading Level Zero symbols failed
1: Failed to create a memory provider!
1/1 Test #1: umf_example_level_zero_shared_memory ...   Passed    0.06 sec
```
> Do not overwrite ret code in level_zero_shared_memory example

- include/umf/providers/provider_cuda.h
- src/libumf.def
- src/libumf.map
- src/provider/provider_cuda.c
- test/providers/cuda_helpers.cpp
- test/providers/cuda_helpers.h
- test/providers/provider_cuda.cpp
- test/providers/provider_cuda_not_impl.cpp
Add support for CUDA allocation flags.
This PR adds one new API call for CUDA:
- `umfCUDAMemoryProviderParamsSetAllocFlags()`
> add support for CUDA allocation flags

- benchmark/CMakeLists.txt
- examples/CMakeLists.txt
- examples/ipc_level_zero/CMakeLists.txt
- examples/level_zero_shared_memory/CMakeLists.txt
- include/umf/base.h
- src/libumf.c
- src/provider/provider_cuda.c
- src/provider/provider_cuda_internal.h
- src/provider/provider_level_zero.c
- src/provider/provider_level_zero_internal.h
- src/utils/utils_level_zero.cpp
- src/utils/utils_load_library.c
- src/utils/utils_load_library.h
- test/CMakeLists.txt
- test/providers/cuda_helpers.cpp
Prior to this PR, the Level Zero provider did not `dlopen(“libze_loader.so”)` at all. We suppose that UMF’s client, who uses Level Zero provider, loaded `libze_loader.so` into the process. But what if there are two clients in the process:
1. The first client loads `libze_loader.so` into the process and uses the Level Zero provider. In that case, UMF inits Level Zero symbols via `dlsym`. Then the first client destroys the Level Zero Memory provider and unloads the `libze_loader.so`.
2. Then the second client loads `libze_loader.so` into the process and uses the Level Zero provider. But our current implementation does not catch such situation and Level Zero symbols are considered initialized, but the `dlsym` should be done again.
This PR fixes that. The UMF acquires handle to the …
> Increase refcount to ze_loader/CUDA libraries when Level Zero/CUDA providers are used

- src/ipc_cache.c
- src/ipc_cache.h
- src/provider/provider_tracking.c
- src/provider/provider_tracking.h
I moved the refactoring part from the #998.
Refactoring of the memory tracker and IPC cache.
Only the names of various variables/functions are changed — no change in the logic.
> Refactoring of the memory tracker and IPC cache

- .github/workflows/reusable_gpu.yml
This avoid writing to the same generate.stamp while building UMF on Windows for L0 during nightly.
> Suppress CMake rerun to prevent  custombuild timestamp error

- CONTRIBUTING.md
- src/libumf.rc.in
- src/proxy_lib/proxy_lib.rc.in
We already have "strings" on Linux, so add similar metadata to dll's rc files.
Describe it a little more in CONTRIBUTING.md
> Add CMake vars to dll's metadata

- src/provider/provider_tracking.c
Clearing the tracker was a temporary solution and should be removed.
The tracker should be cleared using the provider's free() operation.
Replace `clear_tracker_for_the_pool()` with `check_if_tracker_is_empty()`.
This patch reverts commit 2766a21681c1e395d4bcd4c0f178a2627cf56d23
Ref: #759
> Check if tracker is empty instead of clearing it

- benchmark/benchmark.cpp
- benchmark/benchmark.hpp
- benchmark/benchmark_size.hpp
> Improve benchmark stability.

- src/libumf.c
- src/pool/pool_scalable.c
- src/pool/pool_scalable_internal.h
Fixes: https://github.com/oneapi-src/unified-memory-framework/issues/700
> Init TBB symbols only once

- src/pool/pool_scalable.c
Return the `UMF_RESULT_ERROR_DEPENDENCY_UNAVAILABLE` error when loading the TBB symbols failed.
> Return DEPENDENCY_UNAVAILABLE error when loading TBB symbols failed

- benchmark/benchmark.cpp
- benchmark/benchmark_umf.hpp
Fix incorrect bucked size, causing all allocating going to single bucket
> Benchmark improvements

- .github/workflows/reusable_benchmarks.yml
Update location of benchmarking scripts (prev. in UR repo, now in SYCL repo, unified-runtime dir).
> Benchmarks UR repo move

- src/ipc_cache.c
- src/provider/provider_tracking.c
- test/ipcFixtures.hpp
- test/supp/drd-umf_test-provider_devdax_memory_ipc.supp
- test/supp/drd-umf_test-provider_file_memory_ipc.supp
- test/supp/drd-umf_test-provider_os_memory.supp
- test/supp/helgrind-umf_test-provider_devdax_memory_ipc.supp
- test/supp/helgrind-umf_test-provider_file_memory_ipc.supp
- test/supp/helgrind-umf_test-provider_os_memory.supp
This PR fixes data race (found by Coverity) in the umfIpcOpenedCacheDestroy function.
> Fix data race in the umfIpcOpenedCacheDestroy function

- src/coarse/coarse.c
- test/coarse_lib.cpp
Fix `node_list_rm_first()` and `node_list_rm_with_alignment()` in the coarse library.
Add the `coarseTest_basic_non_aligned_fixed_memory` test.
> Fix `node_list_rm_first()` and `node_list_rm_with_alignment()` in the coarse library

- src/pool/pool_disjoint.c
- src/pool/pool_disjoint_internal.h
Fix for calculating the chunk address in the Disjoint Pool when allocating memory with a specified alignment.
Note that in the current Disjoint Pool implementation, the origin of the slab isn't aligned, 
so the chunks don't need to be aligned either (hence, I use the floor() function).
issues for TODOs:
param for disabling poisoning (for GPU provider): https://github.com/oneapi-src/unified-memory-framework/issues/1119
valgrind: https://github.com/oneapi-src/unified-memory-framework/issues/1120
> fix alloc / free aligned chunk address calc in disjoint pool

- benchmark/benchmark.cpp
temporary disable DP MT benchmark
as we observe very sporadic deadlock related to utils_compare_exchange() in the Disjoint Pool
enabling of DP MT benchmark was introduced in https://github.com/oneapi-src/unified-memory-framework/pull/1112
issue: https://github.com/oneapi-src/unified-memory-framework/issues/1125
> temporary disable DP MT benchmark

- test/ipcFixtures.hpp
Add one more concurrent test for IPC Get/Put flow.
> Add concurrent tests for IPC Get/Put functions

- CMakeLists.txt
Disable building and installing the jemalloc's documentation, because it is not needed at all.
Fixes: #1128
> Disable building and installing the jemalloc's documentation

- CMakeLists.txt
Using Unix Makefiles CMake generator on Windows with `hwloc` statically linked results in a build error. Now fetched `hwloc` is explicitly built before `hwloc.lib` is linked with other UMF targets.
// tested [on sycl](https://github.com/intel/llvm/pull/17134) + extended testing
> Fix Windows Unix Makefiles generator builds

- src/pool/pool_disjoint.c
- test/common/pool.hpp
- test/memoryPoolAPI.cpp
- test/poolFixtures.hpp
- test/pools/disjoint_pool.cpp
Implement malloc_usable_size and enable pool tests for disjoint.
> implement malloc_usable_size and enable pool tests for disjoint

- src/provider/provider_tracking.c
Use `LOG_FATAL()` in case of critical errors.
Ref: #1095
> Use `LOG_FATAL()` in case of critical errors

- benchmark/benchmark.cpp
This causes that information about threads count is appended to benchmark name which makes it consistent with other bechmarks.
> explicitly declare single threaded benchmark

- src/coarse/coarse.c
- test/coarse_lib.cpp
Error out in case of double free() instead of assert in coarse library.
> coarse: error out on double free instead of assert

- .github/workflows/reusable_basic.yml
- .github/workflows/reusable_fast.yml
There are some jobs cancelled due to legacy Ubuntu 20.04, so it should be disabled immediately.
Source: https://github.com/oneapi-src/unified-memory-framework/actions/runs/13655322578
> [CI] Disable legacy GHA Image - Ubuntu 20.04

- benchmark/benchmark.cpp
- src/critnib/critnib.c
- src/ipc_cache.c
- src/libumf.c
- src/pool/pool_disjoint.c
- src/pool/pool_disjoint_internal.h
- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- src/provider/provider_tracking.c
- src/utils/utils_common.h
- src/utils/utils_concurrency.h
- src/utils/utils_sanitizers.h
- test/supp/drd-umf_test-disjoint_pool.supp
- test/supp/drd-umf_test-ipc.supp
- test/supp/drd-umf_test-jemalloc_coarse_devdax.supp
- test/supp/drd-umf_test-jemalloc_coarse_file.supp
- test/supp/drd-umf_test-provider_devdax_memory_ipc.supp
- test/supp/drd-umf_test-provider_file_memory_ipc.supp
- test/supp/drd-umf_test-provider_os_memory.supp
- test/supp/helgrind-umf_test-disjoint_pool.supp
- test/supp/helgrind-umf_test-ipc.supp
- test/supp/helgrind-umf_test-jemalloc_coarse_devdax.supp
- test/supp/helgrind-umf_test-jemalloc_coarse_file.supp
- test/supp/helgrind-umf_test-provider_devdax_memory_ipc.supp
- test/supp/helgrind-umf_test-provider_file_memory_ipc.supp
- test/supp/helgrind-umf_test-provider_os_memory.supp
Cleanup atomics and replace while(true) loop in Disjoint Pool bucket_can_pool() with a pair of atomic add/sub.
fix for https://github.com/oneapi-src/unified-memory-framework/issues/1125 and https://github.com/oneapi-src/unified-memory-framework/issues/1115
This PR is required by https://github.com/oneapi-src/unified-memory-framework/pull/1143
> Cleanup atomics and fix deadlock in DP bucket_can_pool()

- .github/workflows/nightly.yml
Test the path of building the static hwloc library with NMake generator.
Nightly passed on fork: https://github.com/PatKamin/unified-memory-framework/actions/runs/13672752528
> Add NMake generator build tests

- src/base_alloc/base_alloc_linux.c
> [CI] Fix failing address sanitizer

- .github/workflows/reusable_basic.yml
Fixes #650 
Example of failing CI when not implemented symbol is added to the `def/map` files: https://github.com/PatKamin/unified-memory-framework/actions/runs/13697316188/job/38302634737
No changes for Windows `cl` compiler required for the linker to raise an error.
> Add lld linker CI job

- .github/workflows/reusable_compatibility.yml
plus minor updates in the workflows, please see each commit for description of the change.
> Extend compatibility tests with GPU runners

- .github/workflows/reusable_compatibility.yml
Run Compatibility GPU CI jobs only on upstream,
since forks do not have the required HW.
> Run Compatibility GPU CI jobs only on upstream

- include/umf/base.h
- src/critnib/critnib.c
- src/provider/provider_tracking.c
- src/utils/utils_concurrency.h
- test/CMakeLists.txt
- test/poolFixtures.hpp
- test/provider_fixed_memory.cpp
- test/provider_tracking.cpp
- test/provider_tracking_fixture_tests.cpp
Use eight level of critnibs in the tracker.
Multilevel maps are needed to support the case
when one memory pool acts as a memory provider
for another memory pool (nested memory pooling).
Depends on:
Requires:
> Use eight level of critnibs in the tracker

- .github/workflows/reusable_benchmarks.yml
We moved on to new Ubuntu and it does not allow global pip installation - just use venv.
// https://github.com/oneapi-src/unified-memory-framework/actions/runs/13788400307/job/38561764479?pr=1178
> [CI] Use venv for pip installation in benchmarks

- src/provider/provider_tracking.c
this is a fix for Coverity issue:
https://scan3.scan.coverity.com/#/project-view/65229/15141?selectedIssue=477771
> fix for potential out-of-bounds read in tracker

- benchmark/benchmark.hpp
- benchmark/benchmark_umf.hpp
- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- src/utils/utils_concurrency.h
> add memusage stat to os_provider and use it in benchmarks

- src/provider/provider_cuda.c
Handle `CUDA_ERROR_DEINITIALIZED` error in `cu2umf_result()`.
> Handle `CUDA_ERROR_DEINITIALIZED` error in `cu2umf_result()`

- src/provider/provider_cuda.c
Fix segfault in `cu_memory_provider_get_last_native_error()` when it is called after a CUDA device was destroyed.
> Fix segfault in `cu_memory_provider_get_last_native_error()`

- include/umf/providers/provider_cuda.h
- src/provider/provider_cuda.c
- test/providers/cuda_helpers.cpp
- test/providers/cuda_helpers.h
- test/providers/provider_cuda.cpp
use the current ctx and dev by default in the CUDA provider 
implements https://github.com/oneapi-src/unified-memory-framework/issues/1171
> use current ctx and dev by default in CUDA prov

- .github/workflows/reusable_benchmarks.yml
> update benchmark scripts

- test/pools/jemalloc_pool.cpp
Enable jemalloc pool test with Fixed provider.
> Enable jemalloc pool test with Fixed provider

- .github/workflows/reusable_proxy_lib.yml
Install libnuma-dev in the proxy lib workflow,
because it is required.
It has worked correctly so far most probably,
because libnuma-dev has been installed
as a dependency of libhwloc-dev.
It failed when libhwloc-dev was not installed:
https://github.com/oneapi-src/unified-memory-framework/actions/runs/13895067500/job/38875043512
> Install libnuma-dev in the proxy lib workflow

- test/ipc_file_prov.sh
Remove old SHM files `/tmp/umf_file_provider_*`
(at the beginning of the test)
left from the previous runs, because of crashes
of the `ipc_file_prov` test.
> Remove old SHM files left from the previous runs because of crashes

- benchmark/benchmark.cpp
> fix jemalloc benchmark with fixedprovider

- .github/workflows/reusable_benchmarks.yml
- benchmark/benchmark.cpp
> increase number of threads in benchmarks

- benchmark/benchmark.cpp
Simplify benchmark tests by removing redundant pool benchmarks for fixed provider, as results are nearly identical to os provider. Also reduce iteration count for 'fix' provider benchmarks to match with 'os' provider.
> remove pool benchmarks with fixed provider.

- .github/scripts/get_system_info.sh
on new Ubuntu `level-zero` packages are renamed to `libze`. Extend this part and finding gpu.
> [CI] Minor update in get_system_info.sh

- .github/workflows/benchmarks.yml
- .github/workflows/nightly.yml
- .github/workflows/reusable_benchmarks.yml
- .github/workflows/reusable_docs_build.yml
incl. using new format of data (stored on '[benchmark-results](https://github.com/oneapi-src/unified-memory-framework/tree/benchmark-results)' branch).
// Preview:
Job passed: https://github.com/oneapi-src/unified-memory-framework/actions/runs/13971793856/job/39115241536
New dashboard: https://oneapi-src.github.io/unified-memory-framework/performance/?notes=true&unstable=false
Results: https://github.com/oneapi-src/unified-memory-framework/tree/benchmark-results
> [CI][Bench] Use new version of bench dashboard

- .github/workflows/nightly.yml
- .github/workflows/reusable_sycl.yml
Add a nightly workflow that runs intel/llvm tests with the latest umf library.
Workflow run: https://github.com/oneapi-src/unified-memory-framework/actions/runs/13991023696
> Sycl nightly workflow

- src/pool/pool_disjoint.c
fix warning when building UMF in sycl:
/home/rrudnick/llvm/build/_deps/unified-memory-framework-src/src/pool/pool_disjoint.c:968:33: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
968 |     static char *DEFAULT_NAME = "disjoint_pool";
|                                 ^~~~~~~~~~~~~~~
> fix "discard ‘const’ qualifier" warning in disjoint pool

- .github/workflows/benchmarks.yml
- .github/workflows/coverity.yml
- .github/workflows/reusable_benchmarks.yml
- scripts/qemu/requirements.txt
Each commit with its own fix/change.
Most importantly - update the tokens to the least privileged ones by default.
> Small fixes around CI

- benchmark/benchmark_umf.hpp
- src/ctl/ctl.c
- src/provider/provider_ctl_stats_impl.h
- src/provider/provider_ctl_stats_type.h
- src/provider/provider_fixed_memory.c
- src/provider/provider_os_memory.c
- src/provider/provider_os_memory_internal.h
- src/utils/utils_concurrency.h
> add ctl to fixed provider

- .github/workflows/reusable_basic.yml
- CMakeLists.txt
- test/test_installation.py
Always install debug libraries on Windows. Introduce new CMake option `UMF_USE_DEBUG_POSTFIX` for adding a "d" postfix to debug libraries names.
These changes are required for https://github.com/intel/llvm/pull/17512.
> Install debug libraries on Windows

- .github/workflows/nightly.yml
- .github/workflows/reusable_basic.yml
- .github/workflows/reusable_codeql.yml
- .github/workflows/reusable_compatibility.yml
- .github/workflows/reusable_fast.yml
- .github/workflows/reusable_gpu.yml
- .github/workflows/reusable_sanitizers.yml
Fixes vcpkg tbb installation error on the latest Windows runners with CMake 2.31 installed:
```
Building tbb[core,hwloc]:x64-windows@2021.11.0...
-- Downloading https://github.com/oneapi-src/oneTBB/archive/v2021.11.0.tar.gz -> oneapi-src-oneTBB-v2021.11.0.tar.gz...
-- Extracting source D:/a/unified-memory-framework/unified-memory-framework/build/vcpkg/downloads/oneapi-src-oneTBB-v2021.11.0.tar.gz
-- Using source at D:/a/unified-memory-framework/unified-memory-framework/build/vcpkg/buildtrees/tbb/src/v2021.11.0-0163f51d5f.clean
CMake Warning (dev) at scripts/cmake/vcpkg_find_acquire_program.cmake:70 (cmake_parse_arguments):
The INTERPRETER keyword was followed by an empty string or no value at all.
Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
arg_INTERPRETER …
```
> Fix vcpkg tbb installation

- .github/workflows/reusable_compatibility.yml
- examples/basic/basic.c
- examples/custom_file_provider/custom_file_provider.c
- examples/dram_and_fsdax/dram_and_fsdax.c
- examples/ipc_level_zero/ipc_level_zero.c
- examples/memspace_numa/memspace_numa.c
in the Compatibility workflow:
* browse all folders in the examples directory, 
* build them using the latest UMF version (installed)
* run them, excluding those in the exclude list
> Add compatibility testing for compilation based on examples

- CMakeLists.txt
Check for `autoreconf` prerequisite in case hwloc is fetched from sources.
> Check for autoreconf prerequisite in case hwloc is fetched from sources

- benchmark/benchmark.cpp
- benchmark/benchmark.hpp
> fix false sharing issue in benchmark

- .github/workflows/pr_push.yml
- .github/workflows/reusable_compatibility.yml
- src/libumf.def
- src/libumf.map
Update the compatibility workflow tags to v0.11.0-rc1 and remove filters for tests that are not compatible.
> update compat wflow tag and remove filters

- .github/workflows/reusable_sycl.yml
Sycl compatibility tests are failing after the recent removal of the `umfMemoryTrackerGetAllocInfo` symbol (#1235) form the `.map` file:
```
<LOADER>[INFO]: failed to load adapter 'libur_adapter_level_zero.so.0' with error: llvm/lib/libur_adapter_level_zero.so.0: undefined symbol: umfMemoryTrackerGetAllocInfo, version UMF_0.10
```
Update legacy sycl version used in CI to one that is built with UMF with Disjoint Pool being a part of libumf library.
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14328678325/job/40159432929?pr=1243
> Bump legacy sycl

- src/provider/provider_level_zero.c
In case of error in the init function, cleanup was being called on 'provider' which was being initialized at the very end of init function, instead of 'ze_provider'.
> L0 provider: fix initialization

- benchmark/benchmark.cpp
- benchmark/benchmark.hpp
Changed existing workload to include multiple alloc/free in the row. 
Added workload that firstly increases number of allocations, and decreases it.
> benchmark workload redesign

- src/provider/provider_file_memory.c
- test/poolFixtures.hpp
Fix file_alloc_aligned() and add the allocFreeAligned test to poolFixtures.hpp.
> Fix file_alloc_aligned() and add the allocFreeAligned test to poolFixtures.hpp

- src/provider/provider_tracking.c
We do not need to allocate a new `splitValue`, update critnib using `critnib_insert()` in the update mode and free the old value. It is enough to just update atomically the size of the first part:
```c
utils_atomic_store_release_u64((uint64_t *)&value->size, firstSize);
```
Also add missing `umfMemoryProviderAllocationMerge()` call in the error handling path.
Fixes: #1244
> Simplify and improve `trackingAllocationSplit()`

- src/provider/provider_tracking.c
We do not need to allocate a new `mergedValue`, update critnib using `critnib_insert()` in the update mode and free the old value. It is enough to just update atomically the size of the first part:
```c
utils_atomic_store_release_u64((uint64_t *)&lowValue->size, totalSize);
```
The tracker entries cannot be merged if they are used (if they have children).
> Simplify and improve `trackingAllocationMerge()`

- benchmark/benchmark.hpp
> disable fragmentation output for peak benchmark

- .github/workflows/.spellcheck-conf.toml
- .github/workflows/reusable_checks.yml
- docs/config/Doxyfile
- src/coarse/coarse.c
- test/malloc_compliance_tests.cpp
- test/provider_devdax_memory.cpp
update CI crate-ci/typos action and fix typos
needed by https://github.com/oneapi-src/unified-memory-framework/pull/1255
> update CI crate-ci/typos action and fix typos

- .github/workflows/reusable_basic.yml
- .github/workflows/reusable_compatibility.yml
Get rid of the hwloc installation script runs in CI. Save ca. 25s in each of 14 jobs using this script.
> [CI] Install hwloc from apt instead of building from sources

- .github/workflows/reusable_benchmarks.yml
- .github/workflows/reusable_docs_build.yml
Fix error:
AttributeError: module 'urllib' has no attribute 'request'
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14484406113/job/40632616006 
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14486798844/job/40633929266?pr=1274
> [CI] Update benchmarks

- .github/workflows/nightly.yml
- CMakeLists.txt
- test/test_installation.py
and add installation tests step to Windows generators nightly tests
Nightly passed: https://github.com/PatKamin/unified-memory-framework/actions/runs/14398856014
> Fix building umfd.dll on single-config generators

- .github/workflows/docs_pr_push.yml
- .github/workflows/pr_push.yml
Oftentimes pushes to branches and PRs doesn't change anything in docs/ or include/ directories which influence the documentation build. This job takes ca. 1 minute to run with each push, so it's optimal to run it only when relevant changes were made.
Also, there is no need for other pr_push jobs to wait for docs to build. Developer can work on the docs and project build/tests in any order.
> [CI] Run DocsBuild only when needed

- .github/workflows/reusable_basic.yml
- .github/workflows/reusable_codeql.yml
- .github/workflows/reusable_dax.yml
- .github/workflows/reusable_fast.yml
- .github/workflows/reusable_gpu.yml
- .github/workflows/reusable_proxy_lib.yml
- .github/workflows/reusable_sanitizers.yml
Dir outside of the workspace can't be cleaned in cases of non-stateless runners.
// example of failing job: https://github.com/luszczewskakasia1/unified-memory-framework/actions/runs/14466409232/job/40570259829
// that happened on a machine, when user can't access the `..`
> [CI] Use install dir path within workspace

- CMakeLists.txt
- examples/ipc_level_zero/CMakeLists.txt
- examples/level_zero_shared_memory/CMakeLists.txt
Bump to the latest L0 release. SYCL repo is already using it, with success 😉
> [CMake] Bump L0 version to latest - v1.21.9

- src/memspaces/memspace_highest_bandwidth.c
- src/memspaces/memspace_lowest_latency.c
- src/memtargets/memtarget_numa.c
They are misleadingly read as errors, while they are simply debug information that these targets aren't accessible on a machine.
> Downgrade error logs to debug in memspaces and memtargets

- CMakeLists.txt
- README.md
- test/CMakeLists.txt
update the documentation and fail CMake if the fuzz tests are enabled but their requirements (Clang and Linux) are not met.
fixes https://github.com/oneapi-src/unified-memory-framework/issues/1267
> update doc and fail if fuzz tests reqs are not met

- src/coarse/coarse.c
Improve `coarse_alloc()`: move the code responsible for handling the `(curr == NULL)` case just after `curr = find_free_block()`. Add `coarse_add_free_block()`.
Now (before this change) when a user calls `coarse_alloc(1, 2MB)` (allocate 1 byte with 2MB alignment) and there is no suitable blok inside the coarse allocator, a new block is allocated from the provider of size `coarse->page_size` at least, but it is added to the inner lists with the requested size of only 1 byte and the rest of space will not be able to be utilized.
After this change, when a user calls `coarse_alloc(1, 2MB)` (allocate 1 byte with 2MB alignment) and there is no suitable blok inside the coarse allocator, a new block is allocated from the provider of size `alignment` (>= `coarse->page_size`) and it is added to the …
> Improve `coarse_alloc()`

- .github/workflows/nightly.yml
- CMakeLists.txt
- README.md
Link with the Clang static fuzzer library, libclang_rt.fuzzer_no_main-x86_64, if UMF_BUILD_FUZZTESTS is set. 
Additionally, run extra tests in the nightly workflow that would fail without this change.
Successful run: https://github.com/oneapi-src/unified-memory-framework/actions/runs/14704118968/job/41260044056?pr=1284
```
-- Found fuzzer lib: /usr/lib/llvm-17/lib/clang/17/lib/linux/libclang_rt.fuzzer_no_main-x86_64.a
...
-- Fuzzing tests enabled.
```
Fixes: https://github.com/oneapi-src/unified-memory-framework/issues/590
> link with Clang static fuzzer lib if UMF_BUILD_FUZZTESTS is set

- .github/workflows/reusable_benchmarks.yml
All steps should be able to use the packages installed via venv.
// Fixing e.g. https://github.com/oneapi-src/unified-memory-framework/actions/runs/14616987712/job/41010729651?pr=1284
// `ModuleNotFoundError: No module named 'dataclasses_json'` found in "Commit data.json and results directory" step.
Preview: [link](https://github.com/oneapi-src/unified-memory-framework/actions/runs/14756725275/job/41426780573?pr=1293)
// while the run is still red, it's not because of missing package (on PR, the bot's token is not capable of writing stuff)
> [CI] Add pip's venv into PATH in benchmarks' workflow

- src/memory_pool.c
- src/memory_provider.c
cherry-pick https://github.com/oneapi-src/unified-memory-framework/pull/1296 to stable v0.11.x
> [v0.11.x] Check global state destruction in destructors

- src/memspaces/memspace_highest_bandwidth.c
- src/memspaces/memspace_lowest_latency.c
- src/memtargets/memtarget_numa.c
Cherry pick of https://github.com/oneapi-src/unified-memory-framework/pull/1287 into stable v0.11.x
> [v0.11.x] Downgrade error logs to debug in memspaces and memtargets

- .github/workflows/reusable_basic.yml
- CMakeLists.txt
- benchmark/CMakeLists.txt
- cmake/FindCUDA.cmake
- cmake/FindZE_LOADER.cmake
- examples/CMakeLists.txt
- examples/cmake/FindZE_LOADER.cmake
- examples/cuda_shared_memory/CMakeLists.txt
- examples/ipc_level_zero/CMakeLists.txt
- examples/level_zero_shared_memory/CMakeLists.txt
- test/CMakeLists.txt
- test/test_installation.py
Never build and install ze_loader by using FetchContent_Populate instead of MakeAvailable. After this change, we have to find ze_loader installed on the system instead of using the one built by us. 
Additionally, add testing cmake 3.14, which is the oldest supported version by UMF.
Example of failed installation/deinstallation test (requires using CMake 3.14.0):
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14692346477/job/41229764121?pr=1285
fixes: https://github.com/oneapi-src/unified-memory-framework/issues/1110
> do not install libze_loader

- .github/workflows/reusable_basic.yml
- CMakeLists.txt
- examples/cuda_shared_memory/CMakeLists.txt
Starting with CMake 3.30, FetchContent_Populate is deprecated. It can be replaced by FetchContent_Declare(... EXCLUDE_FROM_ALL) + FetchContent_MakeAvailable(). However, the EXCLUDE_FROM_ALL flag is available only from CMake 3.28 
This pull request checks the CMake version, and for versions <= 3.28, we use FetchContent_Populate, and for later versions, we use EXCLUDE_FROM_ALL + FetchContent_MakeAvailable.
example logs with different CMake versions:
CMake 3.14.0
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14906699261/job/41871908648?pr=1300
CMake 3.29.0
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14906699261/job/41871908635?pr=1300
CMake latest (3.31.6)
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14906699261/job/41871908 …
> do not use FetchContent_Populate in CMake >= 3.28

- .github/workflows/reusable_valgrind.yml
- test/test_valgrind.sh
Move the longest drd tests to Nightly build (in seconds):
```
1834.73user ./test/test_jemalloc_pool
389.64user  ./test/test_jemalloc_coarse_file
294.00user  ./test/test_scalable_pool
208.11user  ./test/test_ipc_max_opened_limit
```
and in minutes:
```
30,57 min ./test/test_jemalloc_pool
6,49 min ./test/test_jemalloc_coarse_file
4,90 min ./test/test_scalable_pool
3,47 min ./test/test_ipc_max_opened_limit
```
Add the **drdshort** option to the valgrind script.
It decreases time of the drd test from 48 minutes to less than 7 minutes.
Duration of the valgrind jobs on **the current main branch**:
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14930807298/job/41949432868
Duration of the valgrind jobs **with this change**: …
> Move the longest drd tests to Nightly build

- CMakeLists.txt
Ref. https://github.com/oneapi-src/unified-memory-framework/pull/1228
In the next minor release (v0.12.0 ), the `UMF_DISABLE_HWLOC ` option in CMake will be removed.
> [CMake] Warn about UMF_DISABLE_HWLOC being deprecated

- src/memtargets/memtarget_numa.c
physical_id field stores os index, so we should use correct function to get hwloc numanode object.
fixes: #1289
> retrieve numanode object by os index instead of logical index.

- test/ipcFixtures.hpp
Add assert in the `ConcurrentDestroyIpcHandlers` test.
> Add assert in the `ConcurrentDestroyIpcHandlers` test

- .github/workflows/reusable_gpu.yml
Rather instead of hard-coding a path from the machine, use env var available in the system.
> [CI] Use extra param to set CUDA_PATH in gpu workflow

- .github/workflows/reusable_gpu.yml
- ChangeLog
- src/memtargets/memtarget_numa.c
Deliveres into main:
- v0.11.2
- #1312 
- #1309
> Merge v0.11.x into main

- src/CMakeLists.txt
- src/provider/provider_cuda.c
- src/provider/provider_level_zero.c
So far, we have two sets of mutually exclusive compilation definitions in our CMake:
- UMF_NO_LEVEL_ZERO_PROVIDER
- UMF_NO_CUDA_PROVIDER
- UMF_NO_DEVDAX_PROVIDER
- UMF_NO_FILE_PROVIDER
and:
- UMF_BUILD_LEVEL_ZERO_PROVIDER
- UMF_BUILD_CUDA_PROVIDER
This PR removes the UMF_BUILD_NO_* definitions. Also, note that UMF_NO_DEVDAX_PROVIDER and UMF_NO_FILE_PROVIDER were never used.
> remove unused UMF_NO_*_PROVIDER compile defs

- .github/workflows/nightly.yml
- .github/workflows/reusable_benchmarks.yml
Add a sycl benchmark script run as an additional sycl compatibility test
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14924558080/job/41926374789
> Add sycl benchmark to sycl compatibility workflow

- .github/workflows/benchmarks.yml
- .github/workflows/nightly.yml
- .github/workflows/reusable_benchmarks.yml
- .github/workflows/reusable_sycl.yml
Includes update for nightly sycl build, to avoid: https://github.com/oneapi-src/unified-memory-framework/actions/runs/15104034834/job/42449512722#step:3:12
The issue above was caused by a sycl release, which:
- uses different file name with sycl release, and
- has the codebase from November, expecting different UMF version.
\
// preview of nightly job: https://github.com/oneapi-src/unified-memory-framework/actions/runs/15116081326?pr=1321
> Minor CI changes

- .github/workflows/nightly_looped_sanitizers.yml
Add nightly CI job with looped sanitizers.
Check code with looped compilers' sanitizers.
This build lasts 6 hours.
CI build on main: https://github.com/ldorau/unified-memory-framework/actions/runs/15131922921
CI build on top of #1270: https://github.com/ldorau/unified-memory-framework/actions/runs/15131992304
> CI: add nightly CI job with looped sanitizers

- .github/workflows/reusable_basic.yml
- test/CMakeLists.txt
- test/coarse_lib.cpp
- test/ipcFixtures.hpp
- test/memoryPoolAPI.cpp
- test/memoryProviderAPI.cpp
- test/pools/disjoint_pool.cpp
- test/test_base_alloc_linear.cpp
- test/test_installation.py
This is a fix for the failing test_installation.py on Windows, introduced by #1285. The failures are related to the `--target install` command, which is not properly recognized on Windows. This pull request reverts the installation command to the previous version, which uses `--install` for Windows.
example of passed Windows Ninja job:
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14972212328/job/42055589833?pr=1310
and Windows NMake job:
https://github.com/oneapi-src/unified-memory-framework/actions/runs/14972212328/job/42055589878?pr=1310
full nightly run:
https://github.com/oneapi-src/unified-memory-framework/actions/runs/15117728112
> use --install in installation tests on Windows

- .github/workflows/nightly.yml
Bump the latest (non-LTS) Ubuntu version in QEMU CI job.
// Preview on my fork: https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/15184572304/job/42701871803
> [CI][QEMU] Bump latest Ubuntu version used

- .github/workflows/nightly.yml
- .github/workflows/reusable_basic.yml
- .github/workflows/reusable_dax.yml
- .github/workflows/reusable_fast.yml
- .github/workflows/reusable_gpu.yml
- .github/workflows/reusable_multi_numa.yml
- .github/workflows/reusable_proxy_lib.yml
- .github/workflows/reusable_qemu.yml
- .github/workflows/reusable_sanitizers.yml
Add details to workflow job names
> Add details to workflow job names

- .github/workflows/nightly.yml
- .github/workflows/reusable_multi_numa.yml
- src/base_alloc/base_alloc_global.c
- src/provider/provider_tracking.c
This PR ensures the global base allocator’s destroyed flag is reset on creation and re-enables the test_init_teardown in CI.
- Reset ba_is_destroyed to false in umf_ba_create_global
- Add and adjust debug logs in the memory tracker and base allocator
- Remove exclusion of test_init_teardown from CI workflows
> reset BA destroy flag on BA create

- .github/workflows/reusable_qemu.yml
- test/memspaces/memspace_numa.cpp
Fix checking the number of targets in the memspace CapacityFilter test.
Additionally, test the 8-socket config in the short run suite.
> Fix checking num of targets in memspace CapacityFilter test

- src/memspaces/memspace_highest_bandwidth.c
- src/memspaces/memspace_lowest_latency.c
// found in https://github.com/oneapi-src/unified-memory-framework/pull/1287
> Remove redundant asserts in umfMemspace*Init

- benchmark/benchmark_umf.hpp
- include/umf/base.h
- include/umf/memory_pool.h
- include/umf/memory_pool_ops.h
- include/umf/memory_provider_ops.h
- src/ctl/ctl.c
- src/ctl/ctl.h
- src/libumf.c
- src/libumf.def
- src/libumf.map
- src/memory_pool.c
- src/memory_provider.c
- src/pool/pool_disjoint.c
- src/pool/pool_scalable.c
- src/provider/provider_ctl_stats_impl.h
- src/provider/provider_fixed_memory.c
- src/provider/provider_os_memory.c
- test/CMakeLists.txt
- test/ctl/ctl_api.cpp
- test/ctl/ctl_debug.c
- test/ctl/ctl_unittest.cpp
- test/pools/disjoint_pool.cpp
- test/pools/disjoint_pool_ctl.cpp
- test/pools/scalable_pool.cpp
> [CTL] Add support for defaults

- src/base_alloc/base_alloc.c
- src/coarse/coarse.c
Expensive debug checks are under the ifdef from now:
```
#if !defined(NDEBUG) && defined(UMF_DEVELOPER_MODE)
```
Fixes: #1325
> Disable expensive debug checks

- src/provider/provider_level_zero.c
This PR fixes following error:
```
provider_level_zero.c
Running Code Analysis for C/C++...
9>C:\actions-runner\_work\unified-memory-framework\unified-memory-framework\src\provider\provider_level_zero.c(347,10): error C2220: the following warning is treated as an error [C:\actions-runner\_work\unified-memory-framework\unified-memory-framework\build\src\umf.vcxproj]
9>C:\actions-runner\_work\unified-memory-framework\unified-memory-framework\src\provider\provider_level_zero.c(347,10): warning C5286: implicit conversion from enum type 'umf_usm_memory_type_t' to enum type '_ze_memory_type_t'; use an explicit cast to silence this warning [C:\actions-runner\_work\unified-memory-framework\unified-memory-framework\build\src\umf.vcxproj]
C:\actions-runner\_work\unified-memory-framework\unified-memo …
```
> Fix implicit cast between ze and usm enums

- src/provider/provider_devdax_memory.c
- src/provider/provider_file_memory.c
error: ‘__builtin_strncpy’ output may be truncated copying 4095 bytes from a string of length 4095 [-Werror=stringop-truncation]
> fix __builtin_strncpy truncated compilation error

- test/supp/drd-test_disjoint_pool.supp
- test/supp/drd-test_jemalloc_coarse_devdax.supp
- test/supp/drd-test_jemalloc_coarse_file.supp
- test/supp/helgrind-test_disjoint_pool.supp
- test/supp/helgrind-test_ipc.supp
- test/supp/helgrind-test_ipc_max_opened_limit.supp
- test/supp/helgrind-test_jemalloc_coarse_devdax.supp
- test/supp/helgrind-test_jemalloc_coarse_file.supp
- test/supp/helgrind-test_provider_file_memory_ipc.supp
> Remove all valgrind suppressions for critnib

- test/supp/drd-test_ipc.supp
- test/supp/drd-test_ipc_max_opened_limit.supp
Add missing suppressions for utils_atomic_store_release_ptr() in upstreamOpenIPCHandle().
There should be both suppressions: for utils_atomic_load_acquire_ptr() and
for utils_atomic_store_release_ptr() in each suppression file.
The Nightly build:
https://github.com/oneapi-src/unified-memory-framework/actions/runs/15526531980/job/43707269456
failed because this suppression was missing.
> Add missing suppressions for upstreamOpenIPCHandle()

- README.md
> Fix grammar issues in readme

- src/provider/provider_os_memory.c
> return correct error code in create_fd_for_mmap

- .github/workflows/reusable_sanitizers.yml
Enable L0 provider in Sanitizers build on Windows.
> Enable L0 provider in Sanitizers build on Windows

- src/libumf_windows.c
// Failing nightly CI: https://github.com/oneapi-src/unified-memory-framework/actions/runs/15989654467/job/45100430704
> fix incompatible function pointer on windows

- examples/ipc_level_zero/ipc_level_zero.c
- include/umf/pools/pool_disjoint.h
- src/pool/pool_disjoint.c
- src/pool/pool_disjoint_internal.h
- test/pools/disjoint_pool.cpp
fixes https://github.com/oneapi-src/unified-memory-framework/issues/804
> [disjoint] Set default parameters for disjoint pool

- CMakeLists.txt
We only require source files.
It fixes the nigthly build.
// fail: https://github.com/oneapi-src/unified-memory-framework/actions/runs/15989654467/job/45100430665
// after fixes: https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/16003100695/job/45142932077
> [CMake] Don't configure and build L0 loader

- include/umf/base.h
- include/umf/memory_pool_ops.h
- src/memory_pool.c
- src/pool/pool_disjoint.c
- src/pool/pool_jemalloc.c
- src/pool/pool_proxy.c
- src/pool/pool_scalable.c
- test/common/pool_null.c
- test/common/pool_trace.c
- test/utils/cpp_helpers.hpp
> Unexperiment pool get name

- src/base_alloc/base_alloc_global.c
- src/base_alloc/base_alloc_linear.c
- src/pool/pool_disjoint.c
- test/coarse_lib.cpp
> add valgrind support in base allocator

- benchmark/benchmark_umf.hpp
- examples/dram_and_fsdax/dram_and_fsdax.c
- include/umf/providers/provider_devdax_memory.h
- include/umf/providers/provider_file_memory.h
- include/umf/providers/provider_fixed_memory.h
- include/umf/providers/provider_os_memory.h
- src/provider/provider_devdax_memory.c
- src/provider/provider_file_memory.c
- src/provider/provider_fixed_memory.c
- test/ctl/ctl_api.cpp
- test/disjoint_pool_file_prov.cpp
- test/ipc_devdax_prov_consumer.c
- test/ipc_devdax_prov_producer.c
- test/ipc_file_prov_consumer.c
- test/ipc_file_prov_producer.c
- test/poolFixtures.hpp
- test/pools/jemalloc_coarse_devdax.cpp
- test/pools/jemalloc_coarse_file.cpp
- test/pools/jemalloc_pool.cpp
- test/pools/scalable_coarse_devdax.cpp
- test/pools/scalable_coarse_file.cpp
- test/provider_devdax_memory.cpp
- test/provider_devdax_memory_ipc.cpp
- test/provider_devdax_memory_not_impl.cpp
- test/provider_file_memory.cpp
- test/provider_file_memory_ipc.cpp
- test/provider_file_memory_not_impl.cpp
- test/provider_fixed_memory.cpp
- test/provider_tracking.cpp
- test/provider_tracking_fixture_tests.cpp
> ensure that out paramenter is last function argument

- docs/config/examples.rst
- src/memory_provider.c
- src/pool/pool_scalable.c
- src/provider/provider_os_memory.c
- src/utils/utils_log.c
- test/common/test_helpers.c
- test/fuzz/utils.hpp
- test/malloc_compliance_tests.cpp
- test/malloc_compliance_tests.hpp
- test/pools/jemalloc_coarse_devdax.cpp
- test/pools/jemalloc_coarse_file.cpp
- test/pools/jemalloc_pool.cpp
- test/pools/pool_base_alloc.cpp
- test/pools/scalable_coarse_devdax.cpp
- test/pools/scalable_coarse_file.cpp
- test/pools/scalable_pool.cpp
> use correct includes brackets

- src/base_alloc/base_alloc_global.c
Add comments about redundant annotations.
> Add comments about redundant annotations

- src/critnib/critnib.c
Do not use the value field as a next pointer,
because it sometimes can lead to race conditions
and reusing already used leaves like here:
https://github.com/ldorau/unified-memory-framework/actions/runs/16074523240/job/45366469415
> Fix: do not use the value field as a next pointer

- include/umf/providers/provider_cuda.h
- include/umf/providers/provider_level_zero.h
- src/ctl/ctl.c
- src/ctl/ctl_internal.h
- src/memory_pool.c
- src/memory_provider_internal.h
- src/pool/pool_disjoint.c
- src/pool/pool_scalable.c
- src/pool/pool_scalable_internal.h
- src/provider/provider_ctl_stats_impl.h
- src/provider/provider_ctl_stats_type.h
- src/provider/provider_cuda_internal.h
- src/provider/provider_level_zero_internal.h
- src/provider/provider_os_memory.c
- test/ctl/ctl_debug.h
- test/ctl/ctl_unittest.cpp
and clean up header guards in several header files.
> Rename ctl internal header file

- test/memoryPoolAPI.cpp
- test/poolFixtures.hpp
- test/pools/jemalloc_pool.cpp
> improve umfPoolGetName tests

- .github/workflows/reusable_sycl.yml
update CI sycl tag to nightly-2025-07-09 (UMF v1.0.0-rc1)
passing Nightly / SYCL / nightly-2025-07-09 llvm build (pull_request):
https://github.com/oneapi-src/unified-memory-framework/actions/runs/16168352316/job/45635473006?pr=1425
> update CI sycl tag to nightly-2025-07-09 (UMF v1.0.0-rc1)

- .github/docker/ubuntu-20.04.Dockerfile
- .github/docker/ubuntu-22.04.Dockerfile
- .github/docker/ubuntu-24.04.Dockerfile
A few minor changes in dockers - see commits descriptions.
// as for pkg-config change, compare example jobs:
- https://github.com/oneapi-src/unified-memory-framework/actions/runs/16190993375/job/45707919221#step:9:26
- https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/16192506967/job/45711323543#step:9:23
This way we can test both approaches to finding hwloc in the system.
> [CI] Dockers minor changes

- test/common/pool.hpp
- test/pools/pool_base_alloc.cpp
- test/utils/cpp_helpers.hpp
> improve pool ops tests

- src/provider/provider_level_zero.c
> Add CTL handler to level zero provider

- .github/workflows/pr_push.yml
- src/libumf.def
- src/libumf.map
Also, clean up libumf.map and .def files a little - fix the A-Z order of symbols
> Update libumf.map file to only have 1.0 section

- src/pool/pool_disjoint.c
- test/ctl/ctl_api.cpp
- test/pools/disjoint_pool_ctl.cpp
> [disjoint] Add CTL memory used/reserved metrics

- .github/workflows/reusable_basic.yml
quiet brew install up-to-date warnings
Basic builds / Basic (macos-13, static_hwloc=OFF)
hwloc 2.12.1 is already installed and up-to-date. To reinstall 2.12.1, run: brew reinstall hwloc
Basic builds / Basic (macos-13, static_hwloc=OFF)
libtool 2.5.4 is already installed and up-to-date. To reinstall 2.5.4, run: brew reinstall libtool
> quiet brew install up-to-date warnings

- src/memory_provider.c
- src/utils/utils_assert.h
- src/utils/utils_common.h
improve error handling in Memory Provider API
> improve error handling in Memory Provider API

- src/provider/provider_cuda.c
- src/provider/provider_devdax_memory.c
- src/provider/provider_file_memory.c
- src/provider/provider_level_zero.c
- test/provider_devdax_memory.cpp
- test/provider_file_memory.cpp
- test/provider_fixed_memory.cpp
- test/provider_os_memory.cpp
- test/providers/provider_cuda.cpp
- test/providers/provider_level_zero.cpp
> add ctl_stats to remaining providers

- CMakeLists.txt
ref. #1228 - merged on main - we'll be removed in the next UMF version -- 0.12 is not planned.
> [CMake] Update deprecated msg for hwloc option

- .github/workflows/reusable_codeql.yml
CodeQL caching seem to have no effect on the speed, but it takes quite a lot of our cache storage space.
// no step "upload TRAP cache..." https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/16369095173/job/46253062138#step:11:479
> [CI] Don't use trap caching in CodeQL job

- src/ctl/ctl.c
- src/ctl/ctl_internal.h
- src/libumf.c
- src/memory_pool.c
- src/utils/CMakeLists.txt
- src/utils/utils_log.c
- src/utils/utils_log.h
- test/CMakeLists.txt
- test/ctl/ctl_api.cpp
- test/ctl/ctl_debug.c
- test/utils/utils_log.cpp
> control logger thru CTL

- test/memoryPoolAPI.cpp
Add Jemalloc pool to mallocPoolTest suite.
Fixes: #1455
> Add Jemalloc pool to mallocPoolTest suite

- src/memory_pool.c
- test/poolFixtures.hpp
Check for null pointer dereference in `umfPoolDestroy()`.
> Check for null pointer dereference in umfPoolDestroy()

- test/poolFixtures.hpp
Add assert in `poolCreateExtUnique()` after `EXPECT_*()`.
> Add assert in `poolCreateExtUnique()` after `EXPECT_*()`

- .github/workflows/nightly.yml
- .github/workflows/reusable_benchmarks.yml
- .github/workflows/reusable_docs_build.yml
- .github/workflows/reusable_sycl.yml
// Fixes for failing nightly: https://github.com/oneapi-src/unified-memory-framework/actions/runs/16434451427/job/46454015453
Preview of passing CI: https://github.com/oneapi-src/unified-memory-framework/actions/runs/16498775053
> [CI] SYCL updates

- src/libumf.c
- src/memspaces/memspace_host_all.c
- src/memtargets/memtarget_numa.c
- src/provider/provider_os_memory.c
- src/topology.c
- src/topology.h
> make topology_init faster

- src/ctl/ctl.c
- src/ctl/ctl_internal.h
- src/libumf.c
- src/memory_pool.c
- src/memory_pool_internal.h
- test/CMakeLists.txt
- test/ctl/ctl_env_app.cpp
- test/ctl/ctl_env_config1.cfg
- test/ctl/ctl_env_config2.cfg
- test/ctl/ctl_env_driver.cpp
- test/test_valgrind.sh
> load ctl defaults from env variable/file

- examples/dram_and_fsdax/dram_and_fsdax.c
- test/ipc_devdax_prov_consumer.c
- test/ipc_devdax_prov_producer.c
- test/pools/jemalloc_coarse_devdax.cpp
- test/pools/scalable_coarse_devdax.cpp
- test/provider_devdax_memory.cpp
- test/provider_devdax_memory_ipc.cpp
- test/provider_file_memory.cpp
- test/provider_file_memory_ipc.cpp
Fix null pointer dereference in createDevDaxParams().
It fixes the Coverity issue no. 485528.
> Fix null pointer dereference in createDevDaxParams()

- .github/workflows/pr_push.yml
- .github/workflows/reusable_compatibility.yml
- CMakeLists.txt
- ChangeLog
- src/libumf.c
- src/memspaces/memspace_host_all.c
- src/memtargets/memtarget_numa.c
- src/pool/pool_jemalloc.c
- src/provider/provider_os_memory.c
- src/topology.c
- src/topology.h
- test/common/provider.hpp
- test/pools/jemalloc_pool.cpp
- Merge back stable (along with v1.0.1 release) into main.
- BTW, update the compat tests tag
> Merge stable v1.0.x into main

- .github/workflows/reusable_checks.yml
- src/base_alloc/base_alloc.c
- src/pool/pool_jemalloc.c
- fix inaccessible -> unaccessible typo
- update typos script to v1.35.5
> bump typos

- src/ctl/ctl.c
- src/utils/utils_log.c
- test/ctl/ctl_api.cpp
- test/ctl/ctl_env_app.cpp
- test/ctl/ctl_env_driver.cpp
- test/utils/utils_log.cpp
Logger configuration failed when set via the CTL env variable because
the API used const char ** while the env var provided const
char *. This mismatch affected the size field (sizeof(char *)==8
vs. string length).
The API now accepts char * instead of char **.
> fix logger when enabled thru ctl

- CMakeLists.txt
It's required for hwloc static linking - in hwloc's configure step
> [CMake] Fail early in configure, if autoreconf is missing

- src/libumf.c
initialize hwloc topology only before first fork, not always
> initialize hwloc topology only before first fork, not always

- src/provider/provider_cuda.c
- test/providers/cuda_helpers.cpp
load libcuda.so.1 instead of libcuda.so on linux
> load libcuda.so.1 instead of libcuda.so on linux

- .github/dependabot.yml
As UMF is a little slowed down for the moment, it's not required to update dependencies as often (to not spam our history with just deps' updates).
> Run dependabot updates less often for now
