oneapi-src/unified-memory-framework

- README.md
- test/CMakeLists.txt
- test/common/pool.hpp
- test/common/provider.hpp
- test/common/umf_helpers.hpp
- test/memoryPool.hpp
- test/memoryPoolAPI.cpp
- test/memoryProvider.hpp
- test/memoryProviderAPI.cpp
- test/test_helpers.c
- test/test_helpers.h
> Add memoryPool and memoryProvider tests

- src/pool/disjoint/pool_disjoint.cpp
> Replace free with delete in disjoint_pool_finalize()

- CMakeLists.txt
- README.md
> Add UMF_BUILD_TESTS option (ON by default)

- src/pool/disjoint/pool_disjoint.cpp
- test/CMakeLists.txt
- test/disjoint_pool.cpp
> Add disjointPool test

- include/pool/pool_disjoint.h
- src/pool/disjoint/pool_disjoint.cpp
- src/pool/disjoint/pool_disjoint_impl.cpp
- src/pool/disjoint/pool_disjoint_impl.hpp
- test/c_api/disjoint_pool.c
- test/common/pool.hpp
- test/disjoint_pool.cpp
- test/memoryPool.hpp
- test/memoryPoolAPI.cpp
Relies on: https://github.com/oneapi-src/unified-memory-framework/pull/28
> Disjoint pool shared limits

- include/provider/provider_coarse.h
- src/CMakeLists.txt
- src/provider/provider_coarse.c
> Use RAVL tree in coarse provider

- .github/workflows/basic.yml
- third_party/requirements.txt
Add new configurations like os, compiler, build type, etc. based on the GithubActions main workflow's configuration in the Unified Runtime.
> Extend GithubActions basic workflow

- src/provider/provider_os_memory.c
> Fix three structure names

- src/pool/pool_disjoint.cpp
> Fix: print errors to stderr instead of stdout

- third_party/requirements.txt
Revised API documentation theme to be more similar to UR.
Preview:
https://szadam.github.io/unified-memory-framework/
> Revised API documentation theme

- .github/workflows/basic.yml
- .github/workflows/benchmarks.yml
- .github/workflows/codeql.yml
- .github/workflows/spellcheck.yml
The main idea behind this PR is to provide ground for further changes in the CI area.
My goal is to change the CI to cascade model:
This commit allows to start workflow by another
workflow and make dependencies between them.
> Allow to execute workflows by workflow caller

- third_party/requirements.txt
this PR fixes building HTML docs
> require specific versions of sphinxcontrib to gen docs

- .github/workflows/.spellcheck-conf.toml
- src/CMakeLists.txt
- src/base_alloc/base_alloc.c
- src/base_alloc/base_alloc.h
- src/base_alloc/base_alloc_internal.h
- src/base_alloc/base_alloc_linux.c
- src/base_alloc/base_alloc_windows.c
- src/utils/utils_common.h
- src/utils/utils_concurrency.h
- src/utils/utils_posix_concurrency.c
- src/utils/utils_windows_concurrency.c
- test/CMakeLists.txt
- test/common/test_helpers.h
- test/test_base_alloc.c
Add a MT-safe fixed-size-pool base allocator.
> Add base allocator

- include/umf/providers/provider_os_memory.h
- src/memory_targets/memory_target_numa.c
- test/pools/jemalloc_pool.cpp
- test/pools/scalable_pool.cpp
- test/provider_os_memory.cpp
- test/provider_os_memory_config.cpp
To limit boilerplate in tests and user code.
> Add function for returning default os params

- test/test_base_alloc_linear.c
Shortly: make master green again
> Add void param to main function to meet strict C requirements

- src/base_alloc/base_alloc_linear.c
The linear base allocator fails with OOM now,
when it runs out of memory requested in `umf_ba_linear_create()`.
The linear base allocator is used to allocate structures
which size depends on number of nodes for example,
so it is not known before calling `umf_ba_linear_create()`.
This patch adds a feature that the pool of linear allocator can "grow"
(a new memory region is allocated from OS in fact)
when more space is needed.
> Do not fail linear allocator with OOM

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
- CONTRIBUTING.md
- README.md
We should consider this as the first version of this document. It should be updated with more content as we go.
> Extend Contribution Guide

- src/base_alloc/base_alloc_linear.c
- src/utils/utils_common.h
- test/common/test_helpers.h
- test/test_base_alloc_linear.cpp
The first (main) pool has just been freed except of the first page containing the metadata. The pool size has to be updated and set to the size of one page.
> Fix computing ptr and update pool_size

- test/memoryPoolAPI.cpp
> [tests] Fix: Use of auto that causes a copy

- .github/workflows/basic.yml
- .github/workflows/benchmarks.yml
- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/nightly.yml
- .github/workflows/pr_push.yml
- .github/workflows/proxy_lib.yml
- .github/workflows/sanitizers.yml
- .github/workflows/scorecard.yml
- .github/workflows/spellcheck.yml
Besides some cleanups and updates, it fixes two issues:
- https://github.com/oneapi-src/unified-memory-framework/issues/123
- https://github.com/oneapi-src/unified-memory-framework/issues/169
Fixes: #123
Fixes: #169
> [CI] Update and extend workflows

- README.md
- include/umf/memspace.h
- src/CMakeLists.txt
- src/libumf.def
- src/libumf.map
- src/libumf_linux.c
- src/memspaces/memspace_host_all.c
- src/memspaces/memspace_host_all_internal.h
- test/CMakeLists.txt
- test/memspace_host_all.cpp
> Add predefined HOST ALL memspace

- test/memoryProviderAPI.cpp
> Fix problem with auto that causes a copy

- src/memspaces/memspace_host_all.c
This PR fixes coverity issue #437904 https://scan3.scan.coverity.com/#/project-view/65229/15141?selectedIssue=437904
> return error when hwloc_get_nbobjs_by_type fails

- include/umf/providers/provider_level_zero.h
Fix building docs and remove unused Level Zero provider args
> Fix building docs and remove unused L0 prov args

- .github/pull_request_template.md
- CONTRIBUTING.md
A PR template with basic requirements. I'm open for any additons (or changes) that could help us improve the quality 😉
> Add Pull Request template

- .github/workflows/sanitizers.yml
Related issue: https://github.com/actions/runner-images/issues/9491
> Fix ubuntu-22.04 runner issue

- src/base_alloc/base_alloc_global.c
- src/critnib/critnib.c
- test/supp/umf_test-jemalloc_pool.supp
Fix memcheck errors.
There are still 3 failures on nightly build after the fixes: https://github.com/igchor/unified-memory-framework/actions/runs/8269325299/job/22624345633
I've opened an issue for them as I'm not sure what's the issue yet: https://github.com/oneapi-src/unified-memory-framework/issues/338
> Fix memcheck errors

- test/test_valgrind.sh
> Skip tests incompatible with valgrind

- .github/workflows/basic.yml
- cmake/helpers.cmake
- test/test_installation.py
Ref: https://github.com/oneapi-src/unified-memory-framework/issues/341
> Fix building UMF as shared library on MacOS

- test/memspaces/memspace_helpers.hpp
> Fix segfault in the memspaceNumaProviderTest.allocFree test

- README.md
- include/umf/memspace.h
- src/CMakeLists.txt
- src/libumf.map
- src/libumf_linux.c
- src/memory_target.c
- src/memory_target.h
- src/memory_target_ops.h
- src/memory_targets/memory_target_numa.c
- src/memspace.c
- src/memspace_internal.h
- src/memspaces/memspace_highest_capacity.c
- src/memspaces/memspace_host_all.c
- src/topology.c
- src/topology.h
- test/CMakeLists.txt
- test/memspaces/memspace_highest_capacity.cpp
This PR adds new 'high-capacity' memspace
Ref: https://github.com/oneapi-src/unified-memory-framework/issues/230
> High capacity memspace

- .github/workflows/qemu.yml
fix qemu workflow - change ubuntu image wget path
> fix qemu workflow - change ubuntu image wget path

- src/utils/utils_sanitizers.h
Remove including redundant header.
> Remove including redundant header

- .github/workflows/proxy_lib.yml
Add test for the proxy library based on the jemalloc pool.
It depends on #380.
> Add test for the proxy library based on the jemalloc pool

- .github/workflows/bandit.yml
- README.md
- scripts/generate_docs.py
- test/test_installation.py
Run [Bandit tool](https://github.com/PyCQA/bandit) as part of the CI.
Enabling this workflow require adding a few nosec "skips", as I believe they don't apply for us - in test and dev. scripts.
> Add bandit scanner workflow

- examples/basic/basic.c
> fix newlines in the example

- .github/workflows/coverity.yml
- third_party/requirements.txt
2 small security fixes:
- bump `pygments` version a little
- add missing global permissions for coverity job
Checklist:
> Security fixes

- .github/workflows/basic.yml
Test the shared version of the UMF library on Windows.
> Test the shared version of the UMF library on Windows

- src/provider/provider_tracking.c
Verify trackers's parameters in trackingInitialize().
> Verify trackers's parameters in trackingInitialize()

- benchmark/CMakeLists.txt
- benchmark/multithread.hpp
- src/critnib/critnib.c
- test/common/multithread_helpers.hpp
- test/ipcAPI.cpp
- test/supp/drd-umf_test-ipc.supp
Refactor tests and benchmark code to share multithread utils between benchmarks and tests.
> Share multithread utils between tests and benchmarks

- README.md
- scripts/docs_config/introduction.rst
State in README and web docs intro that this project is a WIP. To be removed, when we're ready for 1.0.0 relase.
Readme preview: https://github.com/lukaszstolarczuk/unified-memory-framework/tree/wip-disclaimer?tab=readme-ov-file#introduction
Web preview: https://lukaszstolarczuk.github.io/unified-memory-framework/introduction.html
> [Docs] Add WIP disclaimer

- test/common/pool_trace.c
- test/common/pool_trace.h
- test/common/provider_trace.c
- test/common/provider_trace.h
- test/common/test_helpers.c
- test/common/test_helpers.h
- test/ipcAPI.cpp
- test/memoryPoolAPI.cpp
- test/memoryProviderAPI.cpp
* Removed unnecessary synchronization to increase contention.
* Added additional checks to the provider_mock_ipc provider.
* Refactor pool_trace and provider_trace
Ref. #412
> Improve tests for IPC

- src/memory_target.c
- src/memspaces/memspace_numa.c
- src/provider/provider_os_memory.c
- src/provider/provider_tracking.c
> remove unnecessary cast after malloc-ish functions

- README.md
Everyone can see what a horse looks like.
> [readme] Add information about black formatter

- README.md
- scripts/docs_config/introduction.rst
and a link to it in CONTRIBUTION.md
Fixes: #431
// Preview on my fork: https://lukaszstolarczuk.github.io/unified-memory-framework/
> [Doc] Redo web docs

- scripts/qemu/run-build.sh
- test/test_valgrind.sh
Run tests under valgrind memcheck on Qemu.
> Run tests under valgrind memcheck on QEMU

- .github/workflows/basic.yml
- .github/workflows/sanitizers.yml
- test/ipc_os_prov.sh
Check if sudo requires password in the ipc_os_prov test.
> Check if sudo requires password in the ipc_os_prov test

- test/ipcAPI.cpp
- test/ipcFixtures.hpp
- test/providers/provider_level_zero.cpp
Enable IPC tests for the Level Zero provider.
The main challenge was to unify work with host and device memory.
> Enable IPC tests for Level Zero provider

- include/umf/providers/provider_os_memory.h
- src/provider/provider_os_memory.c
- src/utils/utils_concurrency.h
- test/provider_os_memory.cpp
- test/provider_os_memory_multiple_numa_nodes.cpp
- test/test_valgrind.sh
> implment interleave mode with customizable size

- benchmark/ubench.c
> Add error messages to ubench

- src/provider/provider_level_zero.c
Cleanup IPC handle implementation in L0 provider.
> Cleanup IPC handle impl in L0 provider

- .github/workflows/pr_push.yml
remove unused UMF_BUILD_LIBUMF_POOL_SCALABLE from workflow
> remove unused UMF_BUILD_LIBUMF_POOL_SCALABLE

- src/utils/utils_log.c
- test/utils/utils_log.cpp
> log: append instead of create new file in logger

- examples/basic/ipc_level_zero.c
- examples/basic/utils_level_zero.h
- Added `level_zero_fill` and `level_zero_copy` functions to the `utils_level_zero.h` to be used in the L0 examaples.
- Extended `ipc_level_zero.c` example to fill the initial buffer with some pattern and verify that mapped buffer contains the same pattern.
> Extend ipc_level_zero.c example

- include/umf.h
Add missing extern "C" to umf.h.
> Add missing extern "C" to umf.h

- src/utils/utils_concurrency.h
I am not sure why it was not detected during the compilation.
> Minor fix in util_atomic_store_release

- .github/workflows/gpu.yml
- benchmark/CMakeLists.txt
- benchmark/ubench.c
> Add benchmarks for IPC API

- .github/workflows/multi_numa.yml
> [CI] Enable multi-numa workflow on RHEL

- .github/dependabot.yml
> [Security] Dependabot - ignore format dependencies auto update

- .github/workflows/bandit.yml
- .github/workflows/codeql.yml
- .github/workflows/pr_push.yml
- .github/workflows/trivy.yml
This PR probably works - not sure how to check it. Maybe someone who has more experience with GHa can validate it. 
ref: #584
> do not run builds twice on dependabot PRs

- src/CMakeLists.txt
- src/libumf.rc.in
- src/proxy_lib/CMakeLists.txt
- src/proxy_lib/proxy_lib.rc.in
> add rc file for windows

- CMakeLists.txt
- test/test_installation.py
- third-party-programs.txt
> add Third Party Programs file

- .github/workflows/coverity.yml
Since this PR Coverity can also be executed
for another branch. Previous solutions always
cloned the main branch.
> [CI] Add branch context to the Coverity

- examples/CMakeLists.txt
- examples/custom_provider/file_provider.c
- examples/memspace/memspace_hmat.c
- examples/memspace/memspace_numa.c
- scripts/docs_config/examples.rst
Propably CI will fail but @igchor  please review if it is something what you requested ;)
> add examples

- cmake/helpers.cmake
> Remove WX MSVC compiler option

- licensing/third-party-programs.txt
add googletest to 3rd party programs
> add googletest to 3rd party programs

- test/test_valgrind.sh
Fix one comment in `test/test_valgrind.sh`.
> Fix one comment in test/test_valgrind.sh

- .github/workflows/basic.yml
Add Ubuntu 24.04 build in basic workflow
> [CI] Add Ubuntu 24.04 build

- test/memspaces/memspace_fixtures.hpp
The PR is a part of a major fix, which will be provided in multiple files.
Ref. #569
> fix: substitute UT_ASSERTs with asserts from GTEST part 2

- .github/workflows/fast.yml
Fix [#629](https://github.com/oneapi-src/unified-memory-framework/issues/629)
> Change the name of the install dependencies step in fastbuild

- .github/workflows/basic.yml
- CMakeLists.txt
- cmake/FindJEMALLOC.cmake
- cmake/FindLIBHWLOC.cmake
- cmake/FindTBB.cmake
- examples/cmake/FindLIBHWLOC.cmake
- examples/cmake/FindTBB.cmake
- src/CMakeLists.txt
new fixes for rc4:
* add custom hwloc lib name
* use *_DLL_DIRS env
> new fixes for rc4

- test/test_examples.sh
- test/test_valgrind.sh
Fix comparing strings in bash.
> Fix comparing strings in bash

- src/CMakeLists.txt
- src/ravl/ravl.c
- src/ravl/ravl.h
Add RAVL tree for Coarse Provider.
This code is a part of from https://github.com/oneapi-src/unified-memory-framework/pull/378.
The code of RAVL tree comes from https://github.com/pmem/pmdk/blob/master/src/core/ravl.c
Ref: #378
> Add RAVL tree for Coarse Provider

- test/memspaces/memspace_fixtures.hpp
- test/memspaces/memspace_helpers.hpp
- test/memspaces/memspace_host_all.cpp
The PR is a part of a major fix, which will be provided in multiple files.
Ref. #569
> fix: substitute UT_ASSERTs with asserts from GTEST part 3

- cmake/helpers.cmake
> Handle development tags in versioning

- .github/workflows/devdax.yml
Set `UMF_TESTS_DEVDAX_SIZE` from `ndctl-list` output.
> Set UMF_TESTS_DEVDAX_SIZE from ndctl-list output

- src/provider/provider_coarse.c
Fix missing unlock() in Coarse Provider.
> Fix missing unlock() in Coarse Provider

- CMakeLists.txt
- cmake/helpers.cmake
- src/CMakeLists.txt
- src/libumf.def
- src/libumf.map
- src/memspaces/memspace_highest_bandwidth.c
- src/memspaces/memspace_highest_capacity.c
- src/memspaces/memspace_host_all.c
- src/memspaces/memspace_lowest_latency.c
- src/memspaces/memspace_numa.c
- src/provider/provider_cuda.c
- src/provider/provider_devdax_memory.c
- src/provider/provider_file_memory.c
- src/provider/provider_level_zero.c
- src/provider/provider_os_memory.c
related to https://github.com/oneapi-src/unified-memory-framework/issues/568
> remove optional symbols

- test/ipcFixtures.hpp
One more test for IPC functionality
> Add new IPC test: openInTwoPools

- .github/workflows/pr_push.yml
Compute partial coverage on forks.
> Compute partial coverage on forks

- test/memoryProviderAPI.cpp
Add missing base tests for providers.
It increases code coverage of the `src/memory_provider.c` file.
- from 149/164 lines (90.9 %)
- to: 163/164 lines (99.4 %)
> Add missing base tests for providers

- test/CMakeLists.txt
- test/common/ipc_common.c
- test/common/ipc_common.h
- test/ipc_devdax_prov_consumer.c
- test/ipc_devdax_prov_producer.c
- test/ipc_file_prov_consumer.c
- test/ipc_file_prov_producer.c
- test/ipc_os_prov_consumer.c
- test/ipc_os_prov_producer.c
- test/providers/ipc_level_zero_prov_consumer.c
- test/providers/ipc_level_zero_prov_producer.c
* change IPC tests to use Pool (Scalable - requires TBB, Disjoint for GPU) instead of Provider API
* add 60 sec timeout for IPC tests
> use pools not only providers in IPC tests

- test/CMakeLists.txt
- test/utils/utils_linux.cpp
> Add tests for utils_common to improve coverage

- test/CMakeLists.txt
Fix linking tests with libcuda.
> Fix linking tests with libcuda

- test/utils/utils_linux.cpp
This PR fixes coverity issues: fd shouldn't be negative.
There is no regression in coverage.
> Fix `utils_linux.cpp` coverity defects

- CMakeLists.txt
- src/CMakeLists.txt
This is a cherry-picked patch merged to the v0.9 branch: #882
> Add a RUNPATH to installed libraries

- src/utils/utils_common.h
- src/utils/utils_posix_common.c
- src/utils/utils_windows_common.c
- test/utils/utils_linux.cpp
Add tests for utils_posix_common.c
Ref: #923
> Add tests for utils_posix_common.c

- .github/workflows/reusable_gpu.yml
- CMakeLists.txt
- benchmark/CMakeLists.txt
- benchmark/benchmark.cpp
- benchmark/benchmark.hpp
- benchmark/benchmark_interfaces.hpp
- benchmark/multithread.cpp
- benchmark/ubench.c
- cmake/helpers.cmake
Add benchmarks to the main branch.
> Merge stable v0.10.x branch into main

- licensing/third-party-programs.txt
update 3rd party programs file with uthash, nvidia CUDA runtime and google bench licenses
> update 3rd party programs file (uthash, google bench)

- test/test_valgrind.sh
Fix paths of logs in test_valgrind.sh.
It fixes the following issue:
https://github.com/ldorau/unified-memory-framework/actions/runs/12540110461/job/34967028717
> Fix paths of logs in test_valgrind.sh

- src/provider/provider_cuda.c
- test/providers/cuda_helpers.cpp
- test/providers/cuda_helpers.h
- test/providers/provider_cuda.cpp
add set/restore context in CUDA provider free()
also add test for multi-context alloc/free scenario
> add set/restore context in CUDA provider free()

- .github/workflows/nightly.yml
Add a missing option for saving benchmark results executed as a part of Nightly
> Save benchmark results in nightly.yml

- .github/workflows/nightly.yml
Fix for ICX for Windows
https://github.com/intel12232289/unified-memory-framework/actions/runs/13258241739
Fixes: https://github.com/oneapi-src/unified-memory-framework/issues/843
> ICX For Windows

- src/base_alloc/base_alloc.c
Add missing unlock in an error handling path of `umf_ba_alloc()`.
> Add missing `unlock()` in an error handling path of `umf_ba_alloc()`

- benchmark/benchmark.cpp
> Enable MT bench for disjoint_pool in fixed provider

- include/umf/pools/pool_disjoint.h
- src/pool/pool_disjoint.c
- src/pool/pool_disjoint_internal.h
> [disjoint] Change pool name setting and cleanup

- benchmark/benchmark.cpp
> reduce number of benchmark threads with disjoint pool

- src/libumf.def
- src/libumf.map
These functions first appeared in 0.12.0
> Move CTL functions into 0.12 sections (in .map/.def files)

- test/ctl/ctl_api.cpp
Fix for Coverity issue
** CID 478076
test/ctl/ctl_api.cpp
> Fix for uninitialized variable

- test/supp/drd-test_ipc.supp
- test/supp/drd-test_ipc_max_opened_limit.supp
- test/supp/drd-test_provider_file_memory_ipc.supp
- test/supp/helgrind-test_ipc.supp
- test/supp/helgrind-test_ipc_max_opened_limit.supp
- test/supp/helgrind-test_provider_file_memory_ipc.supp
Remove suppressions with `umfGetIPCHandle`.
Valgrind CI job did not fail after more than 3 hours in a loop without them:
https://github.com/ldorau/unified-memory-framework/actions/runs/14102107909/job/39500349219
and
https://github.com/ldorau/unified-memory-framework/actions/runs/14103079278/job/39503388963
Ref: #1169
> Remove suppressions with `umfGetIPCHandle`

- .github/workflows/nightly.yml
- .github/workflows/pr_push.yml
- .github/workflows/reusable_gpu.yml
// Nightly preview: https://github.com/oneapi-src/unified-memory-framework/actions/runs/14115303808
> [CI] Enable L0 tests with BMG gpu card

- .github/workflows/reusable_benchmarks.yml
- .github/workflows/reusable_docs_build.yml
> update benchmarks script

- .github/workflows/reusable_benchmarks.yml
> fix benchmarks for PRs

- .github/workflows/reusable_benchmarks.yml
> fix benchmark workflow part 2

- test/fuzz/umfFuzz.cpp
> add missing const in fuzz tests

- .github/workflows/reusable_checks.yml
- third_party/requirements.txt
and in "checks" job install only using pip.
> Add missing python requirements for various tools

- .github/workflows/reusable_sycl.yml
// sycl test preview: https://github.com/oneapi-src/unified-memory-framework/actions/runs/14710419318/job/41281156029?pr=1291
> Fix SYCL job in nightly

- scripts/qemu/configs/sock_8_var1_hmat.xml
- test/memspaces/memspace_highest_bandwidth.cpp
> test correct memory bind with highest bandwidth memspace

- src/memory_pool.c
- test/memoryPoolAPI.cpp
Validate flags inside `umfPoolCreateInternal()`.
> Validate flags inside umfPoolCreateInternal()

- .github/workflows/reusable_valgrind.yml
Describe precisely the drdshort valgrind job.
The "drdshort" option means that very long lasting tests are disabled.
> Describe precisely the drdshort valgrind job

- test/CMakeLists.txt
fix "provdier" typo in cmake file
required by #1348
> fix "provdier" typo in cmake file

- test/provider_fixed_memory.cpp
> Add tests for umfFixedMemoryProviderParamsSetMemory

- src/provider/provider_os_memory.c
> fix error handling in os_provider

- examples/cuda_shared_memory/cuda_shared_memory.c
- examples/level_zero_shared_memory/level_zero_shared_memory.c
> fix error handling in examples

- src/pool/pool_disjoint.c
- src/provider/provider_cuda.c
> add missing \0 in case of strcpy() too long string

- .github/workflows/pr_push.yml
- .github/workflows/reusable_compatibility.yml
bump compat tag in CI to v0.12.0-dev3
> bump compat tag in CI to v0.12.0-dev3

- src/pool/pool_disjoint.c
> [disjoint] fix pool version

- .github/workflows/reusable_multi_numa.yml
> sles-15 is back

- test/ctl/ctl_unittest.cpp
> fix coverity issue

- .github/workflows/nightly.yml
- .github/workflows/reusable_basic.yml
- .github/workflows/reusable_codeql.yml
- .github/workflows/reusable_compatibility.yml
- .github/workflows/reusable_fast.yml
- .github/workflows/reusable_gpu.yml
- .github/workflows/reusable_sanitizers.yml
nigthly tested in https://github.com/oneapi-src/unified-memory-framework/actions/runs/16349737851
> [CI] Add vcpkg caching in Win workflows

- src/pool/pool_disjoint.c
> add missing lock in ctl

- .github/workflows/nightly.yml
- .github/workflows/pr_push.yml
// tested all BMG jobs in here: https://github.com/oneapi-src/unified-memory-framework/actions/runs/17490472334/job/49678944640?pr=1513
> [CI] Enable BMG testing on Windows
